### ISSUE TITLE
Error getGroupInviteLink after createGroup - Cannot read properties of undefined (reading 'isGroup')

### ISSUE THREAD

**Issue by jversolato** [orkestral/venom#1118]
## Description

Error return invite link after creating a group

## Environment

- **Venom version(s):** 3.1.4
- **Browser:** [ Chromium 85]
- **OS:** [Mac]
- **Node version:** [v16.8.0

## Steps to Reproduce

1. Run code
2. Read Qcode
3. CreateGroup

## Log Output
/Users/juliano/Documents/JULIANO/PROJETOS/PROJETOSE1/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isGroup')
    at Object.window.WAPI.window.WAPI.getGroupInviteLink (/Users/juliano/Documents/JULIANO/PROJETOS/PROJETOSE1/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:34673)
    at __puppeteer_evaluation_script__:1:34
    at ExecutionContext._evaluateInternal (/Users/juliano/Documents/JULIANO/PROJETOS/PROJETOSE1/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/juliano/Documents/JULIANO/PROJETOS/PROJETOSE1/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

const venom   = require('venom-bot')

venom.create().then(function start(client) {
	
    let groupId = "";
    client.createGroup('Group name', [
        '00000000@c.us'
      ]).then((result) => {
        console.log('Result GROUP: ', result); //return object success

        groupId = result.gid._serialized;

        client.getGroupInviteLink(groupId).then((resultInvite) => {
            console.log('Result: ', resultInvite); //return object success
          })
          .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
          });

      })
      .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
      });

});

**Comment by orkestral** [comment]
after some tests we verified that venom have no obvious errors, recheck your code

**Comment by Dima564** [comment]
Having the same issue.

**Comment by JimmyBastos** [comment]
Having the same issue
