### ISSUE TITLE
Error: Evaluation failed: TypeError: this._find is not a function

### ISSUE THREAD

**Issue by fquero47** [orkestral/venom#1136]
when i try to reply a message. it gives me the followin error:

Error: Evaluation failed: TypeError: this._find is not a function
    at j._serverQuery (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:334921)

**Comment by AlexsandroZanella2** [comment]
This also happens to me when I try to send a message to a number I've never talked to before.

**Comment by AlexsandroZanella2** [comment]
(node:22424) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: this._find is not a function
    at j._serverQuery (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:334921)
    at j._query (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:334450)
    at j.find (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:332582)
    at Object.window.WAPI.window.WAPI.getChat (<anonymous>:1:55806)
    at Object.window.WAPI.window.WAPI.sendExist (<anonymous>:1:30002)
    at async Object.window.WAPI.window.WAPI.sendMessage (<anonymous>:1:40000)
    at ExecutionContext._evaluateInternal (d:\projetos-hos\merch\Projetos Web\Hos.WhatsApp\API\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (d:\projetos-hos\merch\Projetos Web\Hos.WhatsApp\API\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by fquero47** [comment]
Solved with npm update venom-bot
