### ISSUE TITLE
 message is missing critical data needed to download the file

### ISSUE THREAD

**Issue by mitjarogl** [orkestral/venom#1170]
## Description

When I execute `buffer = await client.decryptFile(message);` I get this error.

## Environment

- **Venom version(s): 3.2.0
- **Browser: Chrome 93.0.4577.82
- **OS: mac os 11.5.2
- **Node version: v12.18.0

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
message is missing critical data needed to download the file.
    at Whatsapp.<anonymous> (/Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/whatsapp.js:208:35)
    at step (/Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/whatsapp.js:48:23)
    at Object.next (/Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/whatsapp.js:29:53)
    at /Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/whatsapp.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/whatsapp.js:19:12)
    at Whatsapp.decryptFile (/Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/whatsapp.js:197:16)
    at EventEmitter.<anonymous> (/Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/index.js:100:39)
    at EventEmitter.emit (events.js:315:20)
    at /Users/mitjarogl/Development/Projects/Nudge-labs/whatsapp-bot/node_modules/venom-bot/dist/api/layers/listener.layer.js:189:90

```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jonalan7** [comment]
of a print on your error!

**Comment by mitjarogl** [comment]
@jonalan7 I added errro log

**Comment by mitjarogl** [comment]
@jonalan7 Also, when I call this method `downloadMedia(message.id)` I get this error ` { error: true, code: 'media_not_found', message: 'Media not found' }`. Is any other way to get media file? Thanks

**Comment by jonalan7** [comment]
I believe the file you are wanting to download is no longer available!

**Comment by mitjarogl** [comment]
@jonalan7 If I try to `downloadMedia` in chat other than my self then it works.
