### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by curruwilla** [orkestral/venom#119]
`(node:70623) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/uiliacom/nodevenv/notification/12/lib/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/uiliacom/nodevenv/notification/12/lib/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/home/uiliacom/nodevenv/notification/12/lib/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:70623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:70623) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Checking for updates`

Localhost works fine, but when I go up to my host using cpanel, I get this error ... how to fix it?

**Comment by joel-vasiliev** [comment]
Im having the same issue
