### ISSUE TITLE
Sending messages does not work after whatsapp crash

### ISSUE THREAD

**Issue by jonnathanlopes** [orkestral/venom#1193]
There was some change after the crash of whatsapp, my system doesn't work anymore, it logs in with qr code but doesn't send messages.

**Comment by galbuqp** [comment]
Here too, I tried with multiple devices activated and cant send messages. But when I tried desactivating the multiple devices feature it worked.

**Comment by jonnathanlopes** [comment]
I'm getting the following error

0|index  | Error: Evaluation failed: TypeError: e.includes is not a function
0|index  |     at Object.window.WAPI.window.WAPI.sendExist (/home/jonnathan/apps/wppapi/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:30862)
0|index  |     at async Object.window.WAPI.window.WAPI.getNewMessageId (/home/jonnathan/apps/wppapi/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:65626)
0|index  |     at async Object.window.WAPI.window.WAPI.sendMessage (/home/jonnathan/apps/wppapi/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:42932)
0|index  |     at ExecutionContext._evaluateInternal (/home/jonnathan/apps/wppapi/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|index  |     at async ExecutionContext.evaluate (/home/jonnathan/apps/wppapi/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by rlucredio** [comment]
The same for me. It only works when i send message to a contact already on the phone.

**Comment by marciodiasdeveloper** [comment]
+1

**Comment by jonnathanlopes** [comment]
> Messages are being sent normally! download the latest version!

i used the latest version but i'm getting the same error. There was no change in my code. Why the topic was closed if it was not resolved? there are reports of other users here with same issue

**Comment by jonnathanlopes** [comment]
> Messages are being sent normally! download the latest version!

latest version the same problem here
<img width="1043" alt="Screen Shot 2021-10-06 at 14 10 33" src="https://user-images.githubusercontent.com/26045692/136251415-c28bde72-fb77-480d-95c0-db9ad96800ce.png">
