### ISSUE TITLE
Cannot read property '_serialized' of undefined

### ISSUE THREAD

**Issue by raulluque** [orkestral/venom#1210]
(node:34780) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property '_serialized' of undefined
    at Object.window.WAPI.window.WAPI.sendExist (/var/www/wavektor/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:31342)
    at async Object.l [as sendFile] (/var/www/wavektor/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:24700)
    at ExecutionContext._evaluateInternal (/var/www/wavektor/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/var/www/wavektor/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
(node:34780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by raulluque** [comment]
Este erro aparece em um único telefone quando desejo enviar uma mensagem, com os outros telefones funciona corretamente

**Comment by malikmub** [comment]
I have the same issue !

**Comment by orkestral** [comment]
fixed in version 4.0.1
