### ISSUE TITLE
Sending message to a blocked contact throws: "Cannot read property 'erro' of undefined" 

### ISSUE THREAD

**Issue by HENRDS** [orkestral/venom#1233]
## Description

Error `Cannot read property 'erro' of undefined` when sending message to a blocked contact.

## Environment

- **Venom version(s):** 3.1.11
- **Browser:** Cromium r818858 
- **OS:** Windows 10
- **Node version:** Node 14

## Steps to Reproduce

1. Block a contact in your phone
2. Attempt to send a message to the blocked contact using venom

## Log Output

```
(node:58040) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
    at Whatsapp.<anonymous> (D:\Workspace\dream.message.client\node_modules\venom-bot\dist\api\layers\sender.layer.js:200:47)
    at step (D:\Workspace\dream.message.client\node_modules\venom-bot\dist\api\layers\sender.layer.js:48:23)
    at Object.next (D:\Workspace\dream.message.client\node_modules\venom-bot\dist\api\layers\sender.layer.js:29:53)
    at fulfilled (D:\Workspace\dream.message.client\node_modules\venom-bot\dist\api\layers\sender.layer.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:58040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Code

```
const venom = require('venom-bot');

async function asyncCall(client) {
	try {
		number = '<blocked number>';
		let result = await client.sendText(`${number}@c.us`, 'Hello from Venom!');
		console.log('Result: ', result);
	} 
        catch (err) {
		console.error('Error when sending: ', err); 

	}
}

async function start() {
	try {
		const client = await venom.create('session');
		await asyncCall(client);
	}
	catch (error) {
		console.error(error);
	} 
}

start();


```

**Comment by orkestral** [comment]
fixed in version 4.0.1
