### ISSUE TITLE
client.getBatteryLevel()

### ISSUE THREAD

**Issue by hafidzaini** [orkestral/venom#125]
cant get battery level value.

```
client.getBatteryLevel().then(val =>{
            console.log(val)
            console.log(val.json())
        }).catch(e => {
            // error
            console.log(e);
        })
```
Error: Evaluation failed: ReferenceError: output is not defined
    at Object.window.WAPI.getBatteryLevel (/Users/h/Downloads/app/wavenom/node_modules/venom-bot/dist/lib/wapi/wapi.js:10:41839)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (/Users/h/Downloads/app/wavenom/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/hh/Downloads/app/wavenom/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/h/Downloads/app/wavenom/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/Users/h/Downloads/app/wavenom/node_modules/puppeteer/lib/DOMWorld.js:89:24)

**Comment by joaosouz4** [comment]
@hafidzaini 
**can u use** 
`let conn = await client.getHostDevice();`
**to get battery use**
`let battery = conn.battery`
