### ISSUE TITLE
Cannot get profilePhotoThumbUrl when using headless

### ISSUE THREAD

**Issue by foomoto** [orkestral/venom#1268]
## Description

client.getProfilePicFromServer(phone) fails when using headless mode

## Environment

- **Venom version(s): 4.0.1
- **Node version: 14

## Steps to Reproduce

Configure headless client
venom.create('cw', (qrImg, b)=> {
//  sendQr(b);
}, null, {
  multidevice: false,
  headless: true, // Headless chrome
  devtools: false, // Open devtools by default
  useChrome: false, // If false will use Chromium instance
  debug: false, // Opens a debug session
  logQR: true, // Logs QR automatically in terminal
  browserArgs: ['--no-sandbox'], // Parameters to be added into the chrome browser instance
  refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
});

Attempt to get profile pic
client.getProfilePicFromServer(phone).then((url) => {
  console.log('irl' + url);
}).catch((e) => {
    console.log(e);
})

## Log Output

Error: Evaluation failed: U [    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

    at async Promise.all (index 0)]([url](`url`))

## Additional context / Screenshot

This issue only happens in headless, and we would like to use venom on a server.

**Comment by foomoto** [comment]
Issue was on me thanks. I removed Promises.race to resolve this issue.
