### ISSUE TITLE
Erro ao carregar grupos usando a função getAllChatsGroups()

### ISSUE THREAD

**Issue by felipebadr** [orkestral/venom#1271]
## Description

Ao tentar carregar os grupos ele retorna  ReferenceError: groupId is not defined
Só testei usando multidevice: false

## Environment

- **Venom version(s):** 4.0.1
- **Browser:** Chrome 95
- **OS:** OSX 11.6
- **Node version:** 14

## Steps to Reproduce

```js
const chats = await client.getAllChatsGroups();
console.log(chats);
```

## Log Output
```
(node:26882) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: groupId is not defined
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Script

```js
venom
	.create({
		session: 'session-test',
		multidevice: false
	})
	.then((client) => { 
		const chats = await client.getAllChatsGroups();
	        console.log(chats);
	})
	.catch((erro) => {
		console.log('Venom error: '+erro);
	});
```

**Comment by zly0321** [comment]
？？？

**Comment by zly0321** [comment]
解决了吗？

**Comment by felipebadr** [comment]
Solução temporária:

```js
async function getAllGroups(client) {
	let grupos = [];
	let chats = await client.getAllChats();
	for (chat of chats) {
		if (chat.isGroup)
			grupos.push(chat);
	}
	return grupos;
}
```

**Comment by orkestral** [comment]
fixed in version 4.0.2

**Comment by zly0321** [comment]
> Ao tentar carregar os grupos ele retorna ReferenceError: groupId is not defined
> Só testei usando multidevice: false

Has not solved this problem 4.0.2

**Comment by zly0321** [comment]
Erro ao carregar grupos usando a função getAllChatsGroups，Não resolvi este problema
