### ISSUE TITLE
Unhandled rejection, and promise never resolved/rejected on sendContactVcard

### ISSUE THREAD

**Issue by voxsoftware** [orkestral/venom#1302]
## Description

Unhandled rejection, and promise never rejected or resolved on sendContactVcard when invalid parameters. 

## Environment

- **Venom version(s):** 4.0.2
- **Browser:** Not relevant
- **OS:** Linux, Ubuntu 21.04
- **Node version:** Node 14

## Steps to Reproduce

1. Send invalid parameters to method sendContactVcard. For example send any text instead of a contactId

## Your Code

```typescript
await client.sendContactVcard("xxxxx@c.us", ["Not a correct contactId"])
```

## Additional context / Screenshot

```bash
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
    at Whatsapp.<anonymous> (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:874:47)
    at step (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:48:23)
    at Object.next (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:29:53)
    at fulfilled (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

I think can be solved checking ```result``` is an object in this portion of code:

File: ```venom-bot/dist/api/layers/sender.layer.js```

```javascript
SenderLayer.prototype.sendContactVcard = function (to, contactsId, name) {
        return __awaiter(this, void 0, void 0, function () {
            var _this = this;
            return __generator(this, function (_a) {
                return [2 /*return*/, new Promise(function (resolve, reject) { return __awaiter(_this, void 0, void 0, function () {
                        var result;
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0: return [4 /*yield*/, this.page.evaluate(function (_a) {
                                        var to = _a.to, contactsId = _a.contactsId, name = _a.name;
                                        return WAPI.sendContactVcard(to, contactsId, name);
                                    }, { to: to, contactsId: contactsId, name: name })];
                                case 1:
                                    result = _a.sent();
                                    if (result['erro'] == true) { // here need a good detect if result is null
                                        reject(result);
                                    }
                                    else {
                                        resolve(result);
                                    }
                                    return [2 /*return*/];
                            }
                        });
                    }); })];
            });
        });
    };
```

**Comment by voxsoftware** [comment]
@orkestral Why close without any response?
