### ISSUE TITLE
Cannot read property 'state' of undefined on 2.2146.9

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#1305]
## Description

`````
 (node:20) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'state' of undefined
 at __puppeteer_evaluation_script__:3:56
 at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

`````

## Environment

- **Venom version(s):** [4.0.2]
- **Browser:** [Chrome]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by neocomun** [comment]
Mesmo erro

**Comment by jonalan7** [comment]
**This bug has now been fixed!**

**Comment by antirek** [comment]
no more error
