### ISSUE TITLE
Cannot read properties of undefined (reading 'wid') on 3.1.12

### ISSUE THREAD

**Issue by acognigni-evotecnia** [orkestral/venom#1308]
## Description

it happens when i try to send buttons. no message is sent and i getr an error in terminal

## Environment

- **Venom version(s):** 3.1.12
- **Browser:** default ( i didnt configure a specific one)
- **OS:** windows 10 19041.1348
- **Node version:** 14.15.0

## Steps to Reproduce

attempt to sendButtons

## Log Output

**Important note** : attempting to set the logger level returned " Cannot set property 'level' of undefined" so the included log was generated without it

```
(node:8136) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'wid')
    at Object.window.WAPI.window.WAPI.sendListMenu (C:\Users\EvoU\Desktop\Augusto\Mis-fuentes\node\ChatBotServired\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:42489)
    at ExecutionContext._evaluateInternal (C:\Users\EvoU\Desktop\Augusto\Mis-fuentes\node\ChatBotServired\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\EvoU\Desktop\Augusto\Mis-fuentes\node\ChatBotServired\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Your Code

```
	const menuautenticar = [
		{
			buttonText: {
				displayText: 'Soy afiliado.'
			}
		},
		{
			buttonText: {
				displayText: 'No estoy afiliado.'
			}
		},
		// {
		// 	buttonText: {
		// 		displayText: 'Contacto con Asesor'
		// 	}
		//}
	]
	if (message.body === 'Hola' || ultimomensaje >= 21600 || ultimomensaje === null) {
		msm = await Client.sendButtons(
			message.from,
			'welcome to XXX. i'm your virtual assistant.',
			menuautenticar,
			'we couldn't find your phone in our databse.'
		)
      }
```

**Comment by KelseyJr** [comment]
I've updated to the latest version and this error is gone.

**Comment by acognigni-evotecnia** [comment]
Seems to be working. Closing ticket
