### ISSUE TITLE
Cannot read properties of undefined (reading 'modelClass')

### ISSUE THREAD

**Issue by Dancrf** [orkestral/venom#1311]
## Description

`Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'modelClass')
    at u (C:\Users\****\Desktop\****\****\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:25845)
    at async Object.w (C:\Users\****\Desktop\****\****\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:26510)
    at ExecutionContext._evaluateInternal (C:\Users\****\Desktop\****\****\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\****\Desktop\****\****\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)`

## Environment

- **Venom version(s):** [4.0.3]
- **Browser:** [Chrome]
- **OS:** [Windows 10]
- **Node version:** [Node 17.1]

## Steps to Reproduce

This error started to appear when sending an image as a sticker

**Comment by vphelipe** [comment]
I'm with the same problem, by my analysis there is no longer the "Store.conn" module

**Comment by kayronbrigido** [comment]
I'm with the same problem
