### ISSUE TITLE
Cannot read property 'attributes' of undefined in getBatteryLevel on 2.2146.9

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#1312]
## Description
`````
 (node:25) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'attributes' of undefined
   at Object.window.WAPI.window.WAPI.getBatteryLevel (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:70062)
   at __puppeteer_evaluation_script__:1:28
   at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
   at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
 (Use `node --trace-warnings ...` to show where the warning was created)
 (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async functi
on without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.ht
ml#cli_unhandled_rejections_mode). (rejection id: 1)
 (node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
 will terminate the Node.js process with a non-zero exit code.
`````

## Environment

- **Venom version(s):** [4.0.3]
- **Browser:** [Chrome]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by pedroayres** [comment]
It was fixed on version 4.0.3

**Comment by antirek** [comment]
No

**Comment by jonalan7** [comment]
@antirek fix!

**Comment by antirek** [comment]
Yeah! 🤩🤩🤩🤩🤩

**Comment by antirek** [comment]
@jonalan7 I checked, it's ok!
