### ISSUE TITLE
TypeError: Cannot read property '_serialized' of undefined

### ISSUE THREAD

**Issue by henrickJona** [orkestral/venom#1313]
## Description

When trying to get WA number, this error happens

## Environment

- **Venom version(s):** [4.0.3]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Log Output

```
[Nest] 7201   - 2021-11-25 11:48:07   [ExceptionsHandler] Cannot read property '_serialized' of undefined +34819ms
TypeError: Cannot read property '_serialized' of undefined
    at WhatsappService.showStatus (/home/jonathan/doGit/api-whatsapp-com-alteraçoes-2/api-whatsapp/dist/src/providers/whatsapp/whatsapp.service.js:172:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WhatsappConService.getStatus (/home/jonathan/doGit/api-whatsapp-com-alteraçoes-2/api-whatsapp/dist/src/modules/whatsappCon/whatsappCon.service.js:42:28)
    at async WhatsappConController.getStatus (/home/jonathan/doGit/api-whatsapp-com-alteraçoes-2/api-whatsapp/dist/src/modules/whatsappCon/whatsappCon.controller.js:32:26)
    at async /home/jonathan/doGit/api-whatsapp-com-alteraçoes-2/api-whatsapp/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /home/jonathan/doGit/api-whatsapp-com-alteraçoes-2/api-whatsapp/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

## Your Code

```
async showStatus() {
    const getHostDevice = await this.client.getHostDevice();
    console.log(getHostDevice, 'tedt');
    const response = await Promise.all([
      getHostDevice.wid._serialized,
      'this.client.getBatteryLevel(),',
      this.client.isConnected(),
      this.client.isLoggedIn(),
      this.client.getWAVersion(),
    ]);
    const resp = {
      mode: 'MAIN',
      myNumber: this.handleNumberToDefaultFormat(response[0]),
      batteryLevel: response[1],
      isPhoneConnected: response[2],
      isLoggedIn: response[3],
      waVersion: response[4],
    };

    return resp;
  }
```

**Comment by vphelipe** [comment]
I'm with the same problem, by my analysis there is no longer the "Store.conn" module
