### ISSUE TITLE
Coordinates for location not found in the message

### ISSUE THREAD

**Issue by Eider3a** [orkestral/venom#1317]
## Coordinates not found

Hi guys I hope you are doing great. Something happens when I try to send coordinates to the phone connected to the bot, In the message, I can not find the coordinates for the location.

Yesterday I installed version 4.0.2 and now I have this issue.

I appreciate it if you can help with a workaround or if you can check what's going on.
Thanks a lot.

**Comment by clovisdanielss** [comment]
Same problem.

```js
(node:20) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Invalid value at currentMsg.lng: value is invalid
    at t.checkValid (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:2:400086)
    at t.encodeProtobuf (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:2:406732)
    at https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:57:34029    at t.convertToMessageRowType (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:57:34099)
    at https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:57:28629    at Array.map (<anonymous>)
    at https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:57:28579    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.16dd6b40d060cbb692f2.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.16dd6b40d060cbb692f2.js:2:63995)
    at ExecutionContext._evaluateInternal (/home/node/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)      
    at async ExecutionContext.evaluate (/home/node/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```
