### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'takeover' of undefined

### ISSUE THREAD

**Issue by GabrielBels** [orkestral/venom#1328]
I'm getting the error message below when I disconnect my WhatsApp by the phone.

Error: Evaluation failed: TypeError: Cannot read property 'takeover' of undefined
at Object.window.WAPI.window.WAPI.takeOver (C:\Users\GabrielBelisario\Desktop\BOT_Aguiar\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:73382)
at puppeteer_evaluation_script:1:28
at ExecutionContext._evaluateInternal (C:\Users\GabrielBelisario\Desktop\BOT_Aguiar\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ExecutionContext.evaluate (C:\Users\GabrielBelisario\Desktop\BOT_Aguiar\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

**Comment by GabrielBels** [comment]
> Estou com o mesmo problema aqui.

Solução paleativa que estou aplicando: quando ocorrer, apagar o arquivo "auth-info.json" e reiniciar a instância. Feito isso, poderá ler o QR Code novamente.
