### ISSUE TITLE
Help: client.getProfilePicFromServer not working

### ISSUE THREAD

**Issue by foomoto** [orkestral/venom#1330]
client.getProfilePicFromServer() does not work except if the contact info is visible in the web dom to puppeteer.

If you try this client.getProfilePicFromServer('2348147343133@c.us')

You get the error

Error: Evaluation failed: U
    at ExecutionContext._evaluateInternal (/Users/eng/cw/whatsapp-images/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/eng/cw/whatsapp-images/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async /Users/eng/cw/whatsapp-images/server.js:65:40

If you open this contact on the WhatsApp Web browser first and try again. You get the profile pic url

**Comment by foomoto** [comment]
client.getProfilePicFromServer() does not work except if the contact info is visible in the web dom to puppeteer.

If you try this client.getProfilePicFromServer('2348147343133@c.us')

You get the error

Error: Evaluation failed: U
at ExecutionContext._evaluateInternal (/Users/eng/cw/whatsapp-images/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ExecutionContext.evaluate (/Users/eng/cw/whatsapp-images/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
at async /Users/eng/cw/whatsapp-images/server.js:65:40

If you open this contact on the WhatsApp Web browser first and try again. You get the profile pic url
