### ISSUE TITLE
sendVideoAsGif crashing

### ISSUE THREAD

**Issue by SLotman** [orkestral/venom#1340]
## Description

When calling sendVideoAsGif, the bot crashes.

## Environment

- **Venom version(s):** 4.0.4-alpha.0
- **Browser:** Chrome 96.0.4664.45, 64 bits 
- **OS:** Windows 10
- **Node version:** Node 16.13.0

## Steps to Reproduce

1. Just try the example on this page. Sending mp4/avi/gif or webp makes no difference, it crashes the same way.

await client.sendVideoAsGif(
  '000000000000@c.us',
  'path/to/video.mp4',
  'video.gif',
  'Gif image file'
);

## Log Output
 Error: Evaluation failed: TypeError: e.match is not a function
    at new l (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:61:32741)
    at new o (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:61:37695)
    at Object.window.WAPI.window.WAPI.sendVideoAsGif (<anonymous>:1:48748)
    at __puppeteer_evaluation_script__:3:34
    at ExecutionContext._evaluateInternal (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

## Additional context / Screenshot
Doesn't matter if multidevice is true or false. Setting "useChrome" to true or false makes no difference either.

**Comment by SLotman** [comment]
Small update: I managed to at least stop the crash.

In wapi.js, where it says: "window.WAPI.sendVideoAsGif=function(t,n,i,a,o)", change it to
"window.WAPI.sendVideoAsGif=async function(t,n,i,a,o)"

Then, where it says "return Store.Chat.find(r).then"
change it to "return await Store.Chat.find(r).then"

Where it says "c(n,r).then((e=>{"
change it to "c(n,r).then((async e=>{"

And finally, where it says "t.mediaPrep.sendToChat("
change it to "await t.mediaPrep.sendToChat("

This will stop the crash, but nothing will show up in the chat either :/

**Comment by SLotman** [comment]
This probably means the send-video-as-gif.js should be:

export async function sendVideoAsGif(dataBase64, chatid, filename, caption, done) {
  const idUser = new Store.WidFactory.createWid(chatid);
  return await Store.Chat.find(idUser).then((chat) => {
    var mediaBlob = base64ToFile(dataBase64, filename);
    processFiles(chat, mediaBlob).then((async mc) => {
      var media = mc.models[0];
      media.mediaPrep._mediaData.isGif = true;
      media.mediaPrep._mediaData.gifAttribution = 1;
      await media.mediaPrep.sendToChat(chat, { caption: caption });
      if (done !== undefined) done(true);
    });
  });
}

But still, nothing shows up in the chat :(

**Comment by SLotman** [comment]
WHY was this closed? The issue isn't solved!
