### ISSUE TITLE
Cannot sendMessage (throw an error)

### ISSUE THREAD

**Issue by duhsyahrizal** [orkestral/venom#1341]
## Description

[Description of the bug, When Issue Happens]
When i try to sending a message in venom, throw an error

## Log Output
throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'wid' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (/home/rad/development/whatsapp-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1705:45)
    at ExecutionContext._evaluateInternal (/home/rad/development/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/rad/development/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by chrisk8er** [comment]
Hi... i got same issue...

**Comment by duhsyahrizal** [comment]
> Hi... i got same issue...

Only update to newest version of venom, it'll be work again..

**Comment by duhsyahrizal** [comment]
> > Hi... i got same issue...
> 
> Only update to newest version of venom, it'll be work again..

Or try to fresh install of venom newest version
