### ISSUE TITLE
getProfilePicFromServer error

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#1375]
## Description

client.getProfilePicFromServer(chatId)

return error 

`````
Error: Evaluation failed: G
   at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
   at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

`````

## Environment

- **Venom version(s):** [4.0.4]
- **Browser:** [e.g. Chrome 87]
- **OS:** [ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by jonalan7** [comment]
using multidevice?

**Comment by antirek** [comment]
@jonalan7 No
