### ISSUE TITLE
Error Cannot read property 'product' of null

### ISSUE THREAD

**Issue by joel-vasiliev** [orkestral/venom#1417]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** e.g. 4.0.4
- **Browser:** Chromium 938248
- **OS:** Windows 10 Pro (WSL: Ubuntu)
- **Node version:** Node 14.8.2 (I also tested with node 17+ and node 8.x)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output ## 

```
TypeError: Cannot read property 'product' of null
    at new BrowserFetcher (/home/joel/another-test/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:158:34)
    at PuppeteerNode.createBrowserFetcher (/home/joel/another-test/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Puppeteer.js:185:16)
    at PuppeteerExtra.createBrowserFetcher (/home/joel/another-test/node_modules/puppeteer-extra/dist/index.cjs.js:175:26)
    at /home/joel/another-test/node_modules/venom-bot/dist/controllers/browser.js:229:64
    at step (/home/joel/another-test/node_modules/venom-bot/dist/controllers/browser.js:44:23)
    at Object.next (/home/joel/another-test/node_modules/venom-bot/dist/controllers/browser.js:25:53)
    at /home/joel/another-test/node_modules/venom-bot/dist/controllers/browser.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/joel/another-test/node_modules/venom-bot/dist/controllers/browser.js:15:12)
    at initBrowser (/home/joel/another-test/node_modules/venom-bot/dist/controllers/browser.js:218:12)
```

## Your Code

```

const express = require('express');
const venom = require('venom-bot');
const app = express();
const server = require('http').createServer(app);
const io = require('socket.io')(server, {cors: {origin: "*"}});

app.set("view engine", "ejs");

app.get('/home', (req, res) => {
    res.render('home');
  });

app.use(express.static(__dirname + '/images'));

server.listen(3001, () => {
  console.log('listening on port 3001')
})

io.on('connection', (socket) => {
  
  console.log('User connected:' + socket.id);

  socket.on("message", () => {
      venom
      .create({
        
        headless: true, // Headless chrome
        devtools: false, // Open devtools by default
        useChrome: false, // If false will use Chromium instance
        debug: false, // Opens a debug session
        logQR: true, // Logs QR automatically in terminal
        folderNameToken: "token",
        session: 'sessionName',
        browserArgs: ["--no-sandbox","--disable-setuid-sandbox"],
        disableSpins: true,
        disableWelcome: true,
        updatesLog: true,
        catchQR: (base64Qr, asciiQR) => {
          console.log(asciiQR); // Optional to log the QR in the terminal
          var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
            response = {};

          if (matches.length !== 3) {
            return new Error('Invalid input string');
          }

          response.type = matches[1];
          response.data = new Buffer.from(matches[2], 'base64');
          
          var imageBuffer = response;

          require('fs').writeFile(
            './images/out.png',
            imageBuffer['data'],
            'binary',
            function (err) {
              if (err != null) {
                console.log(err);
              }
            }
          );
        },
      })
      .then((client) => {start(client);})
      .catch((error) => console.log(error));
      
      function start(client) {  
        client.onStateChange((state) => {
            socket.emit('message', 'Status: ' + state);  
            console.log('State changed: ', state);
            //socket.disconnect(true);           
          });
          }
    });

  socket.on("ready", () => {
      setTimeout(function () {
            socket.emit('ready', './out.png');
          },3000);
    });


  });

```

**Comment by marciodiasdeveloper** [comment]
+1

**Comment by marciodiasdeveloper** [comment]
useChrome: true .... solved

**Comment by joel-vasiliev** [comment]
bem que eu queria, seria tão simples hahah

**Comment by joel-vasiliev** [comment]
[SOLVED]
I was using WSL 2, I have just installed node, npm and yarn on powershell and run the code on Windows and it worked
