### ISSUE TITLE
Error: Evaluation failed: TypeError: (t || "").trim is not a function

### ISSUE THREAD

**Issue by bourdog** [orkestral/venom#142]

**Comment by bourdog** [comment]
> I had to reinstall my OS (Ubuntu 20.04) and migrate my project to the "new" OS but this's what i got :

(node:10989) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: (t || "").trim is not a function
    at v (https://web.whatsapp.com/app2.215119033c36173424fb.js:2:1020444)
    at Object.t.sendTextMsgToChat [as SendTextMsgToChat] (https://web.whatsapp.com/app2.215119033c36173424fb.js:2:1020033)
    at t.window.Store.sendMessage (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:10:21409)
    at t.sendMessage (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:10:36150)
    at Object.window.WAPI.sendMessage (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:10:27526)
    at __puppeteer_evaluation_script__:8:41
    at ExecutionContext._evaluateInternal (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/helper.js:95:27)
    at Whatsapp.<anonymous> (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:89:49)
    at step (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.sendText (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:87:16)
  -- ASYNC --
    at Page.<anonymous> (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/puppeteer/lib/helper.js:94:19)
    at Whatsapp.<anonymous> (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:89:49)
    at step (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.sendText (/home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:87:16)
    at /home/bourdog/Documentos/IGOR-2020/Projetos/Nextech/BOT-Whatsapp/scr/index.js:23:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10989) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
