### ISSUE TITLE
Evaluation failed: TypeError: Cannot read property 'profilePicThumb' of undefined

### ISSUE THREAD

**Issue by FerryAr** [orkestral/venom#1438]
## Description

Method GetHostDevice() returned  Evaluation failed: TypeError: Cannot read property 'profilePicThumb' of undefined

## Environment

- **Venom version(s):** 4.0.3
- **Browser:** Chromium 85
- **OS:** Windows 10
- **Node version:** Node 17.1.0

## Steps to Reproduce

1. create nestjs project
2. use venom-bot as service on nestjs
3. use method getHostDevice()
## Log Output

```
Error: Evaluation failed: TypeError: Cannot read property 'profilePicThumb' of undefined
    at Object.window.WAPI.window.WAPI._serializeMeObj (D:\whatsapp-api\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:36453)
    at async Object.window.WAPI.window.WAPI.getHost (D:\whatsapp-api\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:69530)
    at ExecutionContext._evaluateInternal (D:\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (D:\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
```

## Your Code

```
const client = await create(
      sessionName,
      (base64Qr, asciiQR) => {
        //save qr to file
        const base64Data = base64Qr.replace(/^data:image\/png;base64,/, '');
        fs.writeFile(
          './qr/' + sessionName + '.png',
          base64Data,
          'base64',
          function (err) {
            // console.log("GAGAL LEK, reason" + err);
          },
        );
      },
      (statusFind) => {
        console.log(statusFind);
      },
      {
        headless: true,
        devtools: false,
        useChrome: false,
        debug: false,
        logQR: false,
        multidevice: false,
        browserArgs: [
          '--log-level=3',
          '--no-default-browser-check',
          '--disable-site-isolation-trials',
          '--no-experiments',
          '--ignore-gpu-blacklist',
          '--ignore-certificate-errors',
          '--ignore-certificate-errors-spki-list',
          '--disable-gpu',
          '--disable-extensions',
          '--disable-default-apps',
          '--enable-features=NetworkService',
          '--disable-setuid-sandbox',
          '--no-sandbox',
          '--disable-webgl',
          '--disable-threaded-animation',
          '--disable-threaded-scrolling',
          '--disable-in-process-stack-traces',
          '--disable-histogram-customizer',
          '--disable-gl-extensions',
          '--disable-composited-antialiasing',
          '--disable-canvas-aa',
          '--disable-3d-apis',
          '--disable-accelerated-2d-canvas',
          '--disable-accelerated-jpeg-decoding',
          '--disable-accelerated-mjpeg-decode',
          '--disable-app-list-dismiss-on-blur',
          '--disable-accelerated-video-decode',
          '--single-process', // <- this one doesn't works in Windows
        ],
        autoClose: 60000,
        createPathFileToken: true,
        puppeteerOptions: {},
      },
    );
     const device = await client.getHostDevice();
      const id: any = device.id;
```

**Comment by rafosolima** [comment]
This problem is due to venom's _serializedMeObj, it was adjusted in version 4.0.5, if you upgrade and it doesn't work try changing the useChrome to true.

In my case I can't even access the browser by doing this.

And if you try to keep the same version of venom 4.0.3, it will give you the checkNumber problem, but if you want to persist, you can get the waPage instance and manipulate the popertier to validate this function by not using _serializedMeObj

```
venom.create(
    //session
    'sessionName', //Pass the name of the client you want to start the bot
    //catchQR
    (base64Qrimg, asciiQR, attempts, urlCode) => {
      console.log('Number of attempts to read the qrcode: ', attempts);
      console.log('Terminal qrcode: ', asciiQR);
      console.log('base64 image string qrcode: ', base64Qrimg);
      console.log('urlCode (data-ref): ', urlCode);
    },
    // statusFind
    (statusSession, session) => {
      console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
      //Create session wss return "serverClose" case server for close
      console.log('Session name: ', session);
    },
    // options
    {
      folderNameToken: 'tokens', //folder name when saving tokens
      mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
      headless: true, // Headless chrome
      devtools: false, // Open devtools by default
      useChrome: true, // If false will use Chromium instance
      debug: false, // Opens a debug session
      logQR: true, // Logs QR automatically in terminal
      browserWS: '', // If u want to use browserWSEndpoint
      browserArgs: [''], // Parameters to be added into the chrome browser instance
      puppeteerOptions: {}, // Will be passed to puppeteer.launch
      disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
      disableWelcome: true, // Will disable the welcoming message which appears in the beginning
      updatesLog: true, // Logs info updates automatically in terminal
      autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
      createPathFileToken: false, //creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
    },
    // BrowserSessionToken
    // To receive the client's token use the function await clinet.getSessionTokenBrowser()
    {
      WABrowserId: '"UnXjH....."',
      WASecretBundle:
        '{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
      WAToken1: '"0i8...."',
      WAToken2: '"1@lPpzwC...."',
    },
    (browser, waPage) => {
          // get instance waPage here
     }
  )
  .then((client) => start(client))
  .catch((error) => console.log(error));
```

**Comment by hueltonsantos** [comment]
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket')
1|zap  |     at Object.window.WAPI.window.WAPI._serializeMeObj (/var/www/chathuelton/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:37735)
1|zap  |     at Object.window.WAPI.window.WAPI.getNumberProfile (/var/www/chathuelton/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:70557)
1|zap  |     at ExecutionContext._evaluateInternal (/var/www/chathuelton/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
1|zap  |     at runMicrotasks (<anonymous>)
1|zap  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1|zap  |     at async ExecutionContext.evaluate (/var/www/chathuelton/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
1|zap  |     at async /var/www/chathuelton/sessions.js:367:34
1|zap  |     at async Function.sendText (/var/www/chathuelton/sessions.js:365:38)
1|zap  |     at async Object.recebeDados (/var/www/chathuelton/livechat.js:119:9)
1|zap  |     at async sendText (/var/www/chathuelton/index.js:333:3)

**Comment by hueltonsantos** [comment]
Bom dia pessoal 
Alguém sabe porque desse erro ?
estou usando o venom, e estava funcionando tranquilo, depois que não funiconou mais
