### ISSUE TITLE
Problem updating venom-bot to 4.0.4 or higher

### ISSUE THREAD

**Issue by GuilhermeHumberto** [orkestral/venom#1445]
Hi,

I have a problem when I try to update venom-bot to version 4.0.4 or 4.0.5.

In version 4.0.3, I have no problem.

Looking at the releases, in version 4.0.4 the puppeteer has been updated. Could that have been it? Anyone having the same problem?

The error happens when running the ```yarn start:debug``` command

- Node Version: v17.4.0
- NPM Version: v8.3.1

``` 
TypeError: Cannot read properties of null (reading 'product')
    at new BrowserFetcher (/home/guilherme/Workspace/whatsapp-http-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:158:34)
    at PuppeteerNode.createBrowserFetcher (/home/guilherme/Workspace/whatsapp-http-api/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:185:16)
    at PuppeteerExtra.createBrowserFetcher (/home/guilherme/Workspace/whatsapp-http-api/node_modules/puppeteer-extra/dist/index.cjs.js:175:26)
    at /home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/browser.js:242:64
    at step (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/browser.js:44:23)
    at Object.next (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/browser.js:25:53)
    at /home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/browser.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/browser.js:15:12)
    at initBrowser (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/browser.js:231:12)
```
---

**Comment by marciodiasdeveloper** [comment]
useChrome: true, solved!

**Comment by GuilhermeHumberto** [comment]
@marciodiasdeveloper 

Thanks for the answer, but when I activate this flag, the error below appears:

``` 
TypeError: Cannot read property 'session' of undefined
    at /home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/initializer.js:175:72
    at step (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/initializer.js:98:23)
    at Object.next (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/initializer.js:79:53)
    at fulfilled (/home/guilherme/Workspace/whatsapp-http-api/node_modules/venom-bot/dist/controllers/initializer.js:70:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
```

**Comment by mufer19** [comment]
useChrome: false,        
puppeteerOptions: {
    product: "chrome"
}
