### ISSUE TITLE
Can't list groups

### ISSUE THREAD

**Issue by AndersonVale** [orkestral/venom#1449]
## Description

When trying to execute "client.getAllChatsGroups()" i get this error:

**Error: Evaluation failed: ReferenceError: groupId is not defined
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/home/andersonvale/Documentos/node_projetos/pmmcZap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/andersonvale/Documentos/node_projetos/pmmcZap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)**

## Environment

- **Venom version(s): 4.0.5
- **Browser: Postman
- **OS: Ubuntu

**Comment by Havaiano78** [comment]
Very sad... I also get the same when I try to send a message to the group

![image](https://user-images.githubusercontent.com/88166804/152371515-1eefb84f-de69-427b-b051-86a4ab2a2ea0.png)

**Comment by Havaiano78** [comment]
I was developing a robot for the company where I work, now stopped the project, must be some whatsapp update

**Comment by jonalan7** [comment]
This problem has already been fixed! Update to the newest version!

**Comment by vielhuber** [comment]
This error is still present in all nightlies. Any update on this?
