### ISSUE TITLE
Issue when compiling venom and running it

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#145]
Disclaimer - I have never used javascript or typescript. I am Python C# selenium guy.

Compiling Issues - 
Downloaded the code, ran `tsc tsconfig.json`.
Files in lib folder were not copied to the dist folder whereas the readme file claims so.

Running issue - 
After Copying the files to required folder I ran the following code - 
```const venom = require('./index');<br/>
venom
  .create()
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });
function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}
```
And it gave the following error - 

```
√ Checking for updates
√ Compilation Mutation
Error: Evaluation failed: ReferenceError: WAPI is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:5:29)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:6:27)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (C:\Users\bhavy\Downloads\venom-master\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WaitTask.rerun (C:\Users\bhavy\Downloads\venom-master\node_modules\puppeteer\lib\DOMWorld.js:404:23)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\bhavy\Downloads\venom-master\node_modules\puppeteer\lib\helper.js:94:19)
    at WaitTask.rerun (C:\Users\bhavy\Downloads\venom-master\node_modules\puppeteer\lib\DOMWorld.js:404:71)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

What should I do? I really want to shift from selenium.

**Comment by edgardmessias** [comment]
According to https://github.com/orkestral/venom#development, you need first run `npm run build:wapi ....`, but you can just use `npm run build`, because it contains all steps
