### ISSUE TITLE
Erro when try send Image a Sticker

### ISSUE THREAD

**Issue by kayronbrigido** [orkestral/venom#1464]
Log:

(node:14052) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: o.sendToChat is not a function
    at u (C:\Users\Kayron\Desktop\projetos\curso\venomBot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:26273)
    at async Object.w (C:\Users\Kayron\Desktop\projetos\curso\venomBot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:26631)
    at ExecutionContext._evaluateInternal (C:\Users\Kayron\Desktop\projetos\curso\venomBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Users\Kayron\Desktop\projetos\curso\venomBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(node:14052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Dependecies:
"gify": "^0.2.0",
"venom-bot": "^4.0.5"

OS: windows 10

I'm having this problem, it happens when I send an image and try to turn it into a sticker

Code Line:

if (message.isMedia === true || message.isMMS === true) {
      const buffer = await client.decryptFile(message);
      const fileName = `./src/img/imgSticker.${mime.extension(message.mimetype)}`;
      await fs.writeFile(fileName, buffer, async (err) => {
        if (err) {
          console.log(err)
        } else {
          await client
            .sendImageAsSticker(message.from, fileName)
            .then((result) => {
              console.log('Result: ', result); //return object success
            })
            .catch((erro) => {
              console.error('Error when sending: ', erro); //return object error
            });
        }
      });
    }

**Comment by KstmSoft** [comment]
Same error here
