### ISSUE TITLE
Cannot read properties of undefined (reading 'Socket')

### ISSUE THREAD

**Issue by samuelnovaes** [orkestral/venom#1529]
## Description

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket') after reading QR code.

## Environment

- **Venom version(s):** 4.0.6
- **Browser:** Chrome 98.0.4758.102
- **OS:** Linux Mint 20.3 64 bits
- **Node version:** 16.13.1

## Steps to Reproduce

1. Use the latest version of WhatsApp
2. Use Venom 4.0.6
3. Read QR code

## Log Output

```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket')
    at Object.window.WAPI.window.WAPI._serializeMeObj (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:37635)
    at Object.window.WAPI.window.WAPI.getHost (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:72368)
    at ExecutionContext._evaluateInternal (/home/samuel/Documentos/talkone-ws/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/samuel/Documentos/talkone-ws/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```

## Your Code

```javascript
const client = await venom.create(
	process.env.ACCOUNT,
	async (base64Qrimg) => {
		socket.emit('qrcode', base64Qrimg);
	},
	(statusGet) => {
		console.log(statusGet);
	},
	{
		logQR: false,
		disableWelcome: true,
		disableSpins: true,
		multidevice: account.multiDevice,
		autoClose: false,
		headless: false
	}
);
```

**Comment by AlexsandroZanella2** [comment]
Use [nightly release](https://github.com/orkestral/venom/tree/nightly) 4.0.7.alpha0

**Comment by samuelnovaes** [comment]
> Use [nightly release 4.0.7.alpha.0](https://github.com/orkestral/venom/releases/tag/nightly)

It worked for me. Thanks!
