### ISSUE TITLE
Still can't list groups

### ISSUE THREAD

**Issue by AndersonVale** [orkestral/venom#1538]
puppeteer throws an error when trying to list groups:

Error: Evaluation failed: ReferenceError: groupId is not defined
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/home/andersonvale/Documentos/node_projetos/pmmcZap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/andersonvale/Documentos/node_projetos/pmmcZap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

venom  version: 4.0.7

**Comment by Luury** [comment]
same problem
venom version: 4.0.9

**Comment by ArmandoTL** [comment]
same problem :/
