### ISSUE TITLE
Error on SendLocation

### ISSUE THREAD

**Issue by RubensCruz88** [orkestral/venom#1559]
## Description

When I use the SenLocation function, it returns an error.

## Environment

- Venom version: 4.0.9
- Chrome version 99.0.4844.51
- Windows 10
- Node version v16.14.0

## Log Output

D:\Cursos\Node\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Invalid value at currentMsg.lng: value is invalid
    at t.checkValid (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:264221)
    at t.encodeProtobuf (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:271026)
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:66:38033
    at t.convertToMessageRowType (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:66:38103)
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:66:32430
    at Array.map (<anonymous>)
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:66:32380
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at ExecutionContext._evaluateInternal (D:\Cursos\Node\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\Cursos\Node\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

## Your Code

```node.js
async function whatsApp(){
	const whats = await venom
	.create('monitoramento', //Pass the name of the client you want to start the bot
	  undefined, //catchQR
	  (statusSession, session) => { // statusFind
		// return: isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
		console.log('Status Session: ', statusSession);
		// create session wss return "serverClose" case server for close
		console.log('Session name: ', session);
	  },
	);

whats
	.sendLocation('5511966617066@c.us', '-13.6561589', '-69.7309264')
	.then((result) => {
	  console.log('Result: ', result); //return object success
	})
	.catch((erro) => {
	  console.error('Error when sending: ', erro); //return object error
	});
```

**Comment by fernandopraise** [comment]
home/hap/Sistemas/Agendamento/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Invalid value at currentMsg.lng: value is invalid
    at t.checkValid (https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:5:264221)
    at t.encodeProtobuf (https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:5:271026)
    at https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:66:38033
    at t.convertToMessageRowType (https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:66:38103)
    at https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:66:32430
    at Array.map (<anonymous>)
    at https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:66:32380
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at ExecutionContext._evaluateInternal (/home/hap/Sistemas/Agendamento/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/hap/Sistemas/Agendamento/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
