### ISSUE TITLE
sendLinkPreview

### ISSUE THREAD

**Issue by diegosystem32** [orkestral/venom#1561]
## Description
Error in sendLinkPreview()

## Environment
- **Venom version(s):4.0.9
- **Browser:** Chrome

## Log Output
Error: Evaluation failed: Error: Unexpected null or undefined: BUNDLE
    at t.default (https://web.whatsapp.com/:2:398)
    at Object.t.get (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:66:358541)
    at Function.encrypt (https://web.whatsapp.com/bootstrap_main.c62fbbc905c14131281e.js:5:7442)
    at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.c62fbbc905c14131281e.js:2:114672)
    at t.default.write (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:249992)
    at Object.<anonymous> (https://web.whatsapp.com/bootstrap_main.c62fbbc905c14131281e.js:2:98703)
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213
    at ExecutionContext._evaluateInternal (C:\Users\Diego\Documents\Node Projects\DS_BOT_BACK-END\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (C:\Users\Diego\Documents\Node Projects\DS_BOT_BACK-END\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)

**Comment by luteroelavoco** [comment]
i have the same bug

**Comment by luteroelavoco** [comment]
> ## Description
> Error in sendLinkPreview()
> 
> ## Environment
> * **Venom version(s):4.0.9
> * **Browser:** Chrome
> 
> ## Log Output
> Error: Evaluation failed: Error: Unexpected null or undefined: BUNDLE at t.default (https://web.whatsapp.com/:2:398) at Object.t.get (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:66:358541) at Function.encrypt (https://web.whatsapp.com/bootstrap_main.c62fbbc905c14131281e.js:5:7442) at t.default. (https://web.whatsapp.com/bootstrap_main.c62fbbc905c14131281e.js:2:114672) at t.default.write (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:249992) at Object. (https://web.whatsapp.com/bootstrap_main.c62fbbc905c14131281e.js:2:98703) at Generator.next () at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943) at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154) at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213 at ExecutionContext._evaluateInternal (C:\Users\Diego\Documents\Node Projects\DS_BOT_BACK-END\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13) at processTicksAndRejections (node:internal/process/task_queues:96:5) at ExecutionContext.evaluate (C:\Users\Diego\Documents\Node Projects\DS_BOT_BACK-END\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
