### ISSUE TITLE
Venom-bot does not stay connected

### ISSUE THREAD

**Issue by Ale-Floripa** [orkestral/venom#1573]
## Description

Hello!!

I'm new with Venom-bot and I'm creating a project and when I try to connect my whats on the phone, to test whats shows a message to "scan the code again". And when he accesses it stays for a few minutes and leaves. And displays this message in the terminal. Could it be some update on whatsapp? Can someone help me?

## Environment

- **Venom version(s):** v4.0.9
- **Browser:** Chrome default version
- **OS:**  Windows 10
- **Node version:** v15.8.0

## Message in terminal

info:     [sessionName] Waiting... checking the browser...
info:     [sessionName] Browser successfully opened
info:     [sessionName] checking headless...
info:     [sessionName] headless option is active, browser hidden
info:     [sessionName] Checking page...
info:     [sessionName] Page successfully accessed
× [instance: sessionName]: Page Closed
× [instance: sessionName]: Failed to authenticate
× [instance: sessionName]: Unknow error
Not Logged

**Comment by DiegoGuevara86** [comment]
This appears to me ..

Error: Evaluation failed: Error: gadd called without an id attr (id)
    at W.gadd (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:455434)
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:277773
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213
    at j (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:259320)
    at new y (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:251887)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63094
    at W._findAndParse (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:278506)
    at ExecutionContext._evaluateInternal (C:\SISLoja\wpp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\SISLoja\wpp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
C:\SISLoja\wpp-api>pause

**Comment by rannyelly** [comment]
Same problem here... any fix?

**Comment by DiegoGuevara86** [comment]
No meu caso, abri  package.json e mudei a versão do Venom, manualmente  para 4.0.9 e atualizei novamente pelo powershell npm install.

**Comment by DiegoGuevara86** [comment]
![image](https://user-images.githubusercontent.com/101804879/159047348-17d02d09-4b86-4171-8571-2a20fa9e7795.png)

**Comment by ricocrivelli** [comment]
You must update to latest version (4.0.9).

**Comment by rannyelly** [comment]
> You must update to latest version (4.0.9).

I try this and now all be fine!
