### ISSUE TITLE
setGroupImage function executing the wrong function.

### ISSUE THREAD

**Issue by matthewsbrandan** [orkestral/venom#1574]
## Description

I'm using the setGroupImage function to try to change the group image, but it's changing the profile picture of my user logged in to venom.

Here's the link to the documentation I'm following:
https://orkestral.github.io/venom/classes/Whatsapp.html#setGroupImage

## Environment

- **Venom Versions:** ^4.0.9
- **OS:** Windows 10
- **Node version:** 14.17.1

## Steps to play

1. Make the function call.

## Log output

Error when sending: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isBroadcast')
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:6:192119
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213
    at j (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:259320)
    at new y (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:251887)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63094
    at p (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:6:192043)
    at t.getProfilePicFull (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:6:191666)
    at ExecutionContext._evaluateInternal (C:\xampp\htdocs\codewriters\chatinger\venom-http\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks(<anonymous>)
    at processTicksAndRejections(internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\xampp\htdocs\codewriters\chatinger\venom-http\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

## Your code
``` js
async setGroupImage(request, response) {
    const { group_id, image_path } = request.body;

    console.log('::set-group-image')
    console.log('req >>', group_id, image_path);
    this.client?.setGroupImage(group_id, image_path).then((result) => {
      console.log('res >>', result);
      return response.status(201).json(result);
    }).catch((error) => {
      console.error('Error when sending: ', error); // return object error
      return response.json(error);
    });
  }
  ```

**Comment by Infinity8sailor** [comment]
any update on this, I'm having the same issue.
