### ISSUE TITLE
wapi.js error

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [orkestral/venom#1579]
Hi guys i am testing a bot app. with venon when i type the  Hi message it triggers in order to reply the auto-response.. but it throws out this error on venon lib folder wapi.js

info:     [BOT] Page successfully accessed
✓ [instance: BOT]: Connected
Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization
    at Object.window.WAPI.window.WAPI.sendExist (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33189)
    at async Object.window.WAPI.window.WAPI.sendMessage (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:47206)
    at ExecutionContext._evaluateInternal (/opt/template-node-typescript/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (/opt/template-node-typescript/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
[ERROR] 12:14:08 Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization
    at Object.window.WAPI.window.WAPI.sendExist (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33189)
    at async Object.window.WAPI.window.WAPI.sendMessage (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:47206)

**Comment by marianoadangelo** [comment]
I have the same error using nighly build, use version 4.0.9

**Comment by leovigildocr** [comment]
i have the same error.

**Comment by sandro-salles** [comment]
+1

**Comment by mmhospedagem** [comment]
https://github.com/orkestral/venom/issues/1626
