### ISSUE TITLE
How Can i Get The connected Device Phone Number

### ISSUE THREAD

**Issue by h4775346** [orkestral/venom#1584]
```
const venom = require('venom-bot');

async function start(client) {
    const phone = (await client.getHostDevice()).id.user;
    console.log(phone)
}



venom.create(
    //session
    'session_1', //Pass the name of the client you want to start the bot
    //catchQR
    (base64Qrimg, asciiQR, attempts, urlCode) => {
        console.log('Number of attempts to read the qrcode: ', attempts);
        console.log('Terminal qrcode: ', asciiQR);
        // console.log('base64 image string qrcode: ', base64Qrimg);
        // console.log('urlCode (data-ref): ', urlCode);
    },
    // statusFind
    (statusSession, session) => {
        console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
        //Create session wss return "serverClose" case server for close
        console.log('Session name: ', session);
    },
    // options
    {
        folderNameToken: 'tokens', //folder name when saving tokens
        mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
        headless: true, // Headless chrome
        devtools: false, // Open devtools by default
        useChrome: true, // If false will use Chromium instance
        debug: false, // Opens a debug session
        logQR: true, // Logs QR automatically in terminal
        browserWS: '', // If u want to use browserWSEndpoint
        browserArgs: [''], // Parameters to be added into the chrome browser instance
        puppeteerOptions: {}, // Will be passed to puppeteer.launch
        disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
        disableWelcome: true, // Will disable the welcoming message which appears in the beginning
        updatesLog: true, // Logs info updates automatically in terminal
        autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
        createPathFileToken: false, //creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
    },
)
    .then((client) => start(client))
    .catch((error) => console.log(error));
```

Output
```

Session name:  session_1
√ [instance: session_1]: Connected
Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization
    at Object.window.WAPI.window.WAPI.sendExist (D:\test-whats\venom\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33189)
    at async Object.window.WAPI.window.WAPI.getHost (D:\test-whats\venom\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:72570)
    at ExecutionContext._evaluateInternal (D:\test-whats\venom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\test-whats\venom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)



```

**Comment by marciopronin** [comment]
in wapi.js
//change
const o = new Store.WidFactory.createWid(o); 
//to
const o = new Store.WidFactory.createWid(e);
