### ISSUE TITLE
getConnectionState is failing

### ISSUE THREAD

**Issue by gvargas1404** [orkestral/venom#1593]
## Description
The function fails when the integration is disconnected from the cell phone, the function is called and returns an error

## Log Output

(node:18823) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: Store is not defined
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/datacrm/www/gvargas/whatsapp_service_re/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/datacrm/www/gvargas/whatsapp_service_re/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(node:18823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18823) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
User from DataCRM connected!
(node:18823) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: Store is not defined
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/datacrm/www/gvargas/whatsapp_service_re/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/datacrm/www/gvargas/whatsapp_service_re/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(node:18823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

## Your Code
/**
 * @returns venom client
 */
const getClient = async() => {
    return await venom.create("sessionName_"+Math.random().toString(36).slice(-8), sendBase64Qr, getSessionStatus, config).catch((erro) => {
        console.log(erro);
    });
}

clientWhatsapp = await getClient();
var state = await clientWhatsapp.getConnectionState();

If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot
![Captura de pantalla de 2022-03-25 00-33-54](https://user-images.githubusercontent.com/69543668/160060769-3252e72d-a327-4d97-9a24-b9d866ab7240.png)

**Comment by AlexsandroZanella2** [comment]
the same, when multidevice = true.
node 16. W Server 2019
