### ISSUE TITLE
Error: Cannot find module 'rxjs' on venom-bot last update

### ISSUE THREAD

**Issue by OmarMYousef** [orkestral/venom#160]
Hello there, I've just updated venom-bot right now, and i get error while starting the app
i've uninstalled and reinstalled venom-bot and nothing happens

Here's the error i get ( `F:\CovidBot\CovidBot Assistant Src\` is the project directory )
```
Error: Cannot find module 'rxjs'
Require stack:
- F:\CovidBot\CovidBot Assistant Src\node_modules\venom-bot\dist\controllers\auth.js
- F:\CovidBot\CovidBot Assistant Src\node_modules\venom-bot\dist\controllers\initializer.js
- F:\CovidBot\CovidBot Assistant Src\node_modules\venom-bot\dist\index.js
- F:\CovidBot\CovidBot Assistant Src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\CovidBot\CovidBot Assistant Src\node_modules\venom-bot\dist\controllers\auth.js:97:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\CovidBot\\CovidBot Assistant Src\\node_modules\\venom-bot\\dist\\controllers\\auth.js',
    'F:\\CovidBot\\CovidBot Assistant Src\\node_modules\\venom-bot\\dist\\controllers\\initializer.js',
    'F:\\CovidBot\\CovidBot Assistant Src\\node_modules\\venom-bot\\dist\\index.js',
    'F:\\CovidBot\\CovidBot Assistant Src\\index.js'
  ]
}
```

Thanks in advance <3

**Comment by leobevi** [comment]
Hello try to run the command -     npm install --save rxjs

**Comment by OmarMYousef** [comment]
> Hello try to run the command - npm install --save rxjs
Oh It works now, Thanks for help!
