### ISSUE TITLE
Store.sendCreateGroup error: USER_JID: invalid jid type: Not an instance of WID

### ISSUE THREAD

**Issue by mikelustosa** [orkestral/venom#1609]
"Error: USER_JID: invalid jid type: Not an instance of WID
    at t.USER_JID (https://web.whatsapp.com/bootstrap_qr.8c19f3b9920c01c16ec8.js:6:147750)
    at https://web.whatsapp.com/bootstrap_qr.8c19f3b9920c01c16ec8.js:6:222413
    at Array.map (<anonymous>)
    at https://web.whatsapp.com/bootstrap_qr.8c19f3b9920c01c16ec8.js:6:222362
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.a845b257f0f12ac0b80d.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.a845b257f0f12ac0b80d.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.a845b257f0f12ac0b80d.js:2:63213
    at Y (https://web.whatsapp.com/bootstrap_qr.8c19f3b9920c01c16ec8.js:5:261290)
    at new y (https://web.whatsapp.com/bootstrap_qr.8c19f3b9920c01c16ec8.js:5:253857)"

**Comment by idealti-git** [comment]
https://github.com/orkestral/venom/issues/1626
