### ISSUE TITLE
Error calling close() method after startTyping() is called

### ISSUE THREAD

**Issue by effer89** [orkestral/venom#170]
close() method works very well, but if at any given moment I use startTyping then close() it throws this exception:

startTyping dont throw any exceptions when called.

Using "venom-bot": "^2.0.1"

btw, great work guys :D

```(node:21942) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/var/www/whats-bot/node_modules/puppeteer/lib/Connection.js:152:63)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/www/whats-bot/node_modules/puppeteer/lib/Connection.js:151:16)
    at ExecutionContext._evaluateInternal (/var/www/whats-bot/node_modules/puppeteer/lib/ExecutionContext.js:85:50)
    at ExecutionContext.evaluate (/var/www/whats-bot/node_modules/puppeteer/lib/ExecutionContext.js:33:27)
    at ExecutionContext.<anonymous> (/var/www/whats-bot/node_modules/puppeteer/lib/helper.js:95:27)
    at DOMWorld.evaluate (/var/www/whats-bot/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/whats-bot/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/var/www/whats-bot/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/var/www/whats-bot/node_modules/puppeteer/lib/helper.js:95:27)
    at Whatsapp.<anonymous> (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:619:49)
    at step (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.startTyping (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:617:16)
  -- ASYNC --
    at Page.<anonymous> (/var/www/whats-bot/node_modules/puppeteer/lib/helper.js:94:19)
    at Whatsapp.<anonymous> (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:619:49)
    at step (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.startTyping (/var/www/whats-bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:617:16)
    at WhatsAppBot.sendMessage (/var/www/whats-bot/src/app.js:140:12)
    at WhatsAppBot.process (/var/www/whats-bot/src/app.js:459:24)
(node:21942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)```

**Comment by joaosouz4** [comment]
you can create the PR if you feel comfortable

**Comment by effer89** [comment]
> you can create the PR if you feel comfortable

Thanks, I'll try get a hold of this code, in this weekend I'll try solve this!
