### ISSUE TITLE
Erro ao trocar imagem do grupo com setGroupImage

### ISSUE THREAD

**Issue by Gml10** [orkestral/venom#1708]
## Description

Recebo um erro ao utilizar a função setGroupImage.
Nessa função eu passei dois parâmetros, o id do grupo e o caminho da imagem.
Código:
`var resultImageGroup = await client.setGroupImage('120363042669932073@g.us', 'E:\\Projetos\\VenomZapBot\\temp\\4ab5f21913c147c494812212a3b1a155o.png'
).catch((err) => {
   sRetorno = ({ result: "error", success: false, code: 'setGroupImageError' });
});`

O interessante é que ele troca MINHA foto de perfil e em seguida recebo o seguinte erro no console:

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isBroadcast')
    at https://web.whatsapp.com/bootstrap_qr.a93ca7c63be0f2cdef56.js:32:237545
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.27ae36d14a5e15ff6df9.js:2:65356)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.27ae36d14a5e15ff6df9.js:2:65567)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.27ae36d14a5e15ff6df9.js:2:65626
    at Y (https://web.whatsapp.com/bootstrap_qr.a93ca7c63be0f2cdef56.js:31:99298)
    at new y (https://web.whatsapp.com/bootstrap_qr.a93ca7c63be0f2cdef56.js:31:91865)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.27ae36d14a5e15ff6df9.js:2:65507
    at t.getProfilePic (https://web.whatsapp.com/bootstrap_qr.a93ca7c63be0f2cdef56.js:32:237204)
    at https://web.whatsapp.com/bootstrap_qr.a93ca7c63be0f2cdef56.js:50:113492
    at ExecutionContext._evaluateInternal (E:\Visual Studio - Projetos\VenomZapBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (E:\Visual Studio - Projetos\VenomZapBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Whatsapp.setGroupImage (E:\Visual Studio - Projetos\VenomZapBot\node_modules\venom-bot\dist\api\layers\group.layer.js:35:24)
    at async Function.setGroupImage (E:\Visual Studio - Projetos\VenomZapBot\venom\groups.js:356:52)
    at async E:\Visual Studio - Projetos\VenomZapBot\routes\groups.js:33:18

## Environment

- **Venom version(s):**  4.1.0

 const chromiumArgs = [
                '--disable-web-security', '--no-sandbox', '--disable-web-security',
                '--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
                '--disable-offline-load-stale-cache', '--disk-cache-size=0',
                '--disable-background-networking', '--disable-default-apps', '--disable-extensions',
                '--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
                '--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
                '--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list',
                '--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'
              ];

**Comment by jsuceir** [comment]
conseguiu resolver ?

**Comment by Gml10** [comment]
> conseguiu resolver ?

ainda não

**Comment by orkestral** [comment]
#1719

**Comment by ArmandoTL** [comment]
Conseguiu resolver? Não consigo nem pegar o id dos grupos.

> > conseguiu resolver ?
> 
> ainda não
