### ISSUE TITLE
createGroup doesn't work

### ISSUE THREAD

**Issue by ClaraProgramadora** [orkestral/venom#1737]
## Description

When I run client. createGroup, it returns an error. Thanks you. 

## Environment

- **Venom version(s):** 4.2.0
- **Browser:** Chromium versión 88.0.4298.0
- **OS:** macOS Monterey V12.2.1
- **Node version:**  v14.17.4

## Steps to Reproduce

I execute: await client.createGroup()
The error appears

## Log Output

(node:3113) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'createWid' of undefined
    at Object.window.WAPI.window.WAPI.sendExist (/Users/claradiazruiz/Documents/beca/WhatsAppBot/backend/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33202)
    at async Promise.all (index 0)
    at async Object.window.WAPI.window.WAPI.createGroup (/Users/claradiazruiz/Documents/beca/WhatsAppBot/backend/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:39875)
    at ExecutionContext._evaluateInternal (/Users/claradiazruiz/Documents/beca/WhatsAppBot/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/Users/claradiazruiz/Documents/beca/WhatsAppBot/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Whatsapp.createGroup (/Users/claradiazruiz/Documents/beca/WhatsAppBot/backend/node_modules/venom-bot/dist/api/layers/group.layer.js:256:16)
    at async newPrincipalGroup (/Users/claradiazruiz/Documents/beca/WhatsAppBot/backend/dist/Cobato.js:267:23)
If relevant, paste all of your Log Output
```

## Your Code

const infoGroup = await client.createGroup(groupName, [
      venomPhone+'@c.us',
      phone+'@c.us',
    ]);

**Comment by dofer** [comment]
Hi,
is this issue solver? Any of you can confirm if the new "pro" version of Venom, Superchat,  fixed the problem when creating groups?
