### ISSUE TITLE
Problem getAllChatsGroups

### ISSUE THREAD

**Issue by ArmandoTL** [orkestral/venom#1769]
async function start() {
    const contacts = await client.getAllChatsGroups();
    myConsole.log(contacts);
}
start();

output log:
```
C:\Users\User\Desktop\app\scrap\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: ReferenceError: groupId is not defined
    at pptr://__puppeteer_evaluation_script__:3:13
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\User\Desktop\app\scrap\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\User\Desktop\app\scrap\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async Whatsapp.getAllChatsGroups (C:\Users\User\Desktop\app\scrap\node_modules\venom-bot\dist\api\layers\group.layer.js:180:16)
    at async start (C:\Users\User\Desktop\app\scrap\scrap.js:21:26)

**Comment by ArmandoTL** [comment]
which day? have outhers users with problem very days.

**Comment by ArmandoTL** [comment]
Problem continue.

**Comment by ArmandoTL** [comment]
> This issue is stale because it has been open for 30 days with no activity.

No stable, problem continue.
