### ISSUE TITLE
Function getBatteryLevel();

### ISSUE THREAD

**Issue by mazzarello** [orkestral/venom#18]
Hello,

**As i did**
async function f1() {
    var bateria = await client.getBatteryLevel();
    console.log(bateria);
    res.send(bateria);
}

f1();

**The error generated was**

(node:11664) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: output is not defined
    at Object.window.WAPI.getBatteryLevel (C:\venom\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:43845)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (C:\venom\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\venom\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\venom\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (C:\venom\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\venom\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (C:\venom\node_modules\puppeteer\lib\Page.js:612:14)
    at Page.<anonymous> (C:\venom\node_modules\puppeteer\lib\helper.js:95:27)
    at Whatsapp.<anonymous> (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:107:60)
    at step (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:33:23)
    at Object.next (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:14:53)
    at C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:4:12)
    at Whatsapp.HostLayer.getBatteryLevel (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:104:16)
  -- ASYNC --
    at Page.<anonymous> (C:\venom\node_modules\puppeteer\lib\helper.js:94:19)
    at Whatsapp.<anonymous> (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:107:60)
    at step (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:33:23)
    at Object.next (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:14:53)
    at C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:4:12)
    at Whatsapp.HostLayer.getBatteryLevel (C:\venom\node_modules\venom-bot\dist\api\layers\host.layer.js:104:16)
    at f1 (C:\venom\sucesso.js:35:28)
    at C:\venom\sucesso.js:40:1
(node:11664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks!

**Comment by orkestral** [comment]
we are still fixing this function as soon as we fix it, we created a new version, thanks!
