### ISSUE TITLE
Erro ao enviar mensagem para grupo

### ISSUE THREAD

**Issue by jorgeed** [orkestral/venom#1829]
Estou tentando enviar uma mensagem no grupo conforme o padrão de ID, porem me retorna o erro abaixo:

Error: Evaluation failed: Error: wid error: invalid wid: 5562982813630-BB1Dm5rK27hDWWeuaOHgrR@g.us
    at new u (https://web.whatsapp.com/bootstrap_qr.66849cef15ad135f447d.js:71:26577)
    at new s (https://web.whatsapp.com/bootstrap_qr.66849cef15ad135f447d.js:71:31141)
    at window.WAPI.window.WAPI.sendExist (C:\Users\jorge.junior\Documents\Projetos\Produtividade\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33181)
    at async window.WAPI.window.WAPI.sendMessage (C:\Users\jorge.junior\Documents\Projetos\Produtividade\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:47150)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\jorge.junior\Documents\Projetos\Produtividade\node_modules\puppeteer\src\common\ExecutionContext.ts:279:13)        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\jorge.junior\Documents\Projetos\Produtividade\node_modules\puppeteer\src\common\ExecutionContext.ts:145:12)
    at async C:\Users\jorge.junior\Documents\Projetos\Produtividade\node_modules\venom-bot\src\api\layers\sender.layer.ts:145:22

**Comment by orkestral** [comment]
#[113ea95](https://github.com/orkestral/venom/commit/113ea9521a560621fc5207a7386223554dab8242)
