### ISSUE TITLE
Cannot login session

### ISSUE THREAD

**Issue by ocracy** [orkestral/venom#185]
(node:1996) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at eval (eval at waitForPredicatePageFunction (:2:21), <anonymous>:5:29)
    at eval (eval at waitForPredicatePageFunction (:2:21), <anonymous>:6:27)
    at onRaf (__puppeteer_evaluation_script__:56:33)
    at pollRaf (__puppeteer_evaluation_script__:48:5)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:18)
    at ExecutionContext._evaluateInternal (/var/www/astro/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WaitTask.rerun (/var/www/astro/node_modules/puppeteer/lib/DOMWorld.js:570:17)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/var/www/astro/node_modules/puppeteer/lib/helper.js:111:15)
    at WaitTask.rerun (/var/www/astro/node_modules/puppeteer/lib/DOMWorld.js:570:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by leobevi** [comment]
update your package...........
npm update venom-bot
