### ISSUE TITLE
Error: Evaluation failed: Error: gadd called without an id attr (id)

### ISSUE THREAD

**Issue by FerryAr** [orkestral/venom#1858]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** v4.2.7
- **Browser:** Chromium 103
- **OS:** Debian Bullseye x64 on docker
- **Node version:** Node v18.7.0

## Steps to Reproduce
I am using venom-bot as service on NestJS, after scanning qr, that exception appeared.

## Log Output

```
Error: Evaluation failed: Error: gadd called without an id attr (id)
    at H.gadd (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:566799)
    at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:373843
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
    at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
    at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
    at H._findAndParse (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:374910)
    at ExecutionContext._evaluateInternal (/root/NODE_PROJECT/whatsapp-api-venom/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/root/NODE_PROJECT/whatsapp-api-venom/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
```

## Your Code

```
await create(
        sessionName,
        (base64Qr, asciiQR) => {
          //save qr to file
          const base64Data = base64Qr.replace(/^data:image\/png;base64,/, '');
          fs.writeFile(
            './qr/' + sessionName + '.png',
            base64Data,
            'base64',
            function (err) {
              // console.log("GAGAL LEK, reason" + err);
            },
          );
        },
        (statusFind, session) => {
          console.log(statusFind);
          console.log(session);
        },
        {
          headless: true,
          devtools: false,
          useChrome: true,
          debug: false,
          logQR: false,
          multidevice: false,
          browserArgs: [
            '--log-level=3',
            '--no-default-browser-check',
            '--disable-site-isolation-trials',
            '--no-experiments',
            '--ignore-gpu-blacklist',
            '--ignore-certificate-errors',
            '--ignore-certificate-errors-spki-list',
            '--disable-gpu',
            '--disable-extensions',
            '--disable-default-apps',
            '--enable-features=NetworkService',
            '--disable-setuid-sandbox',
            '--no-sandbox',
            '--disable-webgl',
            '--disable-threaded-animation',
            '--disable-threaded-scrolling',
            '--disable-in-process-stack-traces',
            '--disable-histogram-customizer',
            '--disable-gl-extensions',
            '--disable-composited-antialiasing',
            '--disable-canvas-aa',
            '--disable-3d-apis',
            '--disable-accelerated-2d-canvas',
            '--disable-accelerated-jpeg-decoding',
            '--disable-accelerated-mjpeg-decode',
            '--disable-app-list-dismiss-on-blur',
            '--disable-accelerated-video-decode',
            '--single-process', // <- this one doesn't works in Windows
          ],
          autoClose: 60000,
          createPathFileToken: true,
          puppeteerOptions: {},
        },
      )
        .then(async (client) => {
          this.saveToken(client, sessionName);
          this.listClient.push({ session: sessionName, client: client });
          const device = await client.getHostDevice();
          const id: any = device.id;
          const user = req.user;
          const isNomorExist = await this.deviceService.findByNomor(id.user);
          const isSessionExist = await this.deviceService.findBySessionName(
            sessionName,
          );

          if (isNomorExist) {
            //do nothing
          } else {
            if (isSessionExist) {
              await this.deviceService.updateNomor(sessionName, id.user);
            } else {
              await this.deviceService.create({
                aliasName: null,
                nomor: id.user,
                user_id: user.user_id,
                session_name: sessionName,
                is_active: true,
              });
            }
          }
          this.getContact(client, req);
          this.autoReplyMachine(client, res);
          res.status(HttpStatus.OK).json({
            message: 'Connected',
            session: sessionName,
          });
        })
        .catch((err) => {
          res.status(HttpStatus.BAD_REQUEST).json({
            message: 'QR Code expired, silahkan coba lagi',
            session: sessionName,
          });
          this.deleteFile(sessionName);
          console.log(err);
        });
    }
  }
```

**Comment by orkestral** [comment]
(https://github.com/orkestral/venom/commit/3ede6221895dac5a6a88ba64c9288154e5e297a2)
