### ISSUE TITLE
without save number in mobile message not deliver

### ISSUE THREAD

**Issue by Akash-Rathore** [orkestral/venom#1859]
C:\Users\akash\OneDrive\Desktop\adhiraj\akash\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: r._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568548
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
    at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
    at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
    at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568914)
    at H._query (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568040)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\akash\OneDrive\Desktop\adhiraj\akash\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\akash\OneDrive\Desktop\adhiraj\akash\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async C:\Users\akash\OneDrive\Desktop\adhiraj\akash\node_modules\venom-bot\dist\api\layers\sender.layer.js:235:28

**Comment by orkestral** [comment]
#3ede6221895dac5a6a88ba64c9288154e5e297a2

**Comment by orkestral** [comment]
#[f267cae](https://github.com/orkestral/venom/commit/f267cae1bf29ed9c38c2f1060907068dd1bf41f5)

**Comment by michaelmartins94** [comment]
The error persists...

/Users/$$/venom_api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: r._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568548
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
    at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
    at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
    at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568914)
    at H._query (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568040)
    at ExecutionContext._ExecutionContext_evaluate (/Users/$$/venom_api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/$$/venom_api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
    at async /Users/$$/venom_api/node_modules/venom-bot/dist/api/layers/sender.layer.js:120:28
[nodemon] app crashed - waiting for file changes before starting...

**Comment by michaelmartins94** [comment]
The error The error persists...

The error happens when starting a new conversation by sending message.

/Users/michaelmartins/venom_api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: r._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568548
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
    at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
    at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
    at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568914)
    at H._query (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568040)
    at ExecutionContext._ExecutionContext_evaluate (/Users/michaelmartins/venom_api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/michaelmartins/venom_api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
    at async /Users/michaelmartins/venom_api/node_modules/venom-bot/dist/api/layers/sender.layer.js:120:28
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jhaineymilevis** [comment]
hi @michaelmartins94 have you found any solution?
