### ISSUE TITLE
without save number in mobile message not deliver

### ISSUE THREAD

**Issue by Nemo1710** [orkestral/venom#1862]
## Description

If the number is not saved as contact, it's no feasible to send message

- **Venom version(s):** [4.2.9]
- **Browser:** [Chrome ]
- **OS:** [Windows 11]
- **Node version:** [6.14.15]

## Steps to Reproduce
client.sendText(envio, arr[0])
## Log Output

(node:22144) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: r._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568548
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
    at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
    at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
    at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568914)
    at H._query (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568040)
    at ExecutionContext._evaluateInternal (C:\Users\Carlos Luis\OneDrive\CarlosVenegas\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Users\Carlos Luis\OneDrive\CarlosVenegas\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async C:\Users\Carlos Luis\OneDrive\CarlosVenegas\bot\node_modules\venom-bot\src\api\layers\sender.layer.ts:641:22

**Comment by orkestral** [comment]
Solved [e8ba1ec](https://github.com/orkestral/venom/commit/e8ba1ec56573dd3bf4e3c5d8fa90436861af6468)
