### ISSUE TITLE
Venom not working on server

### ISSUE THREAD

**Issue by luizfeer** [orkestral/venom#187]
i tread on ubuntu 18, in azure vps.
```
Chrome not found, using chromium
TypeError: Cannot read property 'onMessage' of undefined
    at start (/home/luiz/zap/src/index.js:15:10)
    at bot.create.then (/home/luiz/zap/src/index.js:10:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Checking for updates
⠋ Waiting...
```

**Comment by nicoaudy** [comment]
yes im here too, in debian vps

**Comment by gustavosoave** [comment]
The simple example will not work for this case, you will need to use somethink like this:

```
venom
  .create(
    'sessionName',
    (base64Qrimg, asciiQR) => {
      console.log('Terminal qrcode: ', asciiQR);
      console.log('base64 image string qrcode: ', base64Qrimg);
    },
    (statusSession) => {
      console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled
    },
    {
      folderNameToken: 'tokens', //folder name when saving tokens
      mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
      headless: true, // Headless chrome
      devtools: false, // Open devtools by default
      useChrome: true, // If false will use Chromium instance
      debug: false, // Opens a debug session
      logQR: true, // Logs QR automatically in terminal
      browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'], // Parameters to be added into the chrome browser instance
      disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
      disableWelcome: true, // Will disable the welcoming message which appears in the beginning
      updates: true, // Logs info updates automatically in terminal
      autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
    }
  )
  .then((client) => {
    start(client);
  })
  .catch((erro) => {
    console.log(erro);
  });
```

**Comment by luizfeer** [comment]
pupeeteer need dependencies in azure/aws machines.
![image](https://user-images.githubusercontent.com/3594167/94439349-b044ce00-0176-11eb-924d-bd56a7954033.png)

I use `sudo apt-get install -f`
from fix apt, and
`
sudo apt-get update
sudo apt-get install libnss3-dev
`
from install chrome dependencies.
more: https://medium.com/mockingbot/run-puppeteer-chrome-headless-on-ec2-amazon-linux-ami-6c9c6a17bee6
and: https://dev.to/chis0m/installing-puppeteer-on-an-ubuntu-aws-ec2-instance-5o7
