### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isWidlike') at window.WAPI.window.WAPI.sendCheckType

### ISSUE THREAD

**Issue by renandecarlo** [orkestral/venom#1876]
## Description

This error is thrown (randomly) after sending multiple messages to the same number, with a small time between msgs (eg. 1 minute)

## Environment

- **Venom version(s):** 4.3.0
- **Browser:** Chrome 
- **OS:** Windows 10
- **Node version:** Node 16

## Steps to Reproduce

Happens randomly, could not reproduce

## Log Output

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')
    at window.WAPI.window.WAPI.sendCheckType (C:\snapshot\geraldin-bot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:31862)
    at window.WAPI.window.WAPI.sendExist (C:\snapshot\geraldin-bot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33133)    at window.WAPI.window.WAPI.sendMessage (C:\snapshot\geraldin-bot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:47248)
    at pptr://_puppeteer_evaluation_script_:2:29
    at ExecutionContext._ExecutionContext_evaluate (C:\snapshot\geraldin-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:271:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\snapshot\geraldin-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:118:16)
    at async C:\snapshot\geraldin-bot\node_modules\venom-bot\dist\api\layers\sender.layer.js:120:28
```

## Your Code

```
try {
  let result = await client.sendText(`55${wppNumber}@c.us`, data.message);

  /* Check if message has been sent. Send to next number otherwise */
  if(!result.erro) {
    console.log(chalk.greenBright.inverse('-> Enviado!'), [ result.status, wppNumber ] )
  }
} catch (error) {
  console.log(chalk.redBright('-> Mensagem não enviada. Tentando próximo número'), [ error.status, wppNumber, error.text ] );
}
```

**Comment by jsuceir** [comment]
up

**Comment by TheSamhain** [comment]
up

**Comment by AdrielSantoss** [comment]
up

**Comment by renandecarlo** [comment]
up

**Comment by rodrigooliver** [comment]
up

**Comment by geek3000** [comment]
up
