### ISSUE TITLE
Checking phone is connected... Page Closed after a few minutes

### ISSUE THREAD

**Issue by fabiopalm** [orkestral/venom#1882]
![image](https://user-images.githubusercontent.com/378061/186309243-9c3cfadc-0401-4360-adec-bdc2c26bda22.png)

## Description

It works the first time we sync the QRcode.
Then when using the script again, it stops at this message.
There was no change in code, it was working in the last few days.
After a few minutes, puppeteer closes.

## Environment

- **Venom version(s): 4.3.0
- **OS: Debian
- **Node version: 18.7.0

## Steps to Reproduce

1. Sync QRcode (first time)
2. run the venom bot correctly
3. close the script
4. try to run the same code again

## Log Output

```
/home/bitnami/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:268
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /home/bitnami/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:268:24
    at new Promise (<anonymous>)
    at CDPSession.send (/home/bitnami/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:264:16)
    at ExecutionContext._ExecutionContext_evaluate (/home/bitnami/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:268:46)
    at ExecutionContext.evaluateHandle (/home/bitnami/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:162:107)
    at WaitTask.rerun (/home/bitnami/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:708:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  originalMessage: ''
}
```

## Your Code

```
venom
    .create({
        session: 'manoel-agora-vr', //name of session wa-agora-session
        multidevice: true // for version not multidevice use false.(default: true)
    })
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
    });
```

**Comment by allburov** [comment]
>This issue is stale because it has been open for 30 days with no activity.

But

>[fabiopalm](https://github.com/fabiopalm) opened this issue 11 days ago

Something wrong with the bot.
