### ISSUE TITLE
Sending Lists doesn't work / causes crash

### ISSUE THREAD

**Issue by omarmyousef** [orkestral/venom#1973]
## Description

Whenever i try to send lists with message the software throws an error

## Environment

- **Venom version(s):** 4.3.3 (@latest)
- **Browser:** Included browser
- **OS:** Windows 10
- **Node version:** Node v18.0.0

## Steps to Reproduce

using the example in Readme.md would throw the error

## Log Output

```
...\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: Error: Sections must be an array
    at t.sendListMessage (<anonymous>:2:154348)
    at pptr://__puppeteer_evaluation_script__:8:33
    at ExecutionContext._ExecutionContext_evaluate (...\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (...\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async ...\project\node_modules\venom-bot\dist\api\layers\sender.layer.js:116:28
```

```js
const list = [{
        title: "Pasta",
        rows: [{
            title: "Ravioli Lasagna",
            description: "Made with layers of frozen cheese",
        }]
    },
    {
        title: "Dessert",
        rows: [{
                title: "Baked Ricotta Cake",
                description: "Sweets pecan baklava rolls",
            },
            {
                title: "Lemon Meringue Pie",
                description: "Pastry filled with lemonand meringue.",
            }
        ]
    }
];

await this.client.sendListMenu('20124865245@c.us', 'Title', 'subTitle', 'Description', 'menu', list)
    .then((result) => {
        console.log('Result: ', result); //return object success
    })
    .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
    });
```

## Additional context / Screenshot

none

**Comment by orkestral** [comment]
verify new documentation in [Venom Documentation](https://docs.orkestral.io/venom)
