### ISSUE TITLE
Error when trying to logout

### ISSUE THREAD

**Issue by omarmyousef** [orkestral/venom#1989]
## Description

Venom throws an error while calling client.logout();

## Environment

- **Venom version(s):** 4.3.3
- **Browser:** Chromium
- **OS:** Windows 10
- **Node version:** Node v18.0.0

## Steps to Reproduce

Create a client, login, then call client.logout();

## Log Output

```
...\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));              ^

Error: Evaluation failed: TypeError: window.Store.Login.triggerCriticalSyncLogout is not a function
    at window.WAPI.window.WAPI.logout (<anonymous>:1:76909)
    at pptr://__puppeteer_evaluation_script__:1:13
    at ExecutionContext._ExecutionContext_evaluate (...\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (...\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async Whatsapp.logout (...\project\node_modules\venom-bot\dist\api\whatsapp.js:59:16)
```

## Your Code

```js
/// create client
this.client = await venom.create({
    "session": "session-main",
    "multidevice": true,
    "mkdirFolderToken": path.join(this.app.dir.data, "whatsapp"),
    "headless": this.app.config.HEADLESS_BROWSER,
    "logQR": false,
    "puppeteerOptions": {
        args: ["--no-sandbox"]
    },
    "disableWelcome": true,
});
/// logout
this.client.logout();
```

## Additional context / Screenshot

none

**Comment by omarmyousef** [comment]
> I'm having the same error, you got any solution?

unfortunately no, the only way i found so far is to delete your session folder
which is have to be done manually

**Comment by orkestral** [comment]
resolve with version 4.3.4 [afea4e4](https://github.com/orkestral/venom/commit/afea4e4fc3d9f065eb3e2e7ad93837a74ddc1924)

**Comment by Pedro-Coimbra** [comment]
I keep getting the same error even after the update
