### ISSUE TITLE
Erro ao setar imagem do perfil do grupo

### ISSUE THREAD

**Issue by Moisa** [orkestral/venom#1995]
## Description

Alguem já passou por isso, Ao tentar senviar uma imgem para o perfil do grupo ocorre o seguinte erro:

 Error: Evaluation failed: TypeError: (t || "").trim is not a function
    at e (c:\venom\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:295565)
    at e.exports (c:\venom\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:81927)
    at t.convertToFile (c:\venom\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:232067)
    at t.setIcon (c:\venom\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:202249)

    at ExecutionContext._ExecutionContext_evaluate (c:\venom\node_modules\puppeteer\src\common\ExecutionContext.ts:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (c:\venom\node_modules\puppeteer\src\common\ExecutionContext.ts:145:12)
    at async Whatsapp.setGroupImage (c:\venom\node_modules\venom-bot\src\api\layers\group.layer.ts:104:16)

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 4.3.3]
- **Browser:** [e.g. 107.0.5304.1075]
- **OS:** [e.g.  Windows 10]
- **Node version:** [e.g. v16.15.1]

**Comment by orkestral** [comment]
resolve with version 4.3.4 [afea4e4](https://github.com/orkestral/venom/commit/afea4e4fc3d9f065eb3e2e7ad93837a74ddc1924)
