### ISSUE TITLE
Error while using nexe and nssm for windows service

### ISSUE THREAD

**Issue by AndisKush** [orkestral/venom#2007]
I am using nexe to create a .exe file and run as service with nssm.
When the service is created the aplication run with no errors, but when i restart the computer the service starts, but when I tried to use sendtext I receive this error:

Unable to load the sleep module (no animations available)
- [instance: webapi]: Waiting page load
- [instance: webapi]: Checking is logged...
- [instance: webapi]: Authenticated
- [instance: webapi]: Checking phone is connected...
- [instance: webapi]: Connected
(node:5132) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')
    at window.WAPI.window.WAPI.sendCheckType (D:\LinkAPI\deployTest\API\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:32027)
    at window.WAPI.window.WAPI.sendExist (D:\LinkAPI\deployTest\API\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33590)
    at window.WAPI.window.WAPI.sendMessage (D:\LinkAPI\deployTest\API\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:46146)
    at pptr://__puppeteer_evaluation_script__:2:29
    at ExecutionContext._ExecutionContext_evaluate (D:\LinkAPI\deployTest\API\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\LinkAPI\deployTest\API\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async D:\LinkAPI\deployTest\API\node_modules\venom-bot\dist\api\layers\sender.layer.js:120:28
(Use `linkapiback --trace-warnings ...` to show where the warning was created)
(node:5132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

If I restart the service the aplication starts to work again, i dont do anything just restart the service, anyone know what could be? I wanna that the aplication starts with windows as a service with no prompt screen, its work just fine until I restart the computer

**Comment by AndisKush** [comment]
some help?
