### ISSUE TITLE
Error sendListMenu

### ISSUE THREAD

**Issue by wagnerdavanco** [orkestral/venom#2016]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [4.3.3, 4.3.4]
- **Browser:** [e.g. Chrome]
- **OS:** [Windows 10]
- **Node version:** [v16.18.1]

## Steps to Reproduce

1. [First Step]
3. [Second Step]
4. [and so on...]

## Log Output

```
Error: Evaluation failed: Error: Sections must be an array
    at t.sendListMessage (C:\repos\ondetah.bot\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:155752)
    at window.WAPI.window.WAPI.sendListMenu (C:\repos\ondetah.bot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:44264)
    at ExecutionContext._ExecutionContext_evaluate (C:\repos\ondetah.bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\repos\ondetah.bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async C:\repos\ondetah.bot\node_modules\venom-bot\dist\api\layers\sender.layer.js:80:28
PS C:\repos\ondetah.bot> ^C
PS C:\repos\ondetah.bot> ^C
PS C:\repos\ondetah.bot> node .\index.js
Unable to load the sleep module (no animations available)
```

## Your Code

```
  await client
    .sendListMenu(fone, 'Title', 'subTitle', 'Description', 'menu', list)
    .then((result) => {
      console.log('Result: ', result); //return object success
    })
    .catch((erro) => {
      console.error('Error when sending: ', erro); //return object error
    });
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by orkestral** [comment]
use documentation correct : https://docs.orkestral.io/venom
