### ISSUE TITLE
Send mp3 files into audio

### ISSUE THREAD

**Issue by Correa2K** [orkestral/venom#202]
**### ENGLISH**
I was using whatsapp-web.js to send audios, and i wanted to change for venom-bot.js and I searched very much and doesn't saw anything to send a mp3 downloaded file into audio.

in whatsapp-web.js i was using `MessageMedia.fromFilePath()`, did have something like this in venom?

e.g of the code that i was using on whatsapp-web.js
```
if (downloadedMusics.includes(`${videoId}.mp3`)){
media =  MessageMedia.fromFilePath(path.resolve(__dirname, 'downloads', `${videoId}.mp3`));
return client.reply(media); 
```

----------------------------------------------------
**### PORTUGUESE**
Eu tava usando o whatsapp-web.js para enviar áudios e queria mudar para venom-bot.js pq vi q o venom tinha essa função tbm, mas procurei em tudo e não achei nada relacionado a enviar media em áudio.

no whatsapp-web.js eu tava usando `MessageMedia.fromFilePath ()`, tem algo assim no venom?

segue o código que eu estava usando no whatsapp-web.js como exemplo
```
if (downloadedMusics.includes(`${videoId}.mp3`)){
media =  MessageMedia.fromFilePath(path.resolve(__dirname, 'downloads', `${videoId}.mp3`));
return client.reply(media); 
```

**Comment by leobevi** [comment]
@Correa2K, eu envio como base64 e tem funcionado sem problemas
retornoenvio =  await client.sendFileFromBase64(numeroenvio+'@c.us', arquivoBase64, filename, caption);

Na documentação existe para envio através de um path, nunca testei mas deve funcionar tbm.

`
// Send file (venom will take care of mime types, just need the path)
// you can also upload an image using a valid HTTP protocol
await client
  .sendFile(
    '000000000000@c.us',
    'path/to/file.pdf',
    'file_name',
    'See my file in pdf'
  )
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });


`

**Comment by Correa2K** [comment]
Toda vez que tento usar essa forma de envio ele da esse erro.
```
(node:11180) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'length' of undefined
    at https://web.whatsapp.com/app.0b52fdd0773f7751f5d9.js:1:1222729
    at K (https://web.whatsapp.com/app.0b52fdd0773f7751f5d9.js:1:1235680)
    at new p (https://web.whatsapp.com/app.0b52fdd0773f7751f5d9.js:1:1222214)
    at Function.m [as all] (https://web.whatsapp.com/app.0b52fdd0773f7751f5d9.js:1:1222700)
    at Object.window.WAPI.sendMessage (<anonymous>:8:37789)
    at ExecutionContext._evaluateInternal (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\Page.js:612:14)
    at Page.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\helper.js:95:27)
    at Whatsapp.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:108:72)
    at step (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:46:23)
    at Object.next (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:27:53)
    at D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:17:12)
    at D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:104:87
  -- ASYNC --
    at Page.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\puppeteer\lib\helper.js:94:19)
    at Whatsapp.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:108:72)
    at step (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:46:23)
    at Object.next (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:27:53)
    at D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:17:12)
    at D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:104:87
    at new Promise (<anonymous>)
    at Whatsapp.<anonymous> (D:\dev yandereee\tentativa de bot novo\node_modules\venom-bot\dist\api\layers\sender.layer.js:104:39)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Ele consegue baixar, converter mas não envia de nenhum jeito.
A minha linha de envio é:
```
if (downloadedMusics.includes(`${videoId}.mp3`)){
      return gclient.sendFile(message.from, `./downloads/${videoId}.mp3`,`${videoId}`)
```
