### ISSUE TITLE
client.getAllChatsGroups() error

### ISSUE THREAD

**Issue by AndersonVale** [orkestral/venom#2034]
## Description

**Error: Evaluation failed: ReferenceError: groupId is not defined
    at pptr://__puppeteer_evaluation_script__:3:13
    at ExecutionContext._ExecutionContext_evaluate (/home/andersonvale/Documentos/node_projetos/pmmcZap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Whatsapp.getAllChatsGroups (/node_modules/venom-bot/dist/api/layers/group.layer.js:181:16)**

## Environment

- **Venom version(s):** 4.3.6
- **OS:** Ubuntu 22.04
- **Node version:** v19.1.0

**Comment by orkestral** [comment]
use getAllGroups
