### ISSUE TITLE
error in new version

### ISSUE THREAD

**Issue by jsuceir** [orkestral/venom#2051]
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import axios from './lib/axios.js';
                                                                                                                                                                  ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
    at Module._compile (internal/modules/cjs/loader.js:712:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\jusce\AppData\Local\Programs\bot-wa\resources\app.asar\node_modules\venom-bot\dist\api\helpers\download-file.js:58:17)

**Comment by orkestral** [comment]
no errors found, do not open issue again
