### ISSUE TITLE
Inicialize Error

### ISSUE THREAD

**Issue by guh0rzd** [orkestral/venom#2075]
## Description

Ao ligar o bot, 2 erros ocorrem, as vezes um, as vezes outro

## Environment

- **Venom version(s): "^4.3.7"

## Steps to Reproduce

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid')
    at window.WAPI.window.WAPI.startTyping (<anonymous>:1:55472)
    at pptr://__puppeteer_evaluation_script__:1:19
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Gustavo\Desktop\bot wpp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:1

----------------------------------------------------------------//---------------------------------------------------------------------------------
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')
    at window.WAPI.window.WAPI.sendCheckType (C:\Users\Gustavo\Desktop\dalle-2\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:32019)
    at window.WAPI.window.WAPI.sendExist (C:\Users\Gustavo\Desktop\dalle-2\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33582)
    at window.WAPI.window.WAPI.sendMessage (C:\Users\Gustavo\Desktop\dalle-2\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:46138)
    at pptr://__puppeteer_evaluation_script__:2:29
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Gustavo\Desktop\dalle-2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:1

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/89607635/207137000-3209a67b-7f77-4c9d-8e7c-3338510203f2.png)

**Comment by nezzzumi** [comment]
Same here.

**Comment by guh0rzd** [comment]
> this is happening to me too

eu apaguei as pastas "package-lock.json" e "package.json", depois reinstalei o venom-bot, voltou a funcionar!

**Comment by guh0rzd** [comment]
> Same here.

eu apaguei as pastas "package-lock.json" e "package.json", depois reinstalei o venom-bot, voltou a funcionar!
