### ISSUE TITLE
getNumberProfile - TypeError: e.isLid is not a function

### ISSUE THREAD

**Issue by murilobesse** [orkestral/venom#2091]
## Description

I've been using function getNumberProfile for a while and suddenly it stops working.

## Environment

- **Venom version(s):** 4.3.7
- **Browser:** Chromium
- **OS:** Windows 10, Ubuntu 20.04
- **Node version:** Node 18, Node 16

## Log Output

```
Error: Evaluation failed: TypeError: e.isLid is not a function
    at https://web.whatsapp.com/app.cbe2fde94befbde07514.js:46:340054
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66694)
    at https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66753
    at Y (https://web.whatsapp.com/app.cbe2fde94befbde07514.js:40:102829)
    at new y (https://web.whatsapp.com/app.cbe2fde94befbde07514.js:40:95396)
    at https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66634
    at t.getAbout (https://web.whatsapp.com/app.cbe2fde94befbde07514.js:46:339802)
    at t.getStatus (https://web.whatsapp.com/app.cbe2fde94befbde07514.js:50:93715)
    at ExecutionContext._ExecutionContext_evaluate (C:\xampp\htdocs\nodeVenom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\xampp\htdocs\nodeVenom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async C:\xampp\htdocs\nodeVenom\app.js:776:17
```

## Your Code

```
await client.getNumberProfile(number);
```

**Comment by riberman** [comment]
I had a similar problem with another client function, in my case I used it only to debug on the console, I just commented. It looks like this isLid function has been removed from the WhatsAppWeb JS, causing many functions to break using client.function()

**Comment by AdrielSantoss** [comment]
same problem here

**Comment by Im2rnado** [comment]
same problem here too

**Comment by fernandopraise** [comment]
mesmo caso aqui.. alguma previsão amigos
