### ISSUE TITLE
client.getHostDevice() crash e.isLid is not a function

### ISSUE THREAD

**Issue by gleberson-alves** [orkestral/venom#2107]
## Description

when i call await client.getHostDevice() i get e.isLid is not a function

## Environment

- **Venom version(s):** 4.3.7
- **OS:** Rocky Linux 9.1
- **Node version:** v16.17.1

## Log Output

 Error: Evaluation failed: TypeError: e.isLid is not a function
    at https://web.whatsapp.com/app.a8147d0b812215d14e1e.js:46:322773
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.9cbaf4c3ba39a27ff50e.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~app.9cbaf4c3ba39a27ff50e.js:2:66694)
    at https://web.whatsapp.com/vendor1~app.9cbaf4c3ba39a27ff50e.js:2:66753
    at K (https://web.whatsapp.com/app.a8147d0b812215d14e1e.js:40:104321)
    at new y (https://web.whatsapp.com/app.a8147d0b812215d14e1e.js:40:96888)
    at https://web.whatsapp.com/vendor1~app.9cbaf4c3ba39a27ff50e.js:2:66634
    at t.getAbout (https://web.whatsapp.com/app.a8147d0b812215d14e1e.js:46:322521)
    at t.getStatus (https://web.whatsapp.com/app.a8147d0b812215d14e1e.js:50:83373)
    at ExecutionContext._ExecutionContext_evaluate (/home/admin/robozap-beta/node_modules/puppeteer/src/common/ExecutionContext.ts:279:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (/home/admin/robozap-beta/node_modules/puppeteer/src/common/ExecutionContext.ts:145:12)
    at Whatsapp.getHostDevice (/home/admin/robozap-beta/node_modules/venom-bot/src/api/layers/host.layer.ts:347:12)
    at WhatsappVenom.checkPhone (/home/admin/robozap-beta/app/whatsapp/ultra-whats/clients/whatsappVenom.ts:285:24)
    at /home/admin/robozap-beta/app/whatsapp/ultra-whats/clients/whatsappVenom.ts:220:40
    at WhatsappVenom.whatsAppStart (/home/admin/robozap-beta/app/whatsapp/ultra-whats/clients/whatsappVenom.ts:117:20)
    at Proxy.whatsappStart (/home/admin/robozap-beta/app/Models/Whatsapp.ts:270:17)
    at WhatsappsController.startWhatsapp (/home/admin/robozap-beta/app/Controllers/Http/WhatsappsController.ts:200:21)

## Your Code
const device = await client.getHostDevice();
```
## Additional context / Screenshot

**Comment by gleberson-alves** [comment]
any solution?

**Comment by gleberson-alves** [comment]
not solved yet

**Comment by fernandovaller** [comment]
not solved yet

**Comment by SaDann** [comment]
This issue is not solved.
