### ISSUE TITLE
Error: Evaluation failed: TypeError: window.Store.Login.triggerCriticalSyncLogout is not a function

### ISSUE THREAD

**Issue by nandomegale** [orkestral/venom#2135]
## Description

I calling "client.logout()" to desconnect from service.

## Environment

- **Venom version(s):** [4.3.7]
- **Browser:** [Chrome 109.0.5414.75]
- **OS:** [Windows 10]
- **Node version:** [v16.13.1]

## Steps to Reproduce

1. Connect whatsapp.
2. Call "client.logout()".

## Log Output

initWhatsapp
successPageWhatsapp
info:     [four-be] Page successfully accessed
waitForLogin
isLoggednce: four-be]: Checking is logged...
✓ [instance: four-be]: Connected
waitChat
successChat
CONNECTED
Error: Evaluation failed: TypeError: window.Store.Login.triggerCriticalSyncLogout is not a function
    at window.WAPI.window.WAPI.logout (D:\Users\nando\Documents\4B\four-be-back\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:74612)
    at pptr://__puppeteer_evaluation_script__:1:13
    at ExecutionContext._ExecutionContext_evaluate (D:\Users\nando\Documents\4B\four-be-back\node_modules\puppeteer\src\common\ExecutionContext.ts:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\Users\nando\Documents\4B\four-be-back\node_modules\puppeteer\src\common\ExecutionContext.ts:145:12)
    at async Whatsapp.logout (D:\Users\nando\Documents\4B\four-be-back\node_modules\venom-bot\src\api\whatsapp.ts:125:12)

**Comment by legendbr94** [comment]
Sigo com o mesmo problema...

**Comment by nandomegale** [comment]
não. muda a lib. melhor a se fazer. não devem dar manutenção nisso aqui mais

**Comment by nandomegale** [comment]
estava avaliando usar a whatsapp-web.js
mas fica a critério de vocês mesmo

**Comment by legendbr94** [comment]
@nandomegale @victornassif  estou usando o whatsapp-web.js e cara muito mais rápido que o venon-bot. \o/
