### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'session')

### ISSUE THREAD

**Issue by Victor-FT** [orkestral/venom#2136]
## Description

[Description of the bug, When Issue Happens]

## Environment

- Venom version 4.3.7
- Browser:** Chrome 109.0.5414.119
- OS: Windows 11
- Node version: Node 16

## Steps to Reproduce

1. Erro ocorre na inicialização / error ocurred on inicialization

## Log Output

Unable to load the sleep module (no animations available)
info:     https://orkestral.io - official site!

Server Running
TypeError: Cannot read properties of undefined (reading 'session')
    at create (C:\Projetos\apiwppartigotas\node_modules\venom-bot\src\controllers\initializer.ts:178:48)
    at Sender.initialize (C:\Projetos\apiwppartigotas\src\sender.ts:91:15)
    at new Sender (C:\Projetos\apiwppartigotas\src\sender.ts:26:14)
    at Object.<anonymous> (C:\Projetos\apiwppartigotas\src\app.ts:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (C:\Projetos\apiwppartigotas\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Projetos\apiwppartigotas\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by Chamed** [comment]
any updates on this one?
