### ISSUE TITLE
e.quotedMsgObj is not a function on `loadEarlierMessages`

### ISSUE THREAD

**Issue by TiagoGouvea** [orkestral/venom#2160]
## Description

It crashes when trying to get earlier messages from a number

## Environment

- **Venom version(s):** 4.3.7
- **OS:** OSX 13.0.1
- **Node version:** Node 18

## Steps to Reproduce

Call `const messages = await client.loadEarlierMessages(number);`

## Log Output

```
Error: Evaluation failed: TypeError: e.quotedMsgObj is not a function
    at window.WAPI.window.WAPI._serializeMessageObj (/Users/tiagogouvea/www/tiago-artificial/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:36776)
    at Array.map (<anonymous>)
    at window.WAPI.window.WAPI.loadEarlierMessages (/Users/tiagogouvea/www/tiago-artificial/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:63848)
    at ExecutionContext._ExecutionContext_evaluate (/Users/tiagogouvea/www/tiago-artificial/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/tiagogouvea/www/tiago-artificial/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
    at async getReadMessages (file:///Users/tiagogouvea/www/tiago-artificial/whatsapp.js:14:22)
    at async handleCommands (file:///Users/tiagogouvea/www/tiago-artificial/commands.js:43:24)
    at async doTest (file:///Users/tiagogouvea/www/tiago-artificial/testCommands.js:24:17)
```

## Additional context / Screenshot

That method is marked as deprecated, but it's shown on docs, and I doesn't find a replacement method.

Calling `getAllMessagesInChat` with the same number returns the new messages.

**Comment by FaelN1** [comment]
https://github.com/orkestral/venom/issues/2067
