### ISSUE TITLE
removeParticipant function crashes

### ISSUE THREAD

**Issue by gurbieta** [orkestral/venom#2180]
## Description

removeParticipant crashes (window.Store.sendRemoveParticipants is not a function)

## Environment

- **Venom version(s):** 4.3.7
- **Browser:** N/A
- **OS:** OSX 13.2.1
- **Node version:** v19.7.0

## Steps to Reproduce

When calling the function ```removeParticipant(groupId, userId)``` venom-bot crashes, the log shows window.Store.sendRemoveParticipants is not a fuction

## Log Output

```
Error: Evaluation failed: TypeError: window.Store.sendRemoveParticipants is not a function
    at window.WAPI.window.WAPI.removeParticipant (/Users/myuser/whatsapp-bot/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:41899)
    at ExecutionContext._ExecutionContext_evaluate (/Users/myuser/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/myuser/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
    at async Whatsapp.removeParticipant (/Users/myuser/whatsapp-bot/node_modules/venom-bot/dist/api/layers/group.layer.js:261:16)
```

## Your Code

```
client.removeParticipant(groupId, userId);
```

## Additional context / Screenshot

I tried deleting the dependencies and redownloading, but nothing changed.

**Comment by gurbieta** [comment]
Hi, this repo is still being maintained?

**Comment by gurbieta** [comment]
Hi @orkestral, this repo is still being maintained?
