### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by ritikkumarsahu** [orkestral/venom#2207]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):**4.3.7
- **Browser:** [Chromium ]
- **OS:** Windows 11
- **Node version:** v17.9.1

## Steps to Reproduce

1. Start venom session
2. Read QR Code
3. Run client.getChatIsOnline
## Log Output

```
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'get')
    at window.WAPI.window.WAPI.getChatIsOnline (D:\Projects\NodeJS\WhatsappInfoBot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:73466)
    at __puppeteer_evaluation_script__:1:19
    at ExecutionContext._evaluateInternal (D:\Projects\NodeJS\WhatsappInfoBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\Projects\NodeJS\WhatsappInfoBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Whatsapp.getChatIsOnline (D:\Projects\NodeJS\WhatsappInfoBot\node_modules\venom-bot\dist\api\layers\retriever.layer.js:278:16)
    at async Timeout._onTimeout (D:\Projects\NodeJS\WhatsappInfoBot\venom_test.js:30:22)

Node.js v17.9.1
```

## Your Code
const venom = require('venom-bot');

venom
  .create({
    session: 'my-session', //name of session
    // headless: false,
    // devtools: true,
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
  setInterval(async () => {
    const isOnline = await client.getChatIsOnline("xxxxxxxxxxxx@c.us");
    console.log(`xxxxxxxxxx is ${isOnline? 'online': 'offline'}`);
  }, 1000);
}

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ritikkumarsahu** [comment]
I was not logged in. once I logged in, the error resolved.
