### ISSUE TITLE
Error trying to send a message: Cannot read property 'isWidlike' of undefined

### ISSUE THREAD

**Issue by iAndreas** [orkestral/venom#2209]
## Description

Sometimes when I try to send a message using `sendFile()` function I got this error: `(node:12757) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'isWidlike' of undefined`.

My code is very simple, just: 
```
client.sendFile(
  `5547988579151@c.us`,
  'https://bucket-nxfacil.s3.sa-east-1.amazonaws.com/bucket-nxfacil/nx1785/maladireta/teste.pdf',
  'teste.pdf',
  'some text message'
)
.then((result) => {
  res.end('ok');
})
.catch((erro) => {
  console.error(erro);
  res.end('erro');
});
```

If I restart the node service and reopen the session it works for a time, then suddenly this error occurs again.

Full error log:
```
(node:12757) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'isWidlike' of unde
fined
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at Object.window.WAPI.window.WAPI.sendCheckType (/usr/share/nginx/html/api_whatsapp/node_modules/venom-bot/dist/lib/wapi/wap
i.js:1:32019)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at Object.window.WAPI.window.WAPI.sendExist (/usr/share/nginx/html/api_whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js
:1:33582)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at Object.l [as sendFile] (/usr/share/nginx/html/api_whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:25968)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at pptr://__puppeteer_evaluation_script__:2:29
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at ExecutionContext._ExecutionContext_evaluate (/usr/share/nginx/html/api_whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/
common/ExecutionContext.js:286:15)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at runMicrotasks (<anonymous>)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at async ExecutionContext.evaluate (/usr/share/nginx/html/api_whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/Execu
tionContext.js:117:16)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: at async /usr/share/nginx/html/api_whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:561:28
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: (node:12757) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside 
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejec
tions=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mar 26 09:19:38 ip-172-31-14-91.sa-east-1.compute.internal api_whatsapp[12757]: (node:12757) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections th
at are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by FaelN1** [comment]
Hello friend, use the command "npm update @wppconnect/wa-js --save" and your problem will be solved.

**Comment by iAndreas** [comment]
I runned the update command but the error still occurring. The versions I'm running are:
node v12.22.9
venom-bot@4.3.7
@wppconnect/wa-js@2.22.0

**Comment by amosayomide05** [comment]
Update your node version

**Comment by iAndreas** [comment]
Tryed on Erbium's Latest LTS (v12.22.12) and Gallium's Latest LTS (v16.20.0) all in latest versions of venom and wppconnect packages, both kept the error. I can't try on Hydrogen versions (higher than 18.12.0) cause my server uses AWS Amazon Linux 2 and only supports glibc 2.26. Which node version is the correct? There's anything I can try to update again?
