### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')

### ISSUE THREAD

**Issue by rafaelsnnoleto** [orkestral/venom#2215]
## Description

My whatsapp messaging service was working properly, no new version was released, no update was done on my server and this problem started to happen.

## Environment

- **Venom version(s):** 4.3.7
- **Browser:** Chrome 111.0.5563.146 (Versão oficial) 64 bits
- **OS:** Ubuntu 20.04.6 LTS 64bits - Gnome 3.36.8
- **Node version:** Now using node v14.19.3 (npm v6.14.17)

## Steps to Reproduce

1. Connect whatsapp with qrcode (success)
2. Send a single message

## Log Output

```
✓ [instance: testeinicial1]: Connected
(node:45544) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')
    at window.WAPI.window.WAPI.sendCheckType (/home/rafaelnoleto/programas/projetos/belgadata/controller-whatsapp/controller-whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:32019)
    at window.WAPI.window.WAPI.sendExist (/home/rafaelnoleto/programas/projetos/belgadata/controller-whatsapp/controller-whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33582)
    at window.WAPI.window.WAPI.sendMessage (/home/rafaelnoleto/programas/projetos/belgadata/controller-whatsapp/controller-whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:46138)
    at pptr://__puppeteer_evaluation_script__:2:29
    at ExecutionContext._ExecutionContext_evaluate (/home/rafaelnoleto/programas/projetos/belgadata/controller-whatsapp/controller-whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/rafaelnoleto/programas/projetos/belgadata/controller-whatsapp/controller-whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
    at async /home/rafaelnoleto/programas/projetos/belgadata/controller-whatsapp/controller-whatsapp/node_modules/venom-bot/dist/api/layers/sender.layer.js:120:28
(Use `node --trace-warnings ...` to show where the warning was created)
(node:45544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Your Code

```
sendText: async function (req, res) {
		let status = true;
		if (!controllerClients[req.query.sessionName]) {
			status = await this.reconnect(req, res);
		}

		if (status && controllerClients[req.query.sessionName] && controllerClients[req.query.sessionName]['client']) {
			try {
				status = await controllerClients[req.query.sessionName]['client'].isConnected();
				if (status) {
					let result = await controllerClients[req.query.sessionName]['client'].sendText(req.query.number + '@c.us', req.query.message);
					if (!result.erro) {
						this.messageSuccess(req, res, req.query.number);
					} else {
						this.messageError(req, res, req.query.number, erro);
					}
				} else {
					this.killProcess(controllerClients[req.query.sessionName]['browserPid']);
					this.deleteSession(req, res);
					this.messageNoConnection(req, res, req.query.number);
				}
			} catch (error) {
				this.killProcess(controllerClients[req.query.sessionName]['browserPid']);
				this.deleteSession(req, res);
				this.messageNoConnection(req, res, req.query.number + ' - ' + error);
			}
		} else {
			this.messageNoConnection(req, res, req.query.number);
		}
	},
```

**Comment by iAndreas** [comment]
I have the same problem. Updating the package wppconnect or even nodejs version doesn't work. I'd ask to collaborators not close this issue as completed like the others opened by the same error.

**Comment by paulotolentino** [comment]
I was getting this error when the number I was trying to send the message wasn't a whatsapp number. Some user didn't have the extra "9" (Brazil) in they number.

**Comment by jonalan7** [comment]
Try the most current version! removed wppconnect project from venom-bot!
