### ISSUE TITLE
wapi.js error send message

### ISSUE THREAD

**Issue by LeonardoFreitag** [orkestral/venom#2216]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s): latast
- **Browser: Chrome 87
- **OS:** OSX, LINUX, WINDOWS
- **Node version: Node 18.13.0

## Steps to Reproduce

1. Start venom
2. try to send simple message
3. An error is generated and showing the contents of wapi.js. it is showing the below message as well.

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')
    at window.WAPI.window.WAPI.sendCheckType (/Users/leonardofreitag/NodeProjects/whats-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:32019)
    at window.WAPI.window.WAPI.sendExist (/Users/leonardofreitag/NodeProjects/whats-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33582)
    at window.WAPI.window.WAPI.sendMessage (/Users/leonardofreitag/NodeProjects/whats-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:46138)
    at pptr://__puppeteer_evaluation_script__:2:29
    at ExecutionContext._ExecutionContext_evaluate (/Users/leonardofreitag/NodeProjects/whats-api/node_modules/puppeteer/src/common/ExecutionContext.ts:279:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/leonardofreitag/NodeProjects/whats-api/node_modules/puppeteer/src/common/ExecutionContext.ts:145:12)
    at async /Users/leonardofreitag/NodeProjects/whats-api/node_modules/venom-bot/src/api/layers/sender.layer.ts:137:22
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jonalan7** [comment]
this problem has already been fixed
