### ISSUE TITLE
getConnectionState is failing

### ISSUE THREAD

**Issue by BhagavatiAntala** [orkestral/venom#2217]
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket')
at pptr://__puppeteer_evaluation_script__:3:32
at ExecutionContext._ExecutionContext_evaluate (./puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext.evaluate (./puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
at async Whatsapp.getConnectionState (./venom-bot/dist/api/layers/host.layer.js:245:16)

**Comment by BhagavatiAntala** [comment]
etConnectionState=await client.getConnectionState(); getting failed
