### ISSUE TITLE
Error: Evaluation failed: TypeError: e.isLid is not a function

### ISSUE THREAD

**Issue by omarmyousef** [orkestral/venom#2225]
## Description

Calling the function `client.getHostDevice()` causes crash
and this error appears: (node:10204) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.isLid is not a function

## Environment

- **Venom version(s): ^4.3.7** 
- **Browser: included chromiom** 
- **OS: Windows 10**
- **Node version: v18.12.1**

## Steps to Reproduce

just call client.getHostDevice() after creating one

## Log Output

```
(node:10204) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.isLid is not a function
    at https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:46:240605
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66694)
    at https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66753
    at Y (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:5:140100)
    at new y (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:5:132667)
    at https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66634
    at c (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:46:241122)
    at t.getAbout (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:46:240353)
    at ExecutionContext._ExecutionContext_evaluate (M:\Creator\Freelancing\projects\691811_wa_marketing\project-software\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)      
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (M:\Creator\Freelancing\projects\691811_wa_marketing\project-software\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async Whatsapp.getHostDevice (M:\Creator\Freelancing\projects\691811_wa_marketing\project-software\node_modules\venom-bot\dist\api\layers\host.layer.js:233:16)
    at async MODULE_WA.start (M:\Creator\Freelancing\projects\691811_wa_marketing\project-software\app\modules\whatsapp\wa.js:42:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:10204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

## Your Code

```
client.getHostDevice();
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by marceviana** [comment]
Same here.

**Comment by jonalan7** [comment]
this problem has already been fixed
