### ISSUE TITLE
getNumberProfile - TypeError: e.isLid is not a function

### ISSUE THREAD

**Issue by TiagoGouvea** [orkestral/venom#2229]
## Description

I've tried to use getNumberProfile but it's buggy.

## Environment

Venom version(s): 4.3.7
Browser: Chromium
OS: Windows 10, Ubuntu 20.04
Node version: Node 18, Node 16

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

Error: Evaluation failed: TypeError: e.isLid is not a function
    at https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:46:240605
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66694)
    at https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66753
    at Y (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:5:140100)
    at new y (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:5:132667)
    at https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66634
    at c (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:46:241122)
    at t.getAbout (https://web.whatsapp.com/app.0067e3224e6db3ee85de.js:46:240353)
    at ExecutionContext._ExecutionContext_evaluate (/Users/tiagogouvea/www/tiago-artificial/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)

## Your Code

```
const user = await client.getNumberProfile(nn);
```

**Comment by TiagoGouvea** [comment]
It's strange to have an automatic default message saying "we are currently fixing this bug".

**Comment by jonalan7** [comment]
this issue has been fixed!

**Comment by TiagoGouvea** [comment]
Thanks @jonalan7 !
Does this new version has some breaking changes? Or is it safe to update using the same code as before?

**Comment by TiagoGouvea** [comment]
In fact the error still happening on the new version:

```
Error: Evaluation failed: TypeError: e.isLid is not a function
    at https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:46:243429
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.a91035d81a749b3d5627.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~app.a91035d81a749b3d5627.js:2:66694)
    at https://web.whatsapp.com/vendor1~app.a91035d81a749b3d5627.js:2:66753
    at j (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:5:141934)
    at new E (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:5:134501)
    at https://web.whatsapp.com/vendor1~app.a91035d81a749b3d5627.js:2:66634
    at c (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:46:243946)
    at t.getAbout (https://web.whatsapp.com/app.d38ba36ba32224f079bb.js:46:243177)
    at ExecutionContext._ExecutionContext_evaluate (/Users/tiagogouvea/www/tiago-artificial/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/tiagogouvea/www/tiago-artificial/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)
    at async start (file:///Users/tiagogouvea/www/tiago-artificial/index.js:69:18)
```

**Comment by TiagoGouvea** [comment]
@ jonalan7 can you confirm that it was fixed?
I updated to `5.0.0` and the error persisted.
