### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by devalexanderdaza** [orkestral/venom#224]
Hi, when run my script, in the terminal show this message

```bash
1] - Checking for updates
[1] - Waiting...
[1] - check headless
[1] - Checking for updates
[1] - Waiting...
[1] - headless option is active, browser hidden
[1] - Checking for updates
[1] - Waiting...
[1] - headless option is active, browser hidden
[1] - Checking for updates
[1] - Authenticating...
[1] - headless option is active, browser hidden
[1] Status Session:  isLogged
[1] - Checking for updates
[1] - Authenticated
[1] - headless option is active, browser hidden
[1] - Checking for updates
[1] - Authenticated
[1] - headless option is active, browser hidden
[1] - Injecting Sibionte...
[1] - Checking for updates
[1] - Authenticated
[1] - headless option is active, browser hidden
[1] - Starting With Success!
[1] - Checking for updates
[1] - Authenticated
[1] - headless option is active, browser hidden
[1] - Saving Token...
[1] - (node:8118) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'includes' of undefined
[1]     at Object.window.WAPI.sendExist (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:31764)
[1]     at async Object.window.WAPI.sendMessage (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:37952)
[1]     at ExecutionContext._evaluateInternal (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1]     at ExecutionContext.evaluate (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
[1]   -- ASYNC --
[1]     at ExecutionContext.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/helper.js:94:19)
[1]     at DOMWorld.evaluate (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/DOMWorld.js:89:24)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1]   -- ASYNC --
[1]     at Frame.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/helper.js:94:19)
[1]     at Page.evaluate (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/Page.js:612:14)
[1]     at Page.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/helper.js:95:27)
[1]     at Whatsapp.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:108:72)
[1]     at step (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
[1]     at Object.next (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
[1]     at /Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
[1]     at /Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:104:87
[1]   -- ASYNC --
[1]     at Page.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/puppeteer/lib/helper.js:94:19)
[1]     at Whatsapp.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:108:72)
[1]     at step (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
[1]     at Object.next (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
[1]     at /Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
[1]     at /Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:104:87
[1]     at new Promise (<anonymous>)
[1]     at Whatsapp.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Whatsappi/VenomAPI/node_modules/venom-bot/dist/api/layers/sender.layer.js:104:39)
[1] (node:8118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[1] (node:8118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] - Checking for updates
[1] - Authenticated
[1] - headless option is active, browser hidden
[1] - Token saved successfully...```

My create object is:

```
venom.create(
    'Venom',
    (base64Qrimg: any, asciiQR: any, attempts: any) => {
      console.log('Attemps to read QR Code: ', attempts);
      console.log('Terminal qrcode: ', asciiQR);
      console.log('base64 image string qrcode: ', base64Qrimg);
    },
    (statusSession: any) => {
      console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile
    },
    {
      folderNameToken: 'tokens', //folder name when saving tokens
      mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
      headless: true, // Headless chrome
      devtools: false, // Open devtools by default
      useChrome: true, // If false will use Chromium instance
      debug: false, // Opens a debug session
      logQR: true, // Logs QR automatically in terminal
      disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
      disableWelcome: true, // Will disable the welcoming message which appears in the beginning
      updatesLog: true, // Logs info updates automatically in terminal
      autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
      createPathFileToken: false, //creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
    }
  ).then((client: any) => { start(client); }).catch((erro: any) => { console.log(erro); });
```

Any idea guys? Thanks

**Comment by joaosouz4dev** [comment]
I think this has already been fixed, if not, try to send us more details about your code in new issue, maybe the problem is in it
