### ISSUE TITLE
node 12.18 LTS: browser.setMaxListeners is not a function

### ISSUE THREAD

**Issue by panzi** [orkestral/venom#23]
I tried to figure out the other bug that I've reported and upgraded node to the newest LTS version (12.18.0) and now I get this crash on startup:

```
TypeError: browser.setMaxListeners is not a function
    at StealthPlugin.onBrowser (/home/x/x/shared/node_modules/puppeteer-extra-plugin-stealth/index.js:155:13)
    at StealthPlugin._bindBrowserEvents (/home/x/x/shared/node_modules/puppeteer-extra-plugin/src/index.ts:527:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at PuppeteerExtra.callPlugins (/home/x/x/shared/node_modules/puppeteer-extra/src/index.ts:449:7)
    at PuppeteerExtra.launch (/home/x/x/shared/node_modules/puppeteer-extra/src/index.ts:175:5)
```

Using pupeteer 4.0.0. Is that not the version I should use?

**Comment by orkestral** [comment]
no, use version 3.0.0

**Comment by panzi** [comment]
Thank you. That should be documented somewhere, though.

Now I get a different error:
```
Error: ENOENT: no such file or directory, open './data/whatsapp/436643927764@c.us/DevToolsActivePort'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.<anonymous> (/home/x/x/shared/node_modules/venom-bot/dist/controllers/initializer.js:240:63)
    at step (/home/x/x/shared/node_modules/venom-bot/dist/controllers/initializer.js:44:23)
    at Object.next (/home/x/x/shared/node_modules/venom-bot/dist/controllers/initializer.js:25:53)
    at fulfilled (/home/x/x/shared/node_modules/venom-bot/dist/controllers/initializer.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './data/whatsapp/436643927764@c.us/DevToolsActivePort'
}
```

Does that mean I need to pass `devtools: true`? (Or at least not `devtools: false`?)

**Comment by orkestral** [comment]
yes
