### ISSUE TITLE
Error after scanning QR Code and connecting

### ISSUE THREAD

**Issue by Divino67** [orkestral/venom#2306]
## Description

As soon as the session status arrives in "waitChat" the puppeteer gives a timeout error

## Environment

- **Venom version: 4.3.7
- **OS:** Linux Ubuntu 22.04.2 LTS
- **Node version:** Node v16.19.0

## Steps to Reproduce

1. [First Step] Normal connection procedure
2. [Second Step] Scan the qr code
3. [and so on...] Wait to finish the connection

## Log Output

TimeoutError: waiting for function failed: timeout 30000ms exceeded
            at new WaitTask (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:680:34)
            at DOMWorld.waitForFunction (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:611:26)
            at Frame.waitForFunction (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1089:32)
            at Page.waitForFunction (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2385:33)
            at injectApi (/app/node_modules/venom-bot/dist/controllers/browser.js:140:16)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at async Object.create (/app/node_modules/venom-bot/dist/controllers/initializer.js:302:9)

**Comment by Carloslml** [comment]
In version 5.0.1 it shows this error, a new update in WhatsApp has generated these problems and does not register functions such as onMessage(), the QR can be read but it does not respond
Error in console 
![image](https://github.com/orkestral/venom/assets/37524166/f2a7a0ab-e990-4316-9c81-0ab85701f38d)

**Comment by sandro-salles** [comment]
Maybe related to https://github.com/orkestral/venom/issues/2308
