### ISSUE TITLE
ERROR last update WhatsApp, after scanning QR Code and connecting

### ISSUE THREAD

**Issue by Carloslml** [orkestral/venom#2307]
## Description

Posible error ? cannot register window.WAPI ?

[Description of the bug, When Issue Happens]

## Environment

- **Venom version 5.0.1
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version: v16.14.0

## Steps to Reproduce

1. Read QR
2. No register functions (onMessage...)

## Log Output

TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\Personal\aaa\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:680:34)
    at DOMWorld.waitForFunction (C:\Users\Personal\aaa\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:611:26)
    at Frame.waitForFunction (C:\Users\Personal\aaa\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:1089:32)
    at Page.waitForFunction (C:\Users\Personal\aaa\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2385:33)
    at injectApi (C:\Users\Personal\aaa\node_modules\venom-bot\dist\controllers\browser.js:140:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\Personal\aaa\node_modules\venom-bot\dist\controllers\initializer.js:297:9)
## Your Code

const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    headless: false,
	puppeteerOptions: { headless: false },
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}

## Additional context / Screenshot
Error in console

![image](https://github.com/orkestral/venom/assets/37524166/4d7807e0-6bfe-4599-9a0a-a9f054bedcad)

**Comment by ghayman** [comment]
Version 4.3.7 is reporting the same browser error:

`
serviceworker.js:43 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:43:169687
    at Generator.next (<anonymous>)
    at t (serviceworker.js:1:34510)
    at s (serviceworker.js:1:34721)`

**Comment by PedroMiotti** [comment]
Having the same problem on production, any updates on this issue?

**Comment by Carloslml** [comment]
> Having the same problem on production, any updates on this issue?

In #2308 He suggested the solution, i try his but not work for me

**Comment by PedroMiotti** [comment]
> > Having the same problem on production, any updates on this issue?
> 
> In #2308 He suggested the solution, i try his but not work for me

I haven't tried yet, but which version are you running?

**Comment by Carloslml** [comment]
> > > Having the same problem on production, any updates on this issue?
> > 
> > 
> > In #2308 He suggested the solution, i try his but not work for me
> 
> I haven't tried yet, but which version are you running?

With 4.3.7, and 5.0.1 neither of the two work

**Comment by ghayman** [comment]
I implement the suggested fix in 4.3.7

The line we're looking for there is wapi.js - 201

`window['webpackChunkwhatsapp_web_client'] =
  window['webpackChunkwhatsapp_web_client'] || [];
`
was changed to 
`if (typeof window['webpackChunkwhatsapp_web_client'] === 'undefined') {
  window['webpackChunkwhatsapp_web_client'] = [];
}
`

However this only seems to be a partial fix - seems very slow to register plus onStreamChange (e.g. LOGOUT) does not seem to fire

**Comment by Carloslml** [comment]
> I implement the suggested fix in 4.3.7
> 
> The line we're looking for there is wapi.js - 201
> 
> `window['webpackChunkwhatsapp_web_client'] = window['webpackChunkwhatsapp_web_client'] || []; ` was changed to `if (typeof window['webpackChunkwhatsapp_web_client'] === 'undefined') { window['webpackChunkwhatsapp_web_client'] = []; } `
> 
> However this only seems to be a partial fix - seems very slow to register plus onStreamChange (e.g. LOGOUT) does not seem to fire

Thanks, this error I solve with this code #2308
