### ISSUE TITLE
Error version 5.0.3  Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by DenisAlvesDias** [orkestral/venom#2318]
## Description
Error 

Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:320:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:533:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\xampp\htdocs\whats_chatbot_v2\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\xampp\\htdocs\\whats_chatbot_v2\\node_modules\\venom-bot\\package.json',
  requestPath: 'venom-bot'

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s): 5.0.3
- **Browser:** 
- **OS: Windows 11
- **Node version 16

**Comment by HamaDevek** [comment]
> ## Description
> Error
> 
> Please verify that the package.json has a valid "main" entry at tryPackage (internal/modules/cjs/loader.js:320:19) at Function.Module._findPath (internal/modules/cjs/loader.js:533:18) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27) at Function.Module._load (internal/modules/cjs/loader.js:745:27) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at Object. (D:\xampp\htdocs\whats_chatbot_v2\index.js:3:15) at Module._compile (internal/modules/cjs/loader.js:1072:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) at Module.load (internal/modules/cjs/loader.js:937:32) { code: 'MODULE_NOT_FOUND', path: 'D:\xampp\htdocs\whats_chatbot_v2\node_modules\venom-bot\package.json', requestPath: 'venom-bot'
> 
> [Description of the bug, When Issue Happens]
> 
> ## Environment
> * **Venom version(s): 5.0.3
> * **Browser:**
> * **OS: Windows 11
> * **Node version 16

Same

**Comment by thalles7765** [comment]
I have same problem after updated for version 5.0.3, i old version is 5.0.1..

**Comment by tataredhaalfath** [comment]
I have the same problem with version 5.0.3. and why this issue already closed yet ?

**Comment by Divino67** [comment]
same here on version 5.0.3
