### ISSUE TITLE
Error [ReferenceError]: WAPI is not defined

### ISSUE THREAD

**Issue by CarlosAurelioMRF** [orkestral/venom#2376]
## Description

After deleting the token directory I can connect only once. 2nd try results in this error.

## Environment

- **Venom version:** 5.0.11
- **Browser:** HeadlessChrome/114.0.5735.198
- **OS:** linux
- **Node version:** 18.16.1

## Log Output

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ReferenceError]: WAPI is not defined
    at evaluate (evaluate at Whatsapp.addChatWapi (/home/node/node_modules/venom-bot/dist/api/whatsapp.js:70:25), <anonymous>:0:12)
    at ExecutionContext._ExecutionContext_evaluate (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:262:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/node/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:145:16)
    at async Whatsapp.addChatWapi (/home/node/node_modules/venom-bot/dist/api/whatsapp.js:70:9)
    at async /home/node/node_modules/venom-bot/dist/api/whatsapp.js:47:13
```

## Your Code

```
      const client = await create({
        session: this.session.id,
        mkdirFolderToken: 'storage/app/session',
        disableWelcome: true,
        updatesLog: false,
        disableSpins: true,
        logQR: false,
        autoClose: 0,
        catchQR: async (base64Qr) => {
          const filePath = `storage/app/qr-code`
          const fileName = `${this.session.id}-${new Date().getTime()}.png`

          const imageBuffer = Buffer.from(
            base64Qr.replace('data:image/png;base64,', ''),
            'base64'
          )

          await createFile(filePath, fileName, imageBuffer, 'binary')

          await this.sessionService.updateSession({
            id: this.session.id,
            qrCodePath: `${filePath}/${fileName}`
          })
        }
      })
```

**Comment by karein** [comment]
Similar problem,
I did use workaround by adding `headless: true` in the browser.js file, and it did works for WhatsApp.
But when i use **_WhatsApp Business_** it runs/connect ok at first time, but in the second, it gives me the QR Code again **and does not stay connected**.
It only happened on Linux, I tested it on Windows, and it reconnects just fine after stopping and restarting the server.
On Linux i cannot stop the server or WhatsApp business will disconnect.
https://github.com/orkestral/venom/issues/2372
