### ISSUE TITLE
mobile logout session error message

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#239]
mobile logout session error message
session status desconnectedMobile
(node:29081) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Takeover called without conflict!

**Comment by bhavya32** [comment]
@Lucipher Can you tell what is issue? Yes this is error message. There is no question or problem specified.

**Comment by Lucipher** [comment]
@joaosouz4dev  what's the problem with this issue ?  has it been fixed ?

**Comment by GabrielBels** [comment]
I'm getting similar problem: 

Error: Evaluation failed: TypeError: Cannot read property 'takeover' of undefined
    at Object.window.WAPI.window.WAPI.takeOver (C:\Users\GabrielBelisario\Desktop\BOT_Aguiar\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:73382)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (C:\Users\GabrielBelisario\Desktop\BOT_Aguiar\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\GabrielBelisario\Desktop\BOT_Aguiar\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

This is showing when I disconnect my WhatsApp by the phone.
