### ISSUE TITLE
client.deleteMessage -> n.sendRevokeMsgs is not a function

### ISSUE THREAD

**Issue by RickGroenewegen** [orkestral/venom#2411]
## Description

Whenever I try to delete a message using deleteMessage I'm getting the following error:

`Error [TypeError]: n.sendRevokeMsgs is not a function
    at #evaluate (/myproject/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/myproject/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
    at async /myproject/node_modules/venom-bot/dist/api/layers/controls.layer.js:168:28
    at window.WAPI.window.WAPI.deleteMessages (/myproject/node_modules/venom-bot/dist/lib/wapi/wapi.js:0:60634)
Unhandled Rejection at: TypeError: n.sendRevokeMsgs is not a function
    at #evaluate (/myproject/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/myproject/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
    at async /myproject/node_modules/venom-bot/dist/api/layers/controls.layer.js:168:28
    at window.WAPI.window.WAPI.deleteMessages (/myproject/node_modules/venom-bot/dist/lib/wapi/wapi.js:0:60634)`

## Environment

- Venom 5.0.13
- OSX 14
- Node 18

## Steps to Reproduce

`client.deleteMessage('31634994428-1636016771@g.us', [ 'true_31634994428-1636016771@g.us_N2BT2NAMAL9ID629' ]).then((result) => {
// result handling
	}).catch((err) => {
		console.log(err);
	});`

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
