### ISSUE TITLE
Error: Cannot find module 'npm-check-updates'

### ISSUE THREAD

**Issue by vitoropereira** [orkestral/venom#2417]
## Description
Error: Cannot find module 'npm-check-updates'

## Environment

- **Venom version(s):**  "venom-bot": "^5.0.13"
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:**: lts/hydrogen

## Steps to Reproduce

1. npm init
2. npm install venom-bot
3. npm install @types/node tsx typescript -D
4. Create script package.json: `"dev": "tsx index.ts"`
5. run `npm run dev`

## Log Output
Require stack:
- ...\node_modules\venom-bot\dist\controllers\check-up-to-date.js
- ...\node_modules\venom-bot\dist\controllers\init.js
- ...\node_modules\venom-bot\dist\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.u.default._resolveFilename (...\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:1519)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at <anonymous> (...\node_modules\venom-bot\dist\controllers\check-up-to-date.js:11:45)
    at Object.<anonymous> (...\node_modules\venom-bot\dist\controllers\check-up-to-date.js:47:10)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.F (...\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\node_modules\\venom-bot\\dist\\controllers\\check-up-to-date.js',
    '...\\node_modules\\venom-bot\\dist\\controllers\\init.js',
    '...\\node_modules\\venom-bot\\dist\\index.js'
  ]
}

## Your Code

```
import { create } from 'venom-bot'

create({
    session: 'bot',
})
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro)
    })

async function start(client) {
    const botText = "Bot teste"
    
client.onAnyMessage((message) => {
        if (message.body.toLowerCase() === "hello") {
            client.sendText(message.from, botText)
        }
    })
}
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by andremorettin** [comment]
npm i npm-check-updates

**Comment by assiz-git** [comment]
npm i npm-check-updates --save-dev
