### ISSUE TITLE
The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable

### ISSUE THREAD

**Issue by chacalgbi** [orkestral/venom#2430]
## Description

Venon 5.0.6 was working, when updating to 5.0.16 it shows this error. Does anyone know how to resolve?
I tried installing google again but the error persists.

Error checking Chrome installation: ChromePathNotSetError
    at new LauncherError (/home/iot/node_modules/venom-bot/node_modules/chrome-launcher/dist/utils.js:26:22)
    at new ChromePathNotSetError (/home/iot/node_modules/venom-bot/node_modules/chrome-launcher/dist/utils.js:33:9)
    at Object.linux (/home/iot/node_modules/venom-bot/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Launcher.getInstallations (/home/iot/node_modules/venom-bot/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51)
    at getChrome (/home/iot/node_modules/venom-bot/dist/controllers/browser.js:505:60)
    at initBrowser (/home/iot/node_modules/venom-bot/dist/controllers/browser.js:279:13)
    at /home/iot/node_modules/venom-bot/dist/controllers/initializer.js:83:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  message: 'The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.',
  code: 'ERR_LAUNCHER_PATH_NOT_SET'
}
Path Google-Chrome:  /root/.cache/puppeteer/chrome/linux-115.0.5790.98/chrome-linux64/chrome
Error: Command failed: google-chrome --version
/bin/sh: 1: google-chrome: not found

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'google-chrome --version'
}
✖ Error no open browser....
✓ Platform: linux
05/08/2023, 09:31:01 VENOM Error no open browser....

## Environment

- **Venom version(s): 5.0.6 to 5.0.16
- **Browser: ??
- **OS: Ubuntu 22
- **Node version: 18.16.0

**Comment by jonalan7** [comment]
try to install this version:

```
curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt-get update
sudo apt-get install -f
which google-chrome
```

**Comment by aryzing** [comment]
If using Brave (and similarly for other Chromium-based browsers),

```shell
CHROME_PATH=$(which brave-browser) npm run dev
```
