### ISSUE TITLE
Error: r.findImpl is not a function

### ISSUE THREAD

**Issue by rafael3007** [orkestral/venom#2437]
## Description

the code loads, reads the tokens, but when accessing the venom functions to send a message, it generates the error below:

Error [TypeError]: r.findImpl is not a function
https://web.whatsapp.com/app.9bf7959578bdb7663582.js:51:175453
    at #evaluate (C:\Users\user\Desktop\Mensageria\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:252:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\user\Desktop\Mensageria\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:149:16)
    at async C:\Users\user\Desktop\Mensageria\node_modules\venom-bot\dist\api\layers\sender.layer.js:327:28
    at window.WAPI.window.WAPI.sendExist (C:\Users\user\Desktop\Mensageria\node_modules\venom-bot\dist\lib\wapi\wapi.js:0:43448)
    at find (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:173547)
    at _query (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:175063)
    at _serverQuery (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:175780)
    at <anonymous> (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66633)
    at <anonymous> (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66752)
    at s (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66693)
    at t (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66482)
    at <anonymous> (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:175452)

## Environment

- **Venom version(s):** ^5.0.16
- **Browser:** Chrome/115.0.5790.171
- **OS:** win32
- **Node version:** v18.17.1

## Log Output
Error [TypeError]: r.findImpl is not a function
https://web.whatsapp.com/app.9bf7959578bdb7663582.js:51:175453
    at #evaluate (C:\Users\user\Desktop\Mensageria\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:252:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\user\Desktop\Mensageria\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:149:16)
    at async C:\Users\user\Desktop\Mensageria\node_modules\venom-bot\dist\api\layers\sender.layer.js:327:28
    at window.WAPI.window.WAPI.sendExist (C:\Users\user\Desktop\Mensageria\node_modules\venom-bot\dist\lib\wapi\wapi.js:0:43448)
    at find (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:173547)
    at _query (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:175063)
    at _serverQuery (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:175780)
    at <anonymous> (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66633)
    at <anonymous> (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66752)
    at s (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66693)
    at t (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:1:66482)
    at <anonymous> (https://web.whatsapp.com/app.9bf7959578bdb7663582.js:50:175452)

## Your Code

```
// Supports ES6
import { create, Whatsapp } from 'venom-bot';
import { getInformacoes } from './Transmissao.js';

create({
    session: 'session-name' //name of session
})
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
    });

async function start(client) {
    // Buscar todas as informações da planilha para serem enviadas pelo WhatsApp
    let result = await getInformacoes()

    console.log(result)
    // Envio de mensagem para cada número retornado da planilha
    result.numeros.map((item => {
        client
            .sendText(item + "@c.us", result.mensagem)
            .then((result) => {
                //console.log(result)
            })
            .catch((erro) => {
                //console.error("Result:" + erro)
            });
    }))

}
```

## Additional context 

The code is a simple message sending with venom where you make a request and get a list of numbers. This list is mapped and for each number the message is sent

**Comment by EdesNogueira** [comment]
same here..

**Comment by jonalan7** [comment]
This issue has been fixed in the latest version. Please update!
