### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'erro')     at E:\estudos\estudos-2023\rms\chatbot-rms\node_modules\venom-bot\dist\api\layers\sender.layer.js:330:23           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### ISSUE THREAD

**Issue by Civitao** [orkestral/venom#2448]
## Description

Getting this error message on every very  message event: 

" TypeError: Cannot read properties of undefined (reading 'erro')     at E:\estudos\estudos-2023\rms\chatbot-rms\node_modules\venom-bot\dist\api\layers\sender.layer.js:330:23           at process.processTicksAndRejections (node:internal/process/task_queues:95:5) :  ". 

started from sudden and i don't know what is happening. i've already started another project to see if it was a bug on the dependencies of the first one

## Environment

- **Venom version(s):** [ 5.0.11]  ( not being able to update via npm update)
- **Browser:** [Chrome/116.0.5845.98]
- **OS:** [Windows 10]
- **Node version:** [Node v18.14.0]

## Steps to Reproduce

1. Create a src folder and a server.js file inside it
2. Paste this piece of code, a normal message response and receive: 
3. import venom from 'venom-bot';

const chatsHistory = new Map();

function addMessageToHistory(phone, message) {
  if (!chatsHistory.has(phone)) {
    chatsHistory.set(phone, []);
  }
 chatsHistory.get(phone).push(message);
}

function clearUserChatHistory(message) {
  chatsHistory.delete(phone);
}

function sendGreeting(phone) {
  addMessageToHistory(phone, 'sendGreeting')
  const opcoes = ['Pessoa Fisica', 'Pessoa Jurídica', 'Profissionais Liberais'];

  return `
    Olá! Bem-vindo a RMS!.

    Escolha uma das seguintes opções:
    *1.* ${opcoes[0]}
    *2.* ${opcoes[1]}
    *3.* ${opcoes[2]}

  `;
}

function firstStep(phone, firstSelection) {

 
  if (firstSelection === '1') {
    addMessageToHistory(phone, ['firstStep', firstSelection])

    const opcoesPf = [
      "Seguro de automóvel",
      "Seguro Residencial",
      "Seguro de vida",
      "Financiamento de veículos",
      "Seguro Viagem",
      "Seguro de vida Mulher",
      "Acidentes pessoais",
      "Previdência Complementar",
      "Apoio Familiar",
      "Equipamentos portáteis",
      "Consórcios",
      "Carta Verde",
    ];

    return `
      Ótimo! 

      Agora, escolha uma das seguintes opções:
      1. ${opcoesPf[0]}
      2. ${opcoesPf[1]}
      3. ${opcoesPf[2]}
      4. ${opcoesPf[3]}
      5. ${opcoesPf[4]}
      6. ${opcoesPf[5]}
      7. ${opcoesPf[6]}
      8. ${opcoesPf[7]}
      9. ${opcoesPf[8]}
      10. ${opcoesPf[9]}
      11. ${opcoesPf[10]}
      12. ${opcoesPf[11]}
    `;
  }

  if(firstSelection === '2') {
    addMessageToHistory(phone, 'firstStep')

    const opcoesPj = ["Acidentes pessoais", 
      "Equipamentos",
      "Patrimonial Condominial",
      "Riscos de Engenharia",
      "Náutico ",
      "Responsabilidade Civil",
      "Vida em Grupo",
      "Educacional",
      "Previdência Empresarial",
      "Garantia",
      "Crédito",
      "Patrimonial Empresarial",
      "Aeronáutico ",
      "Frotas de veículos", ]

    return `
    Ótimo! 

    Agora, escolha uma das seguintes opções:
    *1* ${opcoesPj[0]}
    *2* ${opcoesPj[1]}
    *3* ${opcoesPj[2]}
    *4* ${opcoesPj[3]}
    *5* ${opcoesPj[4]}
    *6* ${opcoesPj[5]}
    *7* ${opcoesPj[6]}
    *8* ${opcoesPj[7]}
    *9* ${opcoesPj[8]}
    *10* ${opcoesPj[9]}
    *11* ${opcoesPj[10]}
    *12* ${opcoesPj[11]}
    *13* ${opcoesPj[12]}
    *14* ${opcoesPj[13]}

    *0* Voltar
  `;
  }

  if(firstSelection === '3') {
    addMessageToHistory(phone, 'firstStep')

    const opcoesPj = ["Vida Individual", "Previdência Privada", "Patrimonial", "Equipamentos Profissionais", "Responsabilidade Civil (D&O) e (E&O)"]

    return `
    Ótimo! 

    Agora, escolha uma das seguintes opções:
    *1* ${opcoesPj[0]}
    *2* ${opcoesPj[1]}
    *3* ${opcoesPj[2]}
    *4* ${opcoesPj[3]}
    *5* ${opcoesPj[4]}
   
    *0* Voltar
  `;
  }

 
}

function mensagemFinal(phone, opcao1, opcao2) {
  return `
    Parabéns! Você selecionou as seguintes opções:
    1. ${opcao1}
    2. ${opcao2}

    Obrigado por usar nosso bot!
  `;
}

venom.create({
  session: 'rms'
}).then((client) => {
  client.onMessage(async (message) => {
    const phone = message.from;
    const messageContent = message.body.trim().toLowerCase();
    if (!chatsHistory.has(phone)) {
      chatsHistory.set(phone, []);
    }
    let history = chatsHistory.get(phone)

    

    
      if(!history.includes('sendGreeting')) {
        //sending my first message  
        await client.sendText(phone, sendGreeting(phone));

      }

      if(messageContent === '0') {
        history.pop();
      }

      if (!history.includes('firstStep')) {
        await client.sendText(phone, firstStep(phone, messageContent));

      }
        else {
         await client.sendText(phone, 'Opção inválida. Escolha novamente.');
        }
       

        if (history.includes('completedfirstStep-1')) {
          await client.sendText(phone, 'Obrigado! Já chamei alguém pra te atender');

      } else {
        // Mensagem final com as opções selecionadas
        
        // history.push('finalizar'); // Adicione uma marcação para finalizar a conversa
        // clearUserChatHistory(phone); // Limpe o histórico após a mensagem final
      }
    // }
  });
}).catch((error) => {
  console.log(error);
});

4. start with node src/server.js
5. scan QRCode
6. send a message to it

## Log Output

TypeError: Cannot read properties of undefined (reading 'erro')     at E:\estudos\estudos-2023\rms\chatbot-rms\node_modules\venom-bot\dist\api\layers\sender.layer.js:330:23           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```
If relevant, paste all of your Log Output
```

## Your Code

```  import venom from 'venom-bot';



  const chatsHistory = new Map();

  function addMessageToHistory(phone, message) {
    if (!chatsHistory.has(phone)) {
      chatsHistory.set(phone, []);
    }
  chatsHistory.get(phone).push(message);
  }

  function clearUserChatHistory(message) {
    chatsHistory.delete(phone);
  }

  function sendGreeting(phone) {
    addMessageToHistory(phone, 'sendGreeting')
    const opcoes = ['Pessoa Fisica', 'Pessoa Jurídica', 'Profissionais Liberais'];

    return `
      Olá! Bem-vindo a RMS Seguros!.

      Escolha uma das seguintes opções:
      *1.* ${opcoes[0]}
      *2.* ${opcoes[1]}
      *3.* ${opcoes[2]}

    `;
  }

  function firstStep(phone, firstSelection) {

  
    if (firstSelection === '1') {
      addMessageToHistory(phone, ['firstStep', firstSelection])

      const opcoesPf = [
        "Seguro de automóvel",
        "Seguro Residencial",
        "Seguro de vida",
        "Financiamento de veículos",
        "Seguro Viagem",
        "Seguro de vida Mulher",
        "Acidentes pessoais",
        "Previdência Complementar",
        "Apoio Familiar",
        "Equipamentos portáteis",
        "Consórcios",
        "Carta Verde",
      ];

      return `
        Ótimo! 

        Agora, escolha uma das seguintes opções:
        1. ${opcoesPf[0]}
        2. ${opcoesPf[1]}
        3. ${opcoesPf[2]}
        4. ${opcoesPf[3]}
        5. ${opcoesPf[4]}
        6. ${opcoesPf[5]}
        7. ${opcoesPf[6]}
        8. ${opcoesPf[7]}
        9. ${opcoesPf[8]}
        10. ${opcoesPf[9]}
        11. ${opcoesPf[10]}
        12. ${opcoesPf[11]}
      `;
    }

    if(firstSelection === '2') {
      addMessageToHistory(phone, 'firstStep')

      const opcoesPj = ["Acidentes pessoais", 
        "Equipamentos",
        "Patrimonial Condominial",
        "Riscos de Engenharia",
        "Náutico ",
        "Responsabilidade Civil",
        "Vida em Grupo",
        "Educacional",
        "Previdência Empresarial",
        "Garantia",
        "Crédito",
        "Patrimonial Empresarial",
        "Aeronáutico ",
        "Frotas de veículos", ]

      return `
      Ótimo! 

      Agora, escolha uma das seguintes opções:
      *1* ${opcoesPj[0]}
      *2* ${opcoesPj[1]}
      *3* ${opcoesPj[2]}
      *4* ${opcoesPj[3]}
      *5* ${opcoesPj[4]}
      *6* ${opcoesPj[5]}
      *7* ${opcoesPj[6]}
      *8* ${opcoesPj[7]}
      *9* ${opcoesPj[8]}
      *10* ${opcoesPj[9]}
      *11* ${opcoesPj[10]}
      *12* ${opcoesPj[11]}
      *13* ${opcoesPj[12]}
      *14* ${opcoesPj[13]}

      *0* Voltar
    `;
    }

    if(firstSelection === '3') {
      addMessageToHistory(phone, 'firstStep')

      const opcoesPj = ["Vida Individual", "Previdência Privada", "Patrimonial", "Equipamentos Profissionais", "Responsabilidade Civil (D&O) e (E&O)"]

      return `
      Ótimo! 

      Agora, escolha uma das seguintes opções:
      *1* ${opcoesPj[0]}
      *2* ${opcoesPj[1]}
      *3* ${opcoesPj[2]}
      *4* ${opcoesPj[3]}
      *5* ${opcoesPj[4]}
    
      *0* Voltar
    `;
    }

  
  }

  function mensagemFinal(phone, opcao1, opcao2) {
    return `
      Parabéns! Você selecionou as seguintes opções:
      1. ${opcao1}
      2. ${opcao2}

      Obrigado por usar nosso bot!
    `;
  }

  venom.create({
    session: 'rms-seguros'
  }).then((client) => {
    client.onMessage(async (message) => {
      const phone = message.from;
      const messageContent = message.body.trim().toLowerCase();
      if (!chatsHistory.has(phone)) {
        chatsHistory.set(phone, []);
      }
      let history = chatsHistory.get(phone)

      

      
        if(!history.includes('sendGreeting')) {
          //sending my first message  
          await client.sendText(phone, sendGreeting(phone));

        }

        if(messageContent === '0') {
          history.pop();
        }

        if (!history.includes('firstStep')) {
          await client.sendText(phone, firstStep(phone, messageContent));


        }
          else {
          await client.sendText(phone, 'Opção inválida. Escolha novamente.');
          }
        

          if (history.includes('completedfirstStep-1')) {
            await client.sendText(phone, 'Obrigado! Já chamei alguém pra te atender');

        } else {
          // Mensagem final com as opções selecionadas
          
          // history.push('finalizar'); // Adicione uma marcação para finalizar a conversa
          // clearUserChatHistory(phone); // Limpe o histórico após a mensagem final
        }
      // }
    });
  }).catch((error) => {
    console.log(error);
  });



If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Civitao** [comment]
solved by forced update
