### ISSUE TITLE
protocolTimeout while getUnreadMessages

### ISSUE THREAD

**Issue by CarlosAurelioMRF** [orkestral/venom#2479]
## Description
When I try to collect all unread messagens the error of protocolTimeout is displayed.

## Environment

- **Venom version(s):** latest
- **Browser:** Chrome 117.0.5938.88
- **OS:** linux
- **Node version:** 18

## Steps to Reproduce

1. Calling `getUnreadMessages()`

## Log Output
```
[handleUnreadMessage] ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:49:14)
    at new Callback (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:53:16)
    at CallbackRegistry.create (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:93:26)
    at Connection._rawSend (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:26)
    at CDPSessionImpl.send (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:433:33)
    at #evaluate (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/node/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
    at async Whatsapp.getUnreadMessages (/home/node/node_modules/venom-bot/dist/api/layers/retriever.layer.js:254:16)
    at async WhatsappIntegrationService.handleUnreadMessage (/home/node/dist/whatsapp-integration/whatsapp-integration.service.js:556:30)
```

**Comment by usamastr** [comment]
Facing same issue any solution ?
