### ISSUE TITLE
Get Group Members

### ISSUE THREAD

**Issue by RAKESHSUVIDYA** [orkestral/venom#2540]
## Description

I am getting **Error [TypeError]: window.Store.Cmd.openChatBottom is not a function** . When I am trying to fetch group members.

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code
Error [TypeError]: window.Store.Cmd.openChatBottom is not a function
    at #evaluate (/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:229:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:128:16)
    at async CdpFrame.evaluate (/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:363:20)
    at async CdpPage.evaluate (/app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:744:20)
    at async /app/components/contact.js:30:29
    at window.WAPI.window.WAPI.getGroupParticipant (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:0:87757)

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by EntropicBlackhole** [comment]
I'm also having this problem, same with getting groupAdmins
