### ISSUE TITLE
TypeError: waPage.waitForTimeout is not a function

### ISSUE THREAD

**Issue by Steve2955** [orkestral/venom#257]
After updating to the newest version `2.0.18` without changing any of my code I started getting to following error:

```
TypeError: waPage.waitForTimeout is not a function
    at Object.<anonymous> (/opt/fahrschul-reminder-bot/node_modules/venom-bot/dist/controllers/browser.js:139:36)
    at step (/opt/fahrschul-reminder-bot/node_modules/venom-bot/dist/controllers/browser.js:44:23)
    at Object.next (/opt/fahrschul-reminder-bot/node_modules/venom-bot/dist/controllers/browser.js:25:53)
    at fulfilled (/opt/fahrschul-reminder-bot/node_modules/venom-bot/dist/controllers/browser.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Downgrading to version `2.0.16` fixed the issue for now.

**Comment by caugustoschiller** [comment]
Same problem here

**Comment by AlanMartines** [comment]
Same problem here too.

**Comment by caugustoschiller** [comment]
Seens after a clean install problem is solved

**Comment by AlanMartines** [comment]
For me it did not work, it is still giving error.

**Comment by AlanMartines** [comment]
Normalized only after changing from **waPage.waitForTimeout** to **waPage.waitFor** in the browser.js file.

**Comment by joaosouz4** [comment]
when does the error happen?

**Comment by joaosouz4** [comment]
waPage.waitForTimeout is only available with the updated puppeteer.

**Comment by AlanMartines** [comment]
I forced the updated puppeteer, functioning normally.

Thank you for your help.
