### ISSUE TITLE
Error ESM

### ISSUE THREAD

**Issue by satishgunasekaran** [orkestral/venom#2571]
/home/satishg/Documents/Personal/WABuddy/backend/node_modules/venom-bot/dist/controllers/browser.js:30
const ChromeLauncher = __importStar(require("chrome-launcher"));
                                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/satishg/Documents/Personal/WABuddy/backend/node_modules/chrome-launcher/dist/index.js from /home/satishg/Documents/Personal/WABuddy/backend/node_modules/venom-bot/dist/controllers/browser.js not supported.
Instead change the require of index.js in /home/satishg/Documents/Personal/WABuddy/backend/node_modules/venom-bot/dist/controllers/browser.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/satishg/Documents/Personal/WABuddy/backend/node_modules/venom-bot/dist/controllers/browser.js:30:37)
    at Object.<anonymous> (/home/satishg/Documents/Personal/WABuddy/backend/node_modules/venom-bot/dist/controllers/initializer.js:6:19) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v21.2.0

**Comment by 9cb14c1ec0** [comment]
I've been running into this too.  It looks like a bunch of dependencies are have moved from commonjs to esm format, and venom will need to either do the same or revert to dependency versions that are not esm.

**Comment by 9cb14c1ec0** [comment]
For the moment, you can fix this error by setting the venom-bot version in package.json to "github:9cb14c1ec0/venom#non-esm".  @orkestral , should I open a pull request?
