### ISSUE TITLE
Javascript error:webpackChunkwhatsapp_web_client is not defined error after whatsapp business 2.3 version update

### ISSUE THREAD

**Issue by rajeshshettysrs** [orkestral/venom#2631]
## Description

I am getting Javascript error:webpackChunkwhatsapp_web_client is not defined while sending message after whatsapp business 2.3 version update

## Environment

Window 10

## Steps to Reproduce

 upgrade to whatsapp business 2.3 version 

![Javascript error webpackChunkwhatsapp_web_client is not defined](https://github.com/orkestral/venom/assets/20316958/3099f136-efda-4d8c-b363-f5ca54c83a72)

**Comment by frankdors** [comment]
Here have a idea to get modules to new version...

Someone can help to convert moduleraid?
https://d33gom43gwygbg.cloudfront.net/utils/api.js

**Comment by ghayman** [comment]
I think this is about to become a serious issue as soon as WhatsApp rolls their current Beta version to Production

Our current setup appears to invoke web.whatsapp.com Version 2.2411.2
- every thing is fine

When I enable Beta version I get web.whatsapp.com version Version 2.3000.1012062581
- not fine at all
`Error [ReferenceError]: WAPI is not defined
    at evaluate (evaluate at Whatsapp.addChatWapi (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/venom/dist/api/whatsapp.js:72:25), <anonymous>:0:12)
    at #evaluate (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
    at async Whatsapp.addChatWapi (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/venom/dist/api/whatsapp.js:72:9)
    at async /Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/venom/dist/api/whatsapp.js:49:13
Error [ReferenceError]: WAPI is not defined
    at evaluate (evaluate at Whatsapp.addChatWapi (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/venom/dist/api/whatsapp.js:72:25), <anonymous>:0:12)
    at #evaluate (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:149:16)
    at async Whatsapp.addChatWapi (/Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/venom/dist/api/whatsapp.js:72:9)
    at async /Users/ghayman/projects/txtsmarter/whatsapp-v2-agent/venom/dist/controllers/initializer.js:333:13

`

**Comment by rajeshshettysrs** [comment]
https://github.com/mikelustosa/Projeto-TInject/blob/master/Source/JS/js.abr is working thank's to "Mike W. Lustosa" sir,please give star to 'https://github.com/mikelustosa/Projeto-TInject' project,if solution works

**Comment by ghayman** [comment]
@rajeshshettysrs I'm not clear why this was closed.

How does this file fix venom-bot?

Please could you give details on what you did to make it work?
Thanks in advance!

**Comment by 9cb14c1ec0** [comment]
See also #2646

**Comment by 9cb14c1ec0** [comment]
And #2654
