### ISSUE TITLE
problem in the getNumberProfile function

### ISSUE THREAD

**Issue by wagnerdavanco** [orkestral/venom#2635]
## Description

When using the `client.getNumberProfile(phone)` function to obtain the profile of a phone number, I am experiencing problems retrieving the correct profile information.

## Environment

- **Venom version(s):** 5.0.21
- **Browser:** N/A
- **OS:** Windows 11
- **Node version:** 20.11.1

## Steps to Reproduce

1. Initialize the Venom client.
2. Call the function `client.getNumberProfile(phone)` with the desired phone number.
3. Check the information returned.

## Log Output

```
Error [TypeError]: e.isLid is not a function
https://web.whatsapp.com/app.a325b87cf6fdeb29465c.js:263:370888
    at #evaluate (C:\repos\Talk.BigWhats\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:222:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\repos\Talk.BigWhats\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:117:16)
    at async IsolatedWorld.evaluate (C:\repos\Talk.BigWhats\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:124:16)
    at async CdpFrame.evaluate (C:\repos\Talk.BigWhats\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:353:20)
    at async CdpPage.evaluate (C:\repos\Talk.BigWhats\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:841:20)
    at async C:\repos\Talk.BigWhats\index.js:167:22
    at window.WAPI.window.WAPI.getNumberProfile (C:\repos\Talk.BigWhats\node_modules\venom-bot\dist\lib\wapi\wapi.js:0:91369)
    at <anonymous> (https://web.whatsapp.com/app.a325b87cf6fdeb29465c.js:256:231130)
    at <anonymous> (https://web.whatsapp.com/app.a325b87cf6fdeb29465c.js:262:370723)
    at c (https://web.whatsapp.com/app.a325b87cf6fdeb29465c.js:262:371036)
    at <anonymous> (https://web.whatsapp.com/vendor1~app.264a01b6133c4a120327.js:1:66637)
    at <anonymous> (https://web.whatsapp.com/vendor1~app.264a01b6133c4a120327.js:1:66756)
    at s (https://web.whatsapp.com/vendor1~app.264a01b6133c4a120327.js:1:66697)
    at t (https://web.whatsapp.com/vendor1~app.264a01b6133c4a120327.js:1:66486)
    at <anonymous> (https://web.whatsapp.com/app.a325b87cf6fdeb29465c.js:262:370887)
```

## Your Code

```javascript
// Example code demonstrating the usage of client.getNumberProfile(fone)
const venom = require('venom-bot');

venom.create().then((client) => {
  const fone = '+1234567890';
  client.getNumberProfile(fone).then((profile) => {
    console.log(profile);
  }).catch((error) => {
    console.error('Error:', error);
  });
}).catch((error) => {
  console.error('Failed to create client:', error);
});

**Comment by 9cb14c1ec0** [comment]
As best I can tell, this is a bug in the javascript from WhatsApp itself.  I don't think there is anything this project can do about it.
