### ISSUE TITLE
error loading the bot

### ISSUE THREAD

**Issue by fquero47** [orkestral/venom#268]
hello when I try to load the bot I'm getting a new error:

```


    ▐█  ██  █░▐█▀▀▀░▐█     ▄█▀▀█▄ ▄█▀▀█▄ ▐██   ██▌ ▓█▀▀▀░
     █▌▐██▄▓█ ▐█▄▄▄ ▐█    ▐█      █▒  ▐█▄▐█▀▌ ▐▌█▌ ▓█▄▄▄
     ▐██ ▐██░ ▐█    ▐█    ▐█▄  ▄▀ █▌  ▐█ ▐█ █▓█ █▌ ██
      ▀▀  ▀▀  ▀▀▀▀▀░▐▀▀▀▀▀  ▀▀▀▀   ▀▀▀▀  ▐▀  ▀  ▀▀ ▀▀▀▀▀
                                   ▄
      ▄▄░          ▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄ ██         ▄▄       ▄▄▄▄      ░
      ░██▄        ██ ███▀▀▀▀▀▀▀▀█▌ ███▌       ██▄  ▄▄█▀▀▀▀▀▀█▄   ▓█▄           ▄█░
       ░██▄     ░██▀ ███           ██▀██▄     ██▄ ▄█░        ▀█▄ ▓███▄      ░████░
         ██▌   ▄██░ ▄███▄▄▄▄       ██  ▓██▄   ██▄▐█           ▐█ ▓█▌▀██▄  ▄███░██░
          ██▌ ▄██░  ▀███▀▀▀▀       ██   ▐██▌  ██▄▐█           ▐█░▓█▌  ▀█████░  ██░
           ▓████     ███           ██     ▀██▄██▄ █▌          ██ ▓█▌    ▀█░    ██░
            ▀██      ███        █▌ ██       ▀███▄  ▀█▄     ▄▄█▀  ▓█▌           ██░
             ▀       ▀███████████▌ ██        ░██▄    ▀▀███▀▀░    ▀█▌           ▓█░
                                              ▀░

- Checking for updates
- Checking for updates
- Waiting...
- Checking for updates
- Waiting...
- Checking for updates
- Waiting...
- check headless
- Checking for updates
- Waiting...
- headless option is active, browser hidden
TypeError: waPage.waitForTimeout is not a function
    at Object.<anonymous> (/wbot/node_modules/venom-bot/dist/controllers/browser.js:139:36)
    at step (/wbot/node_modules/venom-bot/dist/controllers/browser.js:44:23)
    at Object.next (/wbot/node_modules/venom-bot/dist/controllers/browser.js:25:53)
    at fulfilled (/wbot/node_modules/venom-bot/dist/controllers/browser.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)

```

Can any of you help me to solve this issue ?

**Comment by caugustoschiller** [comment]
#257

**Comment by jonalan7** [comment]
**Esse problema vai ser corrigido nas próximas atualizações**
