### ISSUE TITLE
Error: Page crashed! How to catch it.

### ISSUE THREAD

**Issue by marutichintan** [orkestral/venom#27]
`Error: Page crashed!
    at Page._onTargetCrashed (/home/whatsapp/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.<anonymous> (/home/whatsapp/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/home/whatsapp/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/home/whatsapp/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocket.<anonymous> (/home/whatsapp/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/home/whatsapp/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/whatsapp/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
`

how to catch it.

**Comment by orkestral** [comment]
At the moment we only support here for problems on Venom, for these details we have a group on whatsapp, with more than 50 people to help you.

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

Thank You!
