### ISSUE TITLE
Error [TypeError]: window.WAPI.waitNewAcknowledgements is not a function

### ISSUE THREAD

**Issue by Micheltukker** [orkestral/venom#2713]
## Description

When starting Venom the following error is printed

` Error [TypeError]: window.WAPI.waitNewAcknowledgements is not a function
    at evaluate (evaluate at Whatsapp.initService (<REMOVED>\venom\dist\api\whatsapp.js:81:29), <anonymous>:14:12)
    at #evaluate (<REMOVED>\venom\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (<REMOVED>\venom\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (<REMOVED>\venom\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:131:16)
    at async CdpFrame.evaluate (<REMOVED>\venom\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:363:20)
    at async CdpPage.evaluate (<REMOVED>\venom\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:751:20)
    at async Whatsapp.initService (<REMOVED>\venom\dist\api\whatsapp.js:81:13)
    at async <REMOVED>\venom\dist\api\whatsapp.js:47:13`

## Steps to Reproduce

Tested it with the test script "test/index,js" from the repo.

Used the official version on NPM (5.1.0) and the version here from Github.

## Your Code

``` typescript
const { tree } = require('gulp');
const venom = require('../dist');

venom.create({
    session: 'sessionname', //name of session
    headless: false,
    logQR: true,
  })
  .then((client) => {
    start(client);
  });

async function start(client) {

  const f = await client.getHostDevice();
  console.log(await client.getWAVersion());
  console.log(f);
  // client.onMessage((message) => {
  //   console.log(message);
  // });
  // const allMessages = await client.getAllUnreadMessages();
  // console.log(allMessages);
}
```

**Comment by orkestral** [comment]
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357

**Comment by PedroPC23** [comment]
I have the same error :(

**Comment by orkestral** [comment]
#2730

**Comment by Micheltukker** [comment]
> @orkestral I'm not sure that these are related - could you reopen this ticket while I investigate some more?

Still occurs in the latest Github version.
