### ISSUE TITLE
Not able to Login after scannig QR code (it fails)

### ISSUE THREAD

**Issue by sahil-patel6** [orkestral/venom#2751]
## Description

QR Code scan is reloading every time I scan and I am not able to login

## Environment

- **Venom version(s):** 5.1.0
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** Ubuntu Server 22.04.2 LTS
- **Node version:** v16

## Steps to Reproduce

1. insalled venom-bot and added the code given in docs
2. started and got the error of no browser installed
3. so installed browser by following these steps in https://askubuntu.com/questions/245041/how-do-i-install-chrome-on-a-server/1132008#1132008

## Log Output
After scanning QR code, after some time it throws this error and on my phone it tells me "Couldn't log in. Check your phone's internet connection and scan the QR code again" even though I have proper high speed internet connection
urlCode (data-ref):  undefined,klL2biuCq2+qlHOy9l0RC5ytRPT2nG//81aa6sfYD2w=,mt9AaJQ7EaP+LrEVky3d4xR4TO/27s0Kff0NTG+JI0k=,CqKD2wzF1o0Buv23xj8OhP79jCQ0vM3EmtIW0f+XW7w=,1
^Cwaiting for introduction
⠸ [instance: session-test]: Waiting for QRCode Scan...
✖ Was disconnected!
✖ Disconnected by cell phone!

**Comment by zeekhuge** [comment]
To add more context to the issue, here's the log:

```bash
Fetched token details...
Got token ...
- check nodeJs version...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
You're up to date 🎉🎉🎉
- Waiting... checking the browser...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- ...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- ...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- ...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- ...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- checking SingletonLock file
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Waiting... checking the browser...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- Browser successfully opened
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- checking headless...
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Checking page to whatzapp...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting page load
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Checking is logged...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 1
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 2
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 3
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 4
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 5
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 6
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Waiting for QRCode Scan: Attempt 7
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- waiting for introduction
- [instance: 81f92890cd38e6_1717381618199]: Page Closed
TargetCloseError: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CdpCDPSession.send (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:64:35)
    at #evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:202:50)
    at ExecutionContext.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:117:36)
    at IsolatedWorld.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:124:30)
    at CdpFrame.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:353:43)
    at CdpFrame.<anonymous> (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:841:43)
    at Whatsapp.addChatWapi (/build/node_modules/venom-bot/dist/api/whatsapp.js:88:25)
    at /build/node_modules/venom-bot/dist/api/whatsapp.js:50:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TargetCloseError: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CdpCDPSession.send (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:64:35)
    at #evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:202:50)
    at ExecutionContext.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:117:36)
    at IsolatedWorld.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:124:30)
    at CdpFrame.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:353:43)
    at CdpFrame.<anonymous> (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.evaluate (/build/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:841:43)
    at Whatsapp.addChatWapi (/build/node_modules/venom-bot/dist/api/whatsapp.js:88:25)
    at /build/node_modules/venom-bot/dist/api/whatsapp.js:50:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- Erro intro
- [instance: 81f92890cd38e6_1717381618199]: Page Closed
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- Erro intro
- [instance: 81f92890cd38e6_1717381618199]: Checking QRCode status...
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- Erro intro
- [instance: 81f92890cd38e6_1717381618199]: Failed to authenticate
- Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md
- Node.js version verified successfully!
- headless option is active, browser hidden
- Executable path browser: /usr/bin/google-chrome-stable
- Platform: linux
- Browser Version: 125.0.6422.141
- Path Stored "SingletonLock": /build/tokens/81f92890cd38e6_1717381618199/SingletonLock
- The file "SingletonLock" was not found
- Page successfully accessed
- Erro intro
- [instance: 81f92890cd38e6_1717381618199]: Unknow error

```

**Comment by sahil-patel6** [comment]
@zeekhuge hey bro, I think you also are facing the same issue I did. After doing much debugging I found that my server did not have enough resources so once I upgraded my server then it worked fine.
