### ISSUE TITLE
Error [TypeError]: Cannot read properties of undefined (reading 'map') while "deleteMessage()"

### ISSUE THREAD

**Issue by abhilash-uzdpart** [orkestral/venom#2753]
## Description

When i try to delete a message the bug is happening. 
Thanks in advance.
## Your Code
```
var moredetails = ["moredetails":{
    "failed": [],
    "success": [
        {
            "msgId": "true_000000000000@c.us_DUCLSJF9KU2WH1NV",
            "phoneNumber": "000000000000@c.us"
        }
    ]
}];
moredetails = moredetails[0].moredetails;
try {
                            const phoneNumber = moredetails.success.phoneNumber;
                            const msg_ids = [moredetails.success.msgId];

                            console.log(`Attempting to delete messages with msg_ids: ${JSON.stringify(msg_ids)} for: ${phoneNumber}`);

                            const response = await clientInstances[api_secret].deleteMessage(phoneNumber, msg_ids);
                            console.log("response = ", response);
                        } catch (erro) {
                            console.log(erro);
                        }
```
## Environment

- **Venom version(s):**  venom-bot@5.1.0
- **Browser:** Chrome 
- **OS:** ubuntu server os 22.04
- **Node version:** 22.2.0

## Steps to Reproduce

1. run the deleteMessage(number,msgId)
2. wait for the bug to appear.
3. surprise!

## Log Output

Error [TypeError]: Cannot read properties of undefined (reading 'map')
at window.WAPI.window.WAPI.deleteMessages (evaluate at Whatsapp.initService (/home/info/node/uzd_srm/node_modules/venom-bot/dist/api/whatsapp.js:80:29), <anonymous>:0:62558)
at #evaluate (/home/info/node/uzd_srm/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:222:56)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext.evaluate (/home/info/node/uzd_srm/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:117:16)
at async IsolatedWorld.evaluate (/home/info/node/uzd_srm/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:124:16)
at async CdpFrame.evaluate (/home/info/node/uzd_srm/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:353:20)
at async CdpPage.evaluate (/home/info/node/uzd_srm/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:841:20)
at async /home/info/node/uzd_srm/node_modules/venom-bot/dist/api/layers/controls.layer.js:167:28
at e (https://static.whatsapp.net/rsrc.php/v3i-zO4/yQ/l/rt/jsam99zo1D7.js?_nc_x=Ij3Wp8lg5Kz:739:3499)

**Comment by abhilash-uzdpart** [comment]
Hello guys
Any help is appreciated!
