### ISSUE TITLE
 UnhandledPromiseRejectionWarning: on send Sticker (Image and GIF)

### ISSUE THREAD

**Issue by DaviSMoura** [orkestral/venom#289]
When i send a sticker with
```client.sendImageAsSticker(message.from, "teste.jpeg");```

i'am getting this error:
```
(node:9428) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'modelClass' of undefined
    at w (C:\Users\DaviDEV\Documents\Programação\BotZipZop\meubot\node_modules\venom-bot\dist\lib\wapi\wapi.js:8:24768)
    at async Object.h (C:\Users\DaviDEV\Documents\Programação\BotZipZop\meubot\node_modules\venom-bot\dist\lib\wapi\wapi.js:8:25501)
    at ExecutionContext._evaluateInternal (C:\Users\DaviDEV\Documents\Programação\BotZipZop\meubot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Users\DaviDEV\Documents\Programação\BotZipZop\meubot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(node:9428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 682)
(node:9428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kaiserdj** [comment]
The same thing happens to me

**Comment by V1n1c1uz** [comment]
same thing with me.

**Comment by tadeubarbosa** [comment]
same here

**Comment by jonalan7** [comment]
**whatzapp updated, we are trying to fix the function!**
