### ISSUE TITLE
Error on getGroupMembers()

### ISSUE THREAD

**Issue by effer89** [orkestral/venom#293]
Venom version: 2.0.18

When calling ```client.getGroupMembers``` it throws this:

```
errorHandler Error: Evaluation failed: TypeError: Cannot read property 'find' of undefined
    at Object.window.WAPI.getGroupMetadata (/var/www/whats-bot/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:51308)
    at c (/var/www/whats-bot/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:23584)
    at Object.window.WAPI.getGroupParticipantIDs (/var/www/whats-bot/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:51449)
    at __puppeteer_evaluation_script__:1:35
    at ExecutionContext._evaluateInternal (/var/www/whats-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It started today, can someone help me? :P

**Comment by gustavoalistic** [comment]
Estou com o mesmo problema, porém em getGroupAdmins
