### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by dmzoneill** [orkestral/venom#30]
Is there a way to catch these errors

`(node:108995) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.Page.client.on (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocketTransport._ws.addEventListener (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
(node:108995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:108995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled wi
ll terminate the Node.js process with a non-zero exit code.
`

**Comment by orkestral** [comment]
At the moment we only support here for problems on Venom, for these details we have a group on whatsapp, with more than 50 people to help you.

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

Thank You!
