### ISSUE TITLE
(node:124162) UnhandledPromiseRejectionWarning: Error: Page crashed!

### ISSUE THREAD

**Issue by dmzoneill** [orkestral/venom#31]
Hey,

Thank you for providing this solution.

I raised this issue yesterday also in the whatsapp chat.
It does not make any sense to move issues and support into the whatsapp channel.

When i have an issue, i search the issues on the github page for other similar issues and possible solutions.

If you move the support into the whatsapp, you are going to have people asking the same issues over and over.  because answers are going to be in a chat in whatsapp, that you cant search back in time.

Please can you keep this issue open.  Its after happening again today... 

NOT for me, but for everyone who comes looking for a solution

https://github.com/orkestral/venom/issues/30

`(node:124162) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.Page.client.on (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocketTransport._ws.addEventListener (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
(node:124162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:124162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by joaosouz4** [comment]
@dmzoneill We need to create this flow of markups in the solutions git, but how did you reproduce this error?

**Comment by dmzoneill** [comment]
hi @joaosouz4 

I'm looking through the puppeteer issues now for possible solutions to catch and solve the exception.

My bot is here: nothing special
https://github.com/dmzoneill/ashtangayogacork.ie-whatsbot/blob/master/bot.js

**Comment by dmzoneill** [comment]
https://github.com/puppeteer/puppeteer/issues/1321
https://github.com/puppeteer/puppeteer/issues/5975
https://github.com/puppeteer/puppeteer/issues/5974
https://github.com/puppeteer/puppeteer/issues/5797
https://github.com/puppeteer/puppeteer/issues/4925

no real leads here with this... 

behavior seen with page scrolls.
1) my bot clears the chat after each message to avoid build up.
    ill modify this to do it less aggressive.

chromium version
2) ill attempt a different version of chromium

memory issues
3) docker /dev/shm
im not using docker but i will look into memory availability.  running on a headless server

update here soon

**Comment by dmzoneill** [comment]
sudo apt-get remove google-chrome*
sudo apt-get install chromium

dave@feeditout:~/ashtangayogacork.ie-whatsbot$ dpkg --list | grep chromium
ii  chromium                              80.0.3987.162-1~deb10u1               amd64        web browser
ii  chromium-common                       80.0.3987.162-1~deb10u1               amd64        web browser - common resources used by the chromium packages
ii  chromium-sandbox                      80.0.3987.162-1~deb10u1               amd64        web browser - setuid security sandbox for chromium

**Comment by dmzoneill** [comment]
changing to chromium may have exposed a bug

`(node:152855) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Promise was collected
    at Promise (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:152:63)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:151:16)
    at ExecutionContext._evaluateInternal (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/ExecutionContext.js:85:50)
    at ExecutionContext.evaluate (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/ExecutionContext.js:33:27)
    at ExecutionContext.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:95:27)
    at DOMWorld.evaluate (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:95:27)
    at Whatsapp.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:396:49)
    at step (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.startTyping (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:394:16)
  -- ASYNC --
    at Page.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:94:19)
    at Whatsapp.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:396:49)
    at step (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.startTyping (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:394:16)
    at do_message (/home/dave/ashtangayogacork.ie-whatsbot/bot.js:191:28)
    at welcome.do_message (/home/dave/ashtangayogacork.ie-whatsbot/welcome.js:29:13)
(node:152855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:152855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:152855) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Promise was collected
    at Promise (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:152:63)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Connection.js:151:16)
    at ExecutionContext._evaluateInternal (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/ExecutionContext.js:85:50)
    at ExecutionContext.evaluate (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/ExecutionContext.js:33:27)
    at ExecutionContext.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:95:27)
    at DOMWorld.evaluate (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:95:27)
    at Whatsapp.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:410:49)
    at step (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.stopTyping (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:408:16)
  -- ASYNC --
    at Page.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/puppeteer/lib/helper.js:94:19)
    at Whatsapp.<anonymous> (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:410:49)
    at step (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at Whatsapp.SenderLayer.stopTyping (/home/dave/ashtangayogacork.ie-whatsbot/node_modules/venom-bot/dist/api/layers/sender.layer.js:408:16)
    at do_message (/home/dave/ashtangayogacork.ie-whatsbot/bot.js:195:28)
    at welcome.do_message (/home/dave/ashtangayogacork.ie-whatsbot/welcome.js:29:13)
(node:152855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`
updating the code

**Comment by orkestral** [comment]
Hi, use Pupperteer  3.0 or remove all project and create one new
