### ISSUE TITLE
setProfilePic does not work

### ISSUE THREAD

**Issue by XNexusPrimeX** [orkestral/venom#359]
error: 
```js
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config: {
    url: './images/image1.jpg',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'arraybuffer',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: './images/image1.jpg',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: null,
      port: null,
      nativeProtocols: [Object],
      pathname: './images/image1.jpg'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET ./images/image1.jpg HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.0\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: './images/image1.jpg',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http:./images/image1.jpg',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```
```cmd
(node:8156) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property '_serialized' of undefined
    at Object.window.WAPI.setProfilePic (<anonymous>:1:26330)
    at ExecutionContext._evaluateInternal (C:\Users\User\Projetos de Nodejs\projetos de teste\projeto whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\User\Projetos de Nodejs\projetos de teste\projeto whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
code:
```js
const venom = require('venom-bot');

venom.create()
    .then((client) => start(client))
    .catch((erro) => console.log(erro));

function start(client) {
    client.setProfilePic('./images/image1.jpg');
}
```
What did I do wrong?

**Comment by edgardmessias** [comment]
Try set absolute file path

**Comment by XNexusPrimeX** [comment]
> Try set absolute file path

What? how do i do this?

**Comment by edgardmessias** [comment]
@XNexusPrimeX , could you test with #446?

**Comment by XNexusPrimeX** [comment]
> @XNexusPrimeX , could you test with #446?

it looks like it’s not working yet .. or i’m stupid and made a really silly mistake
```cmd
(node:9412) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property '_serialized' of undefined
    at Object.window.WAPI.setProfilePic (<anonymous>:1:26330)
    at ExecutionContext._evaluateInternal (C:\Users\User\Projetos de Nodejs\projetos de teste\projeto whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\User\Projetos de Nodejs\projetos de teste\projeto whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by XNexusPrimeX** [comment]
> @XNexusPrimeX , could you test with #446?

it's working

**Comment by edgardmessias** [comment]
@XNexusPrimeX , upgrade to [2.2.2](https://github.com/orkestral/venom/releases/tag/v2.2.2)

**Comment by XNexusPrimeX** [comment]
> @XNexusPrimeX , upgrade para [2.2.2](https://github.com/orkestral/venom/releases/tag/v2.2.2)
Thanks!
