### ISSUE TITLE
Erro getGroupMembersIds and getGroupMembers

### ISSUE THREAD

**Issue by leandrogmuller** [orkestral/venom#387]
I'm tryng to get getGroupMembersIds and  getGroupMembers and return error.
Try to run the same 5x, after it will return the same error.

(node:16828) UnhandledPromiseRejectionWarning: Error: Evaluation failed: n
    at ExecutionContext._evaluateInternal (c:\MyProjects\whatsapp\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (c:\MyProjects\whatsapp\whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
 <node_internals>/internal/process/warning.js
(node:16828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 <node_internals>/internal/process/warning.js
(node:16828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 <node_internals>/internal/process/warning.js
ServiceUnavailableError: Response timeout
    at IncomingMessage.<anonymous> (c:\MyProjects\whatsapp\whatsapp\node_modules\connect-timeout\index.js:84:8)
    at IncomingMessage.emit (events.js:327:22)
    at Timeout._onTimeout (c:\MyProjects\whatsapp\whatsapp\node_modules\connect-timeout\index.js:49:11)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
 node_modules/express/lib/application.js
ServiceUnavailableError: Response timeout
    at IncomingMessage.<anonymous> (c:\MyProjects\whatsapp\whatsapp\node_modules\connect-timeout\index.js:84:8)
    at IncomingMessage.emit (events.js:327:22)
    at Timeout.<anonymous> (c:\MyProjects\whatsapp\whatsapp\node_modules\connect-timeout\index.js:49:11)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
 node_modules/express/lib/application.js

**Comment by leandrogmuller** [comment]
addParticipant not working too.
