### ISSUE TITLE
Error when using addParticipant

### ISSUE THREAD

**Issue by hoseajsap** [orkestral/venom#41]
Hello i see something at the console when using addParticipant. it said that 

"Hello i see something at the console when using addParticipant. it said that 

```
Error: Evaluation failed: TypeError: n is not a function
    at myfilepath\venom-bot\dist\lib\wapi\wapi.js:1:28064
    at H (https://web.whatsapp.com/app.14adffa5e404bcc68e38.js:1:1016102)
    at MutationObserver.W (https://web.whatsapp.com/app.14adffa5e404bcc68e38.js:1:1015683)
    at ExecutionContext._evaluateInternal (myfilepath\node_modules\puppeteer\lib\ExecutionContext.js:102:19)        
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ExecutionContext.evaluate (myfilepath\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (myfilepath\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (myfilepath\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (myfilepath\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (myfilepath\node_modules\puppeteer\lib\Page.js:612:14)
    at Page.<anonymous> (myfilepath\node_modules\puppeteer\lib\helper.js:95:27)
    at Whatsapp.<anonymous> (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:162:60)
    at step (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:46:23)
    at Object.next (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:27:53)
    at myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:17:12)
    at Whatsapp.GroupLayer.addParticipant (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:159:16) 
  -- ASYNC --
    at Page.<anonymous> (myfilepath\node_modules\puppeteer\lib\helper.js:94:19)
    at Whatsapp.<anonymous> (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:162:60)
    at Whatsapp.<anonymous> (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:162:60)
    at step (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:46:23)
    at Object.next (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:27:53)
    at myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:17:12)
    at Whatsapp.GroupLayer.addParticipant (myfilepath\node_modules\venom-bot\dist\api\layers\group.layer.js:159:16) 
    at myfilepath\index.js:118:26
    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
```

and when using this function, can we check that add participant is success or not? Thanks.

**Comment by bhavya32** [comment]
@hoseajsap Code reference?

**Comment by joaosouz4** [comment]
I can't reproduce this error, if it happens again create a new issue with more information

**Comment by AlanMartines** [comment]
## Description

I am in error when using the addParticipant function, apparently with a loop and did not return the result of the action.

## Code

#### Json Insomnia
```json
{
	"SessionName": "a56ad842-c707-4446-871c-e570240cd730",
	"group":"000000000000-1618339646",
	"groupId": "@g.us",
	"phonefull": "+55(00)0 0000-0000",
	"chatId": "@c.us"
}
```

#### Route
```node
//
// ------------------------------------------------------------------------------------------------//
//
router.post("/demoteParticipant", upload.none(''), async (req, res, next) => {
  //
 // Add participant
  var sessionStatus = await Sessions.Status(req.body.SessionName);
  switch (sessionStatus.status) {
    case 'inChat':
    case 'qrReadSuccess':
    case 'isLogged':
    case 'chatsAvailable':
      //
      var sendResult = await Sessions.demoteParticipant(
        req.body.SessionName,
        req.body.group,
        req.body.groupId,
        soNumeros(req.body.phonefull),
        req.body.chatId
      );
      res.status(200).json(sendResult);
      break;
    default:
      res.status(400).json(sessionStatus);
  }
}); //demoteParticipant
//
// ------------------------------------------------------------------------------------------------//
//
```

#### Venom
```node
//
// ------------------------------------------------------------------------------------------------//
//
// Add participant
static async addParticipant(
  SessionName,
  group,
  groupId,
  phonefull,
  chatId
) {
  console.log("- addParticipant");
  var session = Sessions.getSession(SessionName);
  var resultaddParticipant = await session.client.then(async client => {
    try {
      return await client.addParticipant(group + groupId, phonefull + chatId);
    } catch (erro) {
      //console.error('Error when sending: ', erro); //return object error
      //
      return {
        "erro": true,
        "status": 404,
        "number": phonefull,
        "message": "Erro ao adicionar participante"
      };
      //
    };
  });
  return {
    "addParticipant": resultaddParticipant
  };
} //addParticipant
//
// ------------------------------------------------------------------------------------------------//
//
```

## Screenshot

#### Insomnia
![image](https://user-images.githubusercontent.com/10979090/114613912-e4df2980-9c71-11eb-90bd-32c697b0c8ce.png)

#### Log
![image](https://user-images.githubusercontent.com/10979090/114614261-4f906500-9c72-11eb-8eab-4e66e1d8ef9f.png)
