### ISSUE TITLE
cannot sendMessage

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#515]
## Description

cannot sendMessage

if I understand right error in `WAPI.sendMessage`  when do `var chat = Store.Chat.get(to);` 
in my code i have try-catch for it, but in sendMessage in webpage not

## Environment

- **Venom version(s):** 2.2.2
- **Browser:**  Chromium 85
- **OS:** Ubuntu 20.04
- **Node version:** Node 14.15.1

## Steps to Reproduce

1. run venom instance
2. wait two weeks ))
3. error

## Log Output

```
(node:25) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined
     at Object.window.WAPI.window.WAPI.sendMessage (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:34887)
     at __puppeteer_evaluation_script__:3:53
     at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_
unhandled_rejections_mode). (rejection id: 16)

```

**Comment by diogo-palma** [comment]
i have problem with Chromium too, but in Chrome venom works fine!
