### ISSUE TITLE
Always waiting when starting the Venom bot

### ISSUE THREAD

**Issue by putradongkal** [orkestral/venom#55]
I found something wrong when starting the Venom bot

`(node:7380) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\xampp\htdocs\venom-bot\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (C:\xampp\htdocs\venom-bot\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\xampp\htdocs\venom-bot\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\xampp\htdocs\venom-bot\node_modules\puppeteer\lib\helper.js:95:27)
    at Object.<anonymous> (C:\xampp\htdocs\venom-bot\node_modules\venom-bot\dist\controllers\browser.js:138:49)
    at step (C:\xampp\htdocs\venom-bot\node_modules\venom-bot\dist\controllers\browser.js:44:23)
    at Object.next (C:\xampp\htdocs\venom-bot\node_modules\venom-bot\dist\controllers\browser.js:25:53)
    at fulfilled (C:\xampp\htdocs\venom-bot\node_modules\venom-bot\dist\controllers\browser.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()
. To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (
see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje
ctions that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by orkestral** [comment]
use chrome not chromium
