### ISSUE TITLE
Venom Start Error

### ISSUE THREAD

**Issue by borellaster** [orkestral/venom#552]
I've been using this library for months, and suddenly I got this error

```
(node:3808) UnhandledPromiseRejectionWarning: RequestError: connect ETIMEDOUT 104.16.20.35:443
    at ClientRequest.<anonymous> (C:\Al.WhatsApp\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (C:\Al.WhatsApp\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![Sem título](https://user-images.githubusercontent.com/4430466/106198626-0a8c8480-6193-11eb-9e94-2f154520aa1a.png)

Any Help?

**Comment by antirek** [comment]
it's network problem. check your connection and dns. in code add reconnection
