### ISSUE TITLE
There's an problem with the function: client.getAllUnreadMessages()

### ISSUE THREAD

**Issue by tadeubarbosa** [orkestral/venom#596]
## Description
When I start my application, I run something like:
> const messages = await client.getAllUnreadMessages()

But this method is returning an error when I try to execute them.

## Environment

- **Venom version(s):** 2.2.3 and 2.2.4
- **OS:** Ubuntu 20 LTS
- **Node version:** Node 12.18.2

## Steps to Reproduce

Just calling "getAllUnreadMessages" method.

## Log Output

```js
Error: Evaluation failed: TypeError: Cannot read property 'filter' of undefined
    at s (/var/www/html/wa-node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:18810)
    at Object.window.WAPI.window.WAPI.getAllUnreadMessages (/var/www/html/wa-node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:49192)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (/var/www/html/wa-node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ExecutionContext.evaluate (/var/www/html/wa-node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at Object.onUnreadMessage (/var/www/html/wa-node/src/events/onUnreadMessage.ts:10:23)
```

**Comment by tadeubarbosa** [comment]
I happens when I updated from 2.2.3 to 2.2.4, then this error started.
I had tried to come back to 2.2.3 version, but it still getting error.

**Comment by tadeubarbosa** [comment]
So, I add these script before start the client (I found it right now in the README), and it solve the problem:

```js
client.onStreamChange((state) => {
    console.log('Connection status: ', state);
    clearTimeout(time);
    if(state === 'CONNECTED'){
     start(client);
    }
   //  DISCONNECTED when the mobile device is disconnected
    if (state === 'DISCONNECTED' || state === 'SYNCING') {
      time = setTimeout(() => {
        client.close();
       // process.exit(); //optional function if you work with only one session
      }, 80000);
    }
  })
```
