### ISSUE TITLE
Error DEBIAN9.X

### ISSUE THREAD

**Issue by contatodct** [orkestral/venom#6]
root@APOIO-DANIEL-NAO-APAGAR:~/BOT# npm start

> venom-bot@1.0.0 start /root/BOT
> npm run build:venom & tsc app.ts && node app.js

> venom-bot@1.0.0 build:venom /root/BOT
> tsc

(node:1722) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0610/202122.834338:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/BOT/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/root/BOT/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1722) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1722) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✓ Checking for updates
⠙ Creating whatsapp instace...

**Comment by orkestral** [comment]
create user in machine for used venom-bot

**Comment by edilsonlm217** [comment]
> create user in machine for use venom-bot

What do you mean by "create user in machine"
