### ISSUE TITLE
venom doesn't go out of wait

### ISSUE THREAD

**Issue by XNexusPrimeX** [orkestral/venom#60]
I liked sulla very much, probably I would also like the venom, if it worked, I already reported a problem here, and it has not been solved: [first issue](https://github.com/orkestral/venom/issues/10) 
please do not want to have to look for another api, yours is **very good**:

anyway, the bot is only in the 'waiting', and does not come out of it

```
✓ Checking for updates
⠼ 🕷🕷🕷Waiting...🕷🕷🕷
```

if I try to restart, it returns:
```
(node:8732) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setDiscoverTargets): Target closed.
    at D:\Pessoal\Projetos\Projetos nodejs\Private\bot9ano\node_modules\puppeteer\lib\Connection.js:53:63      
    at new Promise (<anonymous>)
    at Connection.send (D:\Pessoal\Projetos\Projetos nodejs\Private\bot9ano\node_modules\puppeteer\lib\Connection.js:52:16)
    at Function.create (D:\Pessoal\Projetos\Projetos nodejs\Private\bot9ano\node_modules\puppeteer\lib\Browser.js:43:26)
    at ChromeLauncher.launch (D:\Pessoal\Projetos\Projetos nodejs\Private\bot9ano\node_modules\puppeteer\lib\Launcher.js:79:53)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PuppeteerExtra.launch (D:\Pessoal\Projetos\Projetos nodejs\Private\bot9ano\node_modules\puppeteer-extra\dist\index.cjs.js:129:25)
(node:8732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
ps: my code is the basics:
```
// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom.create().then((client) => start(client));

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi') {
      client.sendText(message.from, 'Welcome Venom 🕷');
    }
  });
}

```

**Comment by hbdbim** [comment]
it seems an environmental problem because it is working normally. try to create a new node project.

**Comment by XNexusPrimeX** [comment]
I don't work 😢

**Comment by orkestral** [comment]
working normally.

**Comment by Pezhvak** [comment]
it doens't work on centos

**Comment by Pezhvak** [comment]
it doesn't work on centos
