### ISSUE TITLE
TypeError: client.getAllGroups is not a function (after update 2.2.4)

### ISSUE THREAD

**Issue by m0w4hhed** [orkestral/venom#601]
## Environment

- **Venom version(s):** 2.2.4
- **Browser:** Chrome
- **OS:** Windows 10
- **Node version:** Node 12

**Comment by clovisdanielss** [comment]
Try GetAllChatGroups [from here](https://github.com/orkestral/venom/commit/acf172ddc749ca6529f8cb32de29bb4594d802e0)

**Comment by m0w4hhed** [comment]
I've tried using this method, but the result is this:
```
Error: Evaluation failed: f
    at ExecutionContext._evaluateInternal (F:\NODE\WABOT\wobot-web\electron\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (F:\NODE\WABOT\wobot-web\electron\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
Error: Evaluation failed: f
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (F:\NODE\WABOT\wobot-web\electron\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
```

**Comment by jonalan7** [comment]
**The getAllGroups() function has been changed to GetAllChatGroups() but she is in trouble! We will fix it in the next updates.**

**Comment by m0w4hhed** [comment]
is the previous version (2.2.3) still save to use?

btw, thanks alot for the fix

**Comment by jonalan7** [comment]
**The problem was solved with a new update!**
