### ISSUE TITLE
autoClose random error

### ISSUE THREAD

**Issue by joaosouz4** [orkestral/venom#62]
![image](https://user-images.githubusercontent.com/47183663/86823655-81c9c200-c063-11ea-9899-296ddd3a8de9.png)

error when closing automatically, I created a counter and sometimes I get this puppeteer error randomly

> Error: Protocol error (Runtime.callFunctionOn): Target closed.
>     at /var/www/node_modules/puppeteer/lib/Connection.js:152:63
>     at new Promise (<anonymous>)
>     at CDPSession.send (/var/www/node_modules/puppeteer/lib/Connection.js:151:16)
>     at ExecutionContext._evaluateInternal (/var/www/node_modules/puppeteer/lib/ExecutionContext.js:85:50)
>     at ExecutionContext.evaluateHandle (/var/www/node_modules/puppeteer/lib/ExecutionContext.js:36:21)
>     at ExecutionContext.<anonymous> (/var/www/node_modules/puppeteer/lib/helper.js:95:27)
>     at WaitTask.rerun (/var/www/node_modules/puppeteer/lib/DOMWorld.js:404:71)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> Error: Protocol error (Runtime.callFunctionOn): Target closed.
>     at /var/www/node_modules/puppeteer/lib/Connection.js:152:63
>     at new Promise (<anonymous>)
>     at CDPSession.send (/var/www/node_modules/puppeteer/lib/Connection.js:151:16)
>     at ExecutionContext._evaluateInternal (/var/www/node_modules/puppeteer/lib/ExecutionContext.js:85:50)
>     at ExecutionContext.evaluateHandle (/var/www/node_modules/puppeteer/lib/ExecutionContext.js:36:21)
>     at ExecutionContext.<anonymous> (/var/www/node_modules/puppeteer/lib/helper.js:95:27)
>     at WaitTask.rerun (/var/www/node_modules/puppeteer/lib/DOMWorld.js:404:71)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> - Checking for updates
> - Auto closed!

**Comment by joaosouz4** [comment]
#79 i fix this too in PR
