### ISSUE TITLE
Problem with method client.getMessageById

### ISSUE THREAD

**Issue by tadeubarbosa** [orkestral/venom#631]
## Description

I'm having trouble when I try to get a message by message id.

## Environment

- **Venom version(s):** venom-business
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** Ubuntu 20 LTS
- **Node version:** Node 12

## Steps to Reproduce

```js
const message = await client.getMessageById(messageId)
```

## Log Output

```js
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string
     at t.default (https://web.whatsapp.com/app2.a1c0feef6c698420f1cc.js:2:1498763)
     at Function.fromString (https://web.whatsapp.com/app2.a1c0feef6c698420f1cc.js:2:743489)
     at Object.e [as getMessageById] (/var/www/html/node/comunique/node_modules/venom-business/dist/lib/wapi/wapi.js:1:17687)
     at _puppeteer_evaluation_script_:1:37
     at ExecutionContext._evaluateInternal (/var/www/html/node/comunique/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by AF1298** [comment]
same problem when send a message, 

`
Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (../node_modules/venom-bot/dist/lib/wapi/wapi.js:1:35930)
    at __puppeteer_evaluation_script__:3:53
    at ExecutionContext._evaluateInternal (../node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ExecutionContext.evaluate (../node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
`

**Comment by patrickbastos** [comment]
Mesmo problema
