### ISSUE TITLE
Reject sender.layer.js

### ISSUE THREAD

**Issue by igortrust** [orkestral/venom#641]
## Description

After a few minutes logged in, the error appears: MsgKey fromString error: str is null or not a string

## Environment

- **Venom version(s):** [3.0.0]
- **Browser:** [Chromium 85]
- **OS:** [Windows 10]
- **Node version:** [15.2.1]

node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string
    at t.default (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889667)
    at Function.fromString (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889406)
    at Object.e [as getMessageById] (D:\Projetos\servidor\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:22970)
    at __puppeteer_evaluation_script__:1:37
    at ExecutionContext._evaluateInternal (D:\Projetos\servidor\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ExecutionContext.evaluate (D:\Projetos\servidor\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)`ode:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);

**Comment by antirek** [comment]
duplicate #631 
use nightly build

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
