### ISSUE TITLE
unhandled promise rejection while number is invalid

### ISSUE THREAD

**Issue by ghifar1** [orkestral/venom#645]
## Description

give an error not readable if number is invalid, not return reason why message is not sent

## Log Output

`(node:7364) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string
    at t.default (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889667)
    at Function.fromString (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889406)
    at Object.e [as getMessageById] (D:\laragon\www\wafree\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:22970)
    at __puppeteer_evaluation_script__:1:37
    at ExecutionContext._evaluateInternal (D:\laragon\www\wafree\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
    at async ExecutionContext.evaluate (D:\laragon\www\wafree\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)`

**Comment by antirek** [comment]
duplicate #631 
use nightly build

**Comment by ghifar1** [comment]
@antirek thank you for advice
