### ISSUE TITLE
error: get messageId after send message to non contact 

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#650]
## Description

I send message to number not from my contact list, message was sent and in console error

client.sendText(chatId, message)

(node:19) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
     at Function.assign (<anonymous>)
     at Object.window.WAPI.window.WAPI.getchatId (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:28437)
     at async Object.window.WAPI.window.WAPI.sendMessage (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:36871)
     at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

## Environment

- **Venom version(s):** [3.0.1]
- **Browser:** [Chromium 85]
- **OS:** [Ubuntu 20.04]
- **Node version:** [ Node 14]

**Comment by techwebsolucao** [comment]
aqui tambem

**Comment by miguelarcjr** [comment]
Same issue

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
