### ISSUE TITLE
MsgKey error on 3.0.5, the same code works before 3.0.0 release

### ISSUE THREAD

**Issue by WhitespaceQ** [orkestral/venom#656]
## Description

I'm using venom to automatically report HomeAssistant log to my phone, however, after 3.0.0 my code suddenly won't work. Sometimes venom can send one or two messages but after that, I'm faced with an error log that I've attached below. This issue also persists in the nightly release.

## Environment

- **Venom version(s):** 3.0.5

## Log Output

```
Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string
    at t.default (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889667)
    at Function.fromString (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889406)
    at Object.e [as getMessageById] (/home/secure/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:23009)
    at __puppeteer_evaluation_script__:1:37
    at ExecutionContext._evaluateInternal (/home/secure/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by NiedsonEmanoel** [comment]
Same here

**Comment by miguelarcjr** [comment]
Same issue

**Comment by patrickbastos** [comment]
Same issue

**Comment by carlinhosarena** [comment]
Same issue

**Comment by orkestral** [comment]
we performed tests on several OS and we did not detect any problem please before opening an issue perform tests in your environment such as deleting folder node_modules and package.json.lock and then an npm install

**Comment by NiedsonEmanoel** [comment]
This error only pops up when i try use client.sendText
