### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by textarea** [orkestral/venom#659]
## Environment

- **Venom version(s):** 3.0.4
- **OS:** Linux Debian 10
- **Node version:** Node 15

## Log Output

Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
at Function.assign (<anonymous>)
at Object.window.WAPI.window.WAPI.getchatId (/var/www/wa-gateway/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:28461)
at async Object.window.WAPI.window.WAPI.sendMessage (/var/www/wa-gateway/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:36895)
at ExecutionContext._evaluateInternal (/var/www/wa-gateway/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async ExecutionContext.evaluate (/var/www/wa-gateway/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by orkestral** [comment]
Please use version 3.0.5

**Comment by JuanCasian** [comment]
I had the same error and I am running version 3.0.5 here is the log output:

```
(node:17052) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Object.window.WAPI.window.WAPI.getchatId (C:\Users\rogel\Downloads\whatsBot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:28461)
    at async Object.window.WAPI.window.WAPI.sendMessage (C:\Users\rogel\Downloads\whatsBot\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:36895)
    at ExecutionContext._evaluateInternal (C:\Users\rogel\Downloads\whatsBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\rogel\Downloads\whatsBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:17052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
