### ISSUE TITLE
ReferenceError: Store is not defined

### ISSUE THREAD

**Issue by textarea** [orkestral/venom#660]
## Environment

- **Venom version(s):** 3.0.4
- **OS:** Linux Debian 10
- **Node version:** Node 15

## Log Output

Evaluation failed: ReferenceError: Store is not defined
at __puppeteer_evaluation_script__:3:29
at ExecutionContext._evaluateInternal (/var/www/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async ExecutionContext.evaluate (/var/www/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by orkestral** [comment]
please use new version 3.0.5
