### ISSUE TITLE
DeprecationWarning (again)

### ISSUE THREAD

**Issue by textarea** [orkestral/venom#661]
## Description

Same as #615 but no more logout() call, no code on statusFind callback

## Environment

- **Venom version(s):** 3.0.4
- **OS:** Linux Debian 10
- **Node version:** Node 15

## Log Output

(node:2063) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will throw if path does not exist or is a file. Use fs.rm(path, { recursive: true, force: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
[2021-02-27 02:18:37] [WARN]   process warning DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will throw if path does not exist or is a file. Use fs.rm(path, { recursive: true, force: true }) instead
    at emitPermissiveRmdirWarning (node:internal/fs/utils:762:13)
    at __node_internal_ (node:internal/fs/utils:741:7)
    at Object.rmdirSync (node:fs:911:15)
    at Plugin.deleteUserDataDir (/var/www/wa-gateway/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
    at Plugin.onClose (/var/www/wa-gateway/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
    at /var/www/wa-gateway/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/var/www/wa-gateway/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Browser.emit (/var/www/wa-gateway/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /var/www/wa-gateway/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:85:94

**Comment by orkestral** [comment]
Please use version 3.0.5
