### ISSUE TITLE
error: get messageId after send message to non contact 

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#663]
copy #650 

I test on venom-bot@3.0.5 and same problem. It's "First write" don't return messageId. After first message contact added to contacts and next messages was sent successful. 

If I right think it's problem here ??https://github.com/orkestral/venom/blob/29aa07959ad32402366f97e4867532d057304f3c/src/lib/wapi/functions/check-send-exist.js#L76 

Usually when we send message to exist chat in sendMessage, but when chat not in chat list we go by 'else' condition
https://github.com/orkestral/venom/blob/29aa07959ad32402366f97e4867532d057304f3c/src/lib/wapi/functions/send-message.js#L76

## Description

I send message to number not from my contact list, message was sent and in console error   

 (node:18) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
     at Function.assign (<anonymous>)
     at Object.window.WAPI.window.WAPI.getchatId (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:28461)
     at async Object.window.WAPI.window.WAPI.sendMessage (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:36895)
     at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

## Environment

- **Venom version(s):** [3.0.5]
- **Browser:** [Chromium 85]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by JuanCasian** [comment]
+1 - Just wan't to add that we are having the same issue :)

**Comment by orkestral** [comment]
resolved in version 3.0.6

**Comment by antirek** [comment]
@orkestral @jonalan7  thanks!
