### ISSUE TITLE
Not working on my server hosting with cpanel

### ISSUE THREAD

**Issue by ArmyNicolasG** [orkestral/venom#668]
Im trying to upload the bot to my server hosting, using nodejs app and cPanel controller, but shows me this error:

Chrome not found, using chromium
TypeError: browser.on is not a function
    at Object.<anonymous> (.../whatsappBotN1/10/lib/node_modules/venom-bot/dist/controllers/initializer.js:199:29)
    at step (.../whatsappBotN1/10/lib/node_modules/venom-bot/dist/controllers/initializer.js:44:23)
    at Object.next (.../whatsappBotN1/10/lib/node_modules/venom-bot/dist/controllers/initializer.js:25:53)
    at fulfilled (.../whatsappBotN1/10/lib/node_modules/venom-bot/dist/controllers/initializer.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
stderr:
npm WARN lifecycle The node binary used for scripts is .../whatsappBotN1/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
Unable to load the sleep module (no animations available)
- Checking for updates
- Checking for updates...
- You're up to date
- You're up to date_

The code worked well on my pc with windows 10, but isn't working on my server hosting, i already downloaded node_modules there and my file and package.json... thank you

**Comment by orkestral** [comment]
not recomended use of cpanel for venom-bot run
