### ISSUE TITLE
Erro ao baixar arquivo.

### ISSUE THREAD

**Issue by kingaspx** [orkestral/venom#69]
Opa, to tentando baixar um arquivo mas não tô conseguindo. Código:

```javascript
const buffer = await client.downloadFile(message)
    const fileName = `foto-.${mime.extension(message.mimetype)}`;
    fs.writeFile(fileName, buffer, function (err) {
    });
```

Erro:

```
 [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined   
    at Function.from (buffer.js:305:9)
    at expandDerivation (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\helpers\decrypt.js:106:33)
    at generateFile (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\helpers\decrypt.js:82:30)
    at Object.decrypt (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\helpers\decrypt.js:70:16)
    at Whatsapp.<anonymous> (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\whatsapp.js:144:57)
    at step (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\whatsapp.js:46:23)
    at Object.next (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\whatsapp.js:27:53)
    at fulfilled (C:\Users\Abner\NodeProjects\Whatsapp\git\WhatsappServer\node_modules\venom-bot\dist\api\whatsapp.js:18:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:13420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was 
not handled with .catch(). (rejection id: 2)
```

![image](https://user-images.githubusercontent.com/40338524/87610490-d6acae80-c6db-11ea-9be7-8159669a7aea.png)

**Comment by orkestral** [comment]
simple, 

` const options = {
					  url: url,
					  dest: "documentos/"+url.split("uploads/")[1] // Save to /path/to/dest/image.jpg
					}
					 
				   await download.image(options)
					  .then(({ filename, image }) => {
						console.log("Saved to", filename)  // Saved to /path/to/dest/image.jpg
					  })
					  .catch((err) => console.error(err))
				  await client.sendImage(
					  from,
					  path.basename("/documentos")+"/"+url.split("uploads/")[1],
					  url,
					  msg
					);`

**Comment by orkestral** [comment]
` const options = {
					  url: url,
					  dest: "documentos/"+url.split("uploads/")[1] // Save to /path/to/dest/image.jpg
					}
					 
				   await download.image(options)
					  .then(({ filename, image }) => {
						console.log("Saved to", filename)  // Saved to /path/to/dest/image.jpg
					  })
					  .catch((err) => console.error(err))`

**Comment by orkestral** [comment]
```javascript
import fs = require('fs');
import mime = require('mime-types');

client.onMessage(async (message) => {
  if (message.isMedia) {
    const buffer = await client.downloadFile(message);
    // At this point you can do whatever you want with the buffer
    // Most likely you want to write it into a file
    const fileName = `some-file-name.${mime.extension(message.mimetype)}`;
    fs.writeFile(fileName, buffer, function (err) {
      ...
    });
  }
});
```
