### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by textarea** [orkestral/venom#710]
## Description

In multiple Venom sessions use, sometimes, not always, I'm getting the following error, I suppose immediately after starting client.

## Environment

- **Venom version(s):** 3.0.8
- **OS:** Debian 10
- **Node version:** Node 15

## Log Output

Error: Evaluation failed: TypeError: Cannot read property 'attributes' of undefined
at Object.window.WAPI.window.WAPI.getHost (/var/www/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:57912)
at __puppeteer_evaluation_script__:1:28
at ExecutionContext._evaluateInternal (/var/www/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async ExecutionContext.evaluate (/var/www/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by textarea** [comment]
Maybe in getHostDevice, but I'm not sure

**Comment by jonalan7** [comment]
I am unable to receive this error! Try using a newer version, if it doesn't work, share your script!

**Comment by textarea** [comment]
I will check
