### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by textarea** [orkestral/venom#711]
## Description

Sometimes getting the following error in errors log. Don't know how to reproduce.

## Environment

- **Venom version(s):** 3.0.8
- **OS:** Debian 10
- **Node version:** Node 15

## Log Output

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:329:5)
at validateString (node:internal/validators:129:11)
at Object.extname (node:path:1273:5)
at Object.filenameFromMimeType (/var/www/node_modules/venom-bot/dist/api/helpers/filename-from-mimetype.js:61:34)
at Whatsapp.<anonymous> (/var/www/node_modules/venom-bot/dist/api/layers/sender.layer.js:301:73)
at step (/var/www/node_modules/venom-bot/dist/api/layers/sender.layer.js:48:23)
at Object.next (/var/ww/node_modules/venom-bot/dist/api/layers/sender.layer.js:29:53)
at /var/www/node_modules/venom-bot/dist/api/layers/sender.layer.js:23:71
at new Promise (<anonymous>)
at __awaiter (/var/www/node_modules/venom-bot/dist/api/layers/sender.layer.js:19:12)

**Comment by jonalan7** [comment]
**Which function is giving this error? Could you give more details of your problem?**

**Comment by textarea** [comment]
Sorry, I don't have now more details, It could be in sendImageFromBase64 also for me
