### ISSUE TITLE
Error: Evaluation failed: TypeError: e.match is not a function

### ISSUE THREAD

**Issue by claudioscarpafilho** [orkestral/venom#715]
## Description

Venom-Bot 3.0.9

When I try to send a text message to a whatsapp number that is not in my contact list I am getting the error:
It´s only for contacts that is not in my contact list. And only with 3.0.9. 

Error: Evaluation failed: TypeError: e.match is not a function

at Object.window.WAPI.window.WAPI.getNewMessageId (\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:57115)
at async Object.window.WAPI.window.WAPI.sendMessage (\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:37297)

## Environment

- **Venom version(s):** 3.0.9
- **OS:** Windows 10 
- **Chrome:** 89.0.4389.82 (Official Build) (64-bit)
- **Node version:** v14.15.0

**Comment by claudioscarpafilho** [comment]
Sorry. I install venom-bot again and now there´s no problem.
