### ISSUE TITLE
sendMessage error

### ISSUE THREAD

**Issue by xzvcit** [orkestral/venom#724]
When I first send message: 

```
(node:67) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.match is not a function
    at new l (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1052938)
    at new s (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1057160)
    at Object.window.WAPI.window.WAPI.getNewMessageId (/var/www/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:57115)
    at async Object.window.WAPI.window.WAPI.sendMessage (/var/www/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:37297)
    at ExecutionContext._evaluateInternal (/var/www/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/var/www/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:67) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:67) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Docker: buildkite/puppeteer:7.1.0

**Comment by jonalan7** [comment]
#718
