### ISSUE TITLE
UnhandledPromiseRejectionWarning error on "sendText" to a non-existent Whatsapp contact.

### ISSUE THREAD

**Issue by mf8s** [orkestral/venom#725]
## Description

I send an image and a text to a non-existent Whatsapp contact. The image was sent, but I got an UnhandledPromiseRejectionWarning error on "sendText".
Ok... It's a invalid number... but I have 1600+ contacts to "sendText". So, some of them will be non-existent as Whatsapp contact.

## Environment

- **Venom version(s):** 3.0.9
- **Browser:** Chromium 88
- **OS:** Windows 10 x64
- **Node version:** 14

## Steps to Reproduce

My code:
```
const fs = require('fs');
const venom = require('venom-bot');

venom
  .create(
    'WAppWeb',
    (base64Qr, asciiQR, attempts, urlCode) => {
      console.log(asciiQR); // Optional to log the QR in the terminal
      var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
        response = {};

      if (matches.length !== 3) {
        return new Error('Invalid input string');
      }
      response.type = matches[1];
      response.data = new Buffer.from(matches[2], 'base64');

      var imageBuffer = response;
      fs.writeFile(
        'qrCode.png',
        imageBuffer['data'],
        'binary',
        function (err) {
          if (err != null) {
            console.log(err);
          }
        }
      );
    },
    undefined,
    { logQR: false }
)
.then((client) => {
start(client);
})
.catch((erro) => {
console.log(erro);
});

async function start(client) {
     
    await client
      .sendImage(
        '55219@c.us',
        './src/img1.jpeg',
        //'image-name',
        //'Caption text'
      )
      .then((result) => {
        console.log('Result: ', result); //return object success
      })
      .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
      });
    await client
      .sendText(
        `55219@c.us`,
        'Hello!'
      )
      .then((result) => {
      console.log('Result: ', result); //return object success
      })
      .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
      });
    
};
```
## Log Output

Console:
Image sent:
```
(...)
erro: false,
status: 'OK',
type: 'sendImage',
filename: 'img1.jpeg',
mimeType: 'image/jpeg'
}
```
Error:
```
(node:11344) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.match is not a function
    at new l (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1052938)
    at new s (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1057160)
    at Object.window.WAPI.window.WAPI.getNewMessageId (*path*\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:57115)
    at async Object.window.WAPI.window.WAPI.sendMessage (*path*\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:37297)
    at ExecutionContext._evaluateInternal (*path*\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (*path*\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:11344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jonalan7** [comment]
#718
