### ISSUE TITLE
sendSeen doesn't work properly

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#734]
## Description

do sendSeen -> get error
do sendSeen again -> no error

## Environment

- **Venom version(s):** [3.0.9]
- **Browser:** [Chromium]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

## Log Output

```
Error: Evaluation failed: TypeError: e.getLastMsgKeyForAction is not a function
at M (https://web.whatsapp.com/bootstrap_main.ef6b5ea9cb55cc0c4253.js:2:38761)
at Object.y [as sendSeen] (https://web.whatsapp.com/bootstrap_main.ef6b5ea9cb55cc0c4253.js:2:36213)
at Object.window.WAPI.window.WAPI.sendSeen (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:38226)
at __puppeteer_evaluation_script__:1:34
at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
at async /usr/src/app/routes/index.js:42:17

**Comment by jonalan7** [comment]
Mano you are passing a number that does not exist! Then the error is generated! 
try sending for example to this number: "55193@c.us"

**Comment by jonalan7** [comment]
**I'll fix the problem!**

**Comment by antirek** [comment]
No, before sendSeen I checked number by checkNumberStatus and if status = 200 then do sendSeen 

I tested new code - all right! )))
