### ISSUE TITLE
Bug while send to specific number

### ISSUE THREAD

**Issue by cristianormoraes** [orkestral/venom#737]
While I send msg to this specific number +5534988391839

Something happens:

```
(node:21440) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.match is not a function
    at new l (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1052938)
    at new s (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1057160)
    at Object.window.WAPI.window.WAPI.getNewMessageId (/var/www/zap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:57112)
    at async Object.window.WAPI.window.WAPI.sendMessage (/var/www/zap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:37294)
    at ExecutionContext._evaluateInternal (/var/www/zap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:21440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by antirek** [comment]
what version of venom?

**Comment by cristianormoraes** [comment]
venom-bot-3.0.10

**Comment by antirek** [comment]
it's like #735

try use nightly version
