### ISSUE TITLE
decryptFile old messages  "Error trying to download the file." 404

### ISSUE THREAD

**Issue by best-tech** [orkestral/venom#774]
i try download image from old message using loadAndGetAllMessagesInChat

`Error: Request failed with status code 404
    at createError (node_modules\axios\lib\core\createError.js:16:15)
    at settle (node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'access-control-expose-headers': 'X-WA-Metadata',
      'access-control-allow-origin': '*',
      pragma: 'no-cache',
`

[there a see](https://docs.openwa.dev/pages/How%20to/decrypt-media.html)

`You may sometimes get a 404 error when trying to decrypt media from an old message, this is because media is only available on the main servers for a limited period of time. In these circumstances, you will need to force the host account to reupload media. You can do this by using forceStaleMediaUpdate then using decryptMedia on the response.

      const mediaData = await decryptMedia(client.forceStaleMediaUpdate(message.id));
`

how to download old file?

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem
