### ISSUE TITLE
Can't start venom with chromium

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#807]
## Description

Can't start venom instance with chromium, see log
If change chromium to chrome - start ok.

## Environment

- **Venom version(s):** [3.0.12]
- **Browser:** [Chromium 88]
- **OS:** [ubuntu 20.04]
- **Node version:** [Node 14]

## Log Output

```
- headless option is active, browser hidden
error on create Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:261:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:215:61)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

```

**Comment by antirek** [comment]
test venom 3.0.13 with same options and chromium - and it start ok!

**Comment by ViniciusGoiania** [comment]
Still getting the same problem here, even with chrome.

### **Environment**
#
**Venom version(s)**: [3.0.13]
**Browser:** [Chromium 88]
**OS**: [Windows 10 Pro 2004]
**Node version**: [Node 14.16.0]

**Comment by rlucredio** [comment]
I also have the problem, with me it happens when i logout the phone.

Venom version: 3.0.16

**Comment by developerdevice** [comment]
> I also have the problem, with me it happens when i logout the phone.
> 
> Venom version: 3.0.16

Same here, how do you solved it?
