### ISSUE TITLE
Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by Foxythefox2020** [orkestral/venom#808]
## Description

Guys i can't start my bots with venom

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** Chromium 85
- **OS:** Linux Mint 20
- **Node version:** 13.14.0

1. I downloaded a bot in github
2. I installed the modules
3. I started the bot

## Log Output

info:     [client] Auto close configured to 60s
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at Object.window.WAPI.window.WAPI.restartService (/home/foxythefox/Programacao/JS/Venom-Tests/venzoir/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:57963)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (/home/foxythefox/Programacao/JS/Venom-Tests/venzoir/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/foxythefox/Programacao/JS/Venom-Tests/venzoir/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

```
const { create, Client } = require('venom-bot')
const fs = require('fs')
const options = require('./options')

//Autosave by Nurutomo
require('./noir.js')
nocache('./noir.js', module => console.log(`'${module}' Updated!`))

const start = async (noir = new Client()) => {

        noir.onAnyMessage((async (message) => {
        require('./noir.js')(noir, message)

        }))
}

function nocache(module, cb = () => { }) {
    console.log('Module', `'${module}'`, 'is now being watched for changes')
    fs.watchFile(require.resolve(module), async () => {
        await uncache(require.resolve(module))
        cb(module)
    })
}

function uncache(module = '.') {
    return new Promise((resolve, reject) => {
        try {
            delete require.cache[require.resolve(module)]
            resolve()
        } catch (e) {
            reject(e)
        }
    })
}

create(options(true, start))
    .then(noir => start(noir))
    .catch((error) => console.log(error))
```

**Comment by GabrielBels** [comment]
Same problem here
