### ISSUE TITLE
Venom is getting closed after a while

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#840]
## Description

I realized that Venom stops working after a while; it's generated the message 

> Session closed. Most likely the page has been closed.

## Environment

- **Venom version(s):** 3.14
- **Browser:** Chrome 88
- **OS:** Debian 9 Stetch

## Steps to Reproduce

1. Run Venom
2. Read QRcode
3. Wait a time (6-12 hours) and the bug happens

## Log Output

```
0|index    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|index    | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|index    |     at CDPSession.send (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|index    |     at ExecutionContext._evaluateInternal (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|index    |     at ExecutionContext.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|index    |     at DOMWorld.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|index    |     at runMicrotasks (<anonymous>)
0|index    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|index    | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|index    |     at CDPSession.send (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|index    |     at ExecutionContext._evaluateInternal (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|index    |     at ExecutionContext.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|index    |     at DOMWorld.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|index    |     at runMicrotasks (<anonymous>)
0|index    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by rafaelbellintani** [comment]
In my system, the venom is working almost 1 week, until now is everything working fine. Maybe is something in the code that causes the error, or an specific function.

**Comment by developerdevice** [comment]
> In my system, the venom is working almost 1 week, until now is everything working fine. Maybe is something in the code that causes the error, or an specific function.

I think it's because the Venom keeps trying to generate qrcode even if I set refreshQR to 0. Today i've seen "4000 Attemps", do you know why?

**Comment by firat125** [comment]
have gotten the same error. maybe you can force venom to restart every 4 hours?
