### ISSUE TITLE
Group invite link: GROUP_JID: invalid jid type: Not an instance of WID

### ISSUE THREAD

**Issue by gio-rotta** [orkestral/venom#906]
## Description
Starting yesterday, May 19, i can't create group invite link anymore. Even in the most simple case scenario.

`console.log(await client.getGroupInviteLink('5548xxxx0015-1620391555@g.us'));`

## Environment

- **Venom version(s):** "3.0.13"
- **OS:** Ubuntu
- **Node version:** Node 12

## Steps to Reproduce

1. `console.log(await client.getGroupInviteLink('5548xxxx0015-1620391555@g.us'));`

## Log Output

```
Error: Evaluation failed: Error: GROUP_JID: invalid jid type: Not an instance of WID
    at t.GROUP_JID (https://web.whatsapp.com/bootstrap_qr.3ee97e011a14353fd537.js:1:551992)
    at Object.t.queryGroupInviteCode (https://web.whatsapp.com/bootstrap_main.61ccbd302106e7080867.js:2:23304)
    at Object.window.WAPI.window.WAPI.getGroupInviteLink (/home/giovanni/Development/dropsmart/comunidade-dropsmart/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:34343)
    at __puppeteer_evaluation_script__:1:34
    at ExecutionContext._evaluateInternal (/home/giovanni/Development/dropsmart/comunidade-dropsmart/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/giovanni/Development/dropsmart/comunidade-dropsmart/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```

**Comment by mono424** [comment]
+1 getting the same issue with version `3.0.16`.

**Comment by sebastianserna30** [comment]
I'm using version 3.0.16 and I'm also experiencing this issue.

**Comment by jonalan7** [comment]
Update to the new version! This issue has been fixed! @sebastianserna30
