### ISSUE TITLE
Cannot read property 'createWid'

### ISSUE THREAD

**Issue by Daniel-Boll** [orkestral/venom#934]
## Description

When trying to send a message I keep getting this error. Tried with both Chrome and chromium.

First I thought it would be the `--user-agent` flag, but it wasn't.

## Environment

- **Venom version(s):** ^3.0.17
- **Browser:** Chrome 91
- **OS:** Arch Linux. Kernel 5.12.7-arch1-1
- **Node version:** 16.2.0

## Steps to Reproduce

1. Run the build command: `yarn build`.
2. Read de QRCode on console.
3. Receive any message

## Log Output

```sh
throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'createWid' of undefined
    at Object.window.WAPI.window.WAPI.checkNumberStatus (/home/daniel/dev/Kivy/kivy-typescript-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:64760)
    at Object.window.WAPI.window.WAPI.sendExist (/home/daniel/dev/Kivy/kivy-typescript-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:29715)
    at Object.window.WAPI.window.WAPI.sendMessage (/home/daniel/dev/Kivy/kivy-typescript-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:38155)
    at __puppeteer_evaluation_script__:3:57
    at ExecutionContext._evaluateInternal (/home/daniel/dev/Kivy/kivy-typescript-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/daniel/dev/Kivy/kivy-typescript-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Your Code

```ts
// src/app.ts

import express from 'express';
import cors, { CorsOptions } from 'cors';

import * as fs from 'fs';
import * as venom from 'venom-bot';

const app = express();

const options: CorsOptions = {
  origin: process.env.API_URL,
};

app.use(cors(options));
app.use(express.json());

app.get('/', (req, res) => {
  const start = (client: venom.Whatsapp): any => {
    client.onMessage((message) => {
      console.log(message.body);
      client.sendText(message.from, 'Answer from Venom');
    });
  };

  venom
    .create(
      'test',
      (base64Qr, asciiQR): any => {
        console.log(asciiQR); // Optional to log the QR in the terminal
        const matches = base64Qr.match(/^data:([A-Za-z-+/]+);base64,(.+)$/);
        const response: any = {};

        if (matches?.length !== 3) {
          return new Error('Invalid input string');
        }

        [response.type] = matches;
        response.data = Buffer.from(matches[2], 'base64');

        const imageBuffer: any = response;

        fs.writeFile('out.png', imageBuffer.data, 'binary', (err) => {
          if (err != null) {
            console.log(err);
          }
        });

        return true;
      },
      undefined,
      {
        disableWelcome: true,
        useChrome: true,
        logQR: false,
        browserArgs: ['--user-agent'],
      },
    )
    .then((client) => start(client));
});

const port = 3000;
app.listen(port, () => console.log(`⚡️[server]: Server is running at https://localhost:${port}`));
```

**Comment by rudacs** [comment]
Make a console.log in the message.from and put it here please.

**Comment by bhavya32** [comment]
@rudacs it occurs when sending also.

**Comment by Daniel-Boll** [comment]
Well, I tested the code again and it didn't present any problem, so strange. It just worked now.

**Comment by ykose1982** [comment]
Same issue here today.
