### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ujjawalchauhan13** [orkestral/venom#952]
## Description

Running a simple sendText program. It's suggesting that the number doesn't exist for a perfectly valid number! Throws me a error with chat.NumberExists as canReceiveMessage being returned false and then match undefined.

## Environment

- **Venom version(s):** 3.0.17
- **Browser:** Chrome v91.0.4472.77
- **OS:** MacOS Mojave
- **Node version:** Node 10.21.0

## Input Code

```
const venom = require('venom-bot');

async function asyncCall(client) {
	try {
		number = '971553194565';
		const chat = await client.checkNumberStatus(`${number}@c.us`);
		console.log('chat here', chat);
		await client
			.sendText('971553194565@c.us', '👋 Hello from Venom!')
			.then((result) => {
				console.log('Result: ', result); //return object success
			})
			.catch((erro) => {
				console.error('Error when sending: ', erro); //return object error
			});
	} catch (err) {
		throw err;
	}
}

async function start() {
	const client = await venom
		.create('session')
		.then((client) => {
			return client;
		})
		.catch((error) => console.info(error));
	asyncCall(client);
}

start();

```

## Log Output

```
chat here { id:
   { server: 'c.us',
     user: '971553194565',
     _serialized: '971553194565@c.us' },
  status: {},
  isBusiness: false,
  canReceiveMessage: false }
(node:84599) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'match' of undefined
    at new l (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:24974)
    at new o (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:29593)
    at Object.window.WAPI.window.WAPI.checkNumberStatus (/Users/ujjawalchauhan/Dropbox/mywasender/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:64732)
    at Object.window.WAPI.window.WAPI.sendExist (/Users/ujjawalchauhan/Dropbox/mywasender/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:29715)
    at Object.window.WAPI.window.WAPI.getNewMessageId (/Users/ujjawalchauhan/Dropbox/mywasender/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:59842)
    at Object.window.WAPI.window.WAPI.sendMessage (/Users/ujjawalchauhan/Dropbox/mywasender/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:38242)
    at ExecutionContext._evaluateInternal (/Users/ujjawalchauhan/Dropbox/mywasender/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:84599) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84599) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by antirek** [comment]
same error too

**Comment by KreisonReis** [comment]
same error too

**Comment by ajmariduena** [comment]
Hi we are facing the same issue, any updates on this?

**Comment by ujjawalchauhan13** [comment]
@ajmariduena @KreisonReis @antirek : This bug is already fixed now in the master branch, but they haven't launched the new npm update yet.

**Comment by jalonsoDev** [comment]
Cool, i will wait new npm update

**Comment by lucianodltec** [comment]
Hi guys, facing same here... that's a really priority issue... any possible workaround? 
@ujjawalchauhan13 which commit fixed this? I might work on a fork...

**Comment by cristianormoraes** [comment]
same here

**Comment by BrunoSette** [comment]
> Hi guys, facing same here... that's a really priority issue... any possible workaround?
> @ujjawalchauhan13 which commit fixed this? I might work on a fork...

I think the commit 1e5e2a6 fixed it.

**Comment by renatosistemasvc** [comment]
is already available on npm?

**Comment by BrunoSette** [comment]
Yes, they updated in NPM and the bug is fixed.

**Comment by matibjolivera** [comment]
> > > Hi guys, facing same here... that's a really priority issue... any possible workaround?
> > > @ujjawalchauhan13 which commit fixed this? I might work on a fork...
> > 
> > 
> > I think the commit [1e5e2a6](https://github.com/orkestral/venom/commit/1e5e2a67f5f4b92537946da2aeb58f208dce59f6) fixed it.
> 
> Na verdade não corrigiu, estamos com o mesmo problema, porém ocorre as vezes apenas e em alguns clientes especificos

npm update fix the problem

**Comment by jonalan7** [comment]
**Problem fixed!**
