### ISSUE TITLE
Can't create a new group

### ISSUE THREAD

**Issue by benzaked** [orkestral/venom#954]
## Description

Can't create new groups 

## Steps to Reproduce
I'm trying to create a new group and getting false in the return results with the latest version of Venom. 
I also tried to use a docker image with version 0.16 of Venom what was worked before. 
And I got the same result. 

My code: 
```
const venom = require('venom-bot');

venom
  .create()
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
    client.createGroup('Group name', [
        '*********@c.us',
      ]).then((result) => {
        console.log('Result: ', result); //return object success
      })
      .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
      });
  
}
```

## Logs:
```
Error occured while creating a group test ***@c.us Error: Evaluation failed: TypeError: window.Store.WapQuery.createGroup is not a function at Object.window.WAPI.window.WAPI.createGroup (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33745)
at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```
Does anyone have some advice? 

Thanks!

**Comment by jonalan7** [comment]
**When using the function, are you clearing both messages? Is that what's happening?**

**Comment by jonalan7** [comment]
Update to the latest version! This function has already been fixed!
