### ISSUE TITLE
I can't send any text message out of my chat's list

### ISSUE THREAD

**Issue by nonna2010** [orkestral/venom#956]
(node:25506) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'match' of undefined
    at new l (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:24974)
    at new o (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:29593)
    at Object.window.WAPI.window.WAPI.checkNumberStatus (/home/public_html/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:64732)
    at Object.window.WAPI.window.WAPI.sendExist (/home/public_html/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:29715)
    at Object.window.WAPI.window.WAPI.getNewMessageId (/home/public_html/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:59842)
    at Object.window.WAPI.window.WAPI.sendMessage (/home/public_html/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:38242)
    at ExecutionContext._evaluateInternal (/home/public_html/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/public_html/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(node:25506) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)

**Comment by antirek** [comment]
duplicate #952
