### ISSUE TITLE
TypeError: Cannot read property 'erro' of undefined

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#957]
> 0|index  | TypeError: Cannot read property 'erro' of undefined
> 0|index  |     at Whatsapp.<anonymous> (/root/app/node/node_modules/venom-bot/dist/api/layers/sender.layer.js:164:47)
> 0|index  |     at step (/root/app/node/node_modules/venom-bot/dist/api/layers/sender.layer.js:48:23)
> 0|index  |     at Object.next (/root/app/node/node_modules/venom-bot/dist/api/layers/sender.layer.js:29:53)
> 0|index  |     at fulfilled (/root/app/node/node_modules/venom-bot/dist/api/layers/sender.layer.js:20:58)
> 0|index  |     at process._tickCallback (internal/process/next_tick.js:68:7)

## Environment

- **Venom version(s):** [3.0.17,3.0.18]
- **Browser:** [Chrome 88]

## Additional context / Screenshot

Code: `const response = await clientsArray[session].sendText(phone + "@c.us", msg);`

![image](https://user-images.githubusercontent.com/24875140/120897892-cf95d400-c5fe-11eb-850c-1f3cff40f495.png)

**Comment by developerdevice** [comment]
I had to remove `await` to keep working.
