### ISSUE TITLE
InvalidMediaFileType error while sending a video

### ISSUE THREAD

**Issue by gonmartinez** [orkestral/venom#958]
## Description

An InvalidMediaFileType error is thrown while trying to send a video using the sendFile method.

## Environment

- **Venom version(s):** 3.0.18
- **Browser:** Chromium r818858
- **OS:** Ubuntu 20.04
- **Node version:** 14.17.0

## Steps to Reproduce

1. Upload an mp4 to a directory
2. Create venom client and send the MP4 file using the sendFile method
```
venom
  .create(
    {
        useChrome: false,
        browserArgs: ['--no-sandbox']
    }
  )
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
    client
    .sendFile(
      'xxxxxxxxxxxxx@c.us',
      'uploads/test.mp4',
      'test.mp4',
      'Video'
    )
    .then((result) => {
      console.log('Result: ', result);
    })
    .catch((erro) => {
      console.error('Error when sending: ', erro);
    });
}
```

## Log Output

```
(node:1420) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: InvalidMediaFileType
    at Object.sendToChat (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:16:165189)
    at Object.u [as sendFile] (/home/testVenom/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:24622)
    at ExecutionContext._evaluateInternal (/home/testVenom/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/testVenom/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by antirek** [comment]
Maybe non-valid codec or format? try convert to other format and send again.

**Comment by antirek** [comment]
I saw same problem (InvalidMediaFileSize) when send empty txt file (0 bytes)  ;))

**Comment by gonmartinez** [comment]
Sending an empty txt returns this other error MediaFileEmpty. I tried different codecs and i downloaded videos from whatsapp to test it but i'm still getting the same error.

The video im testing is a video/mp4 here is more info about it

```
General
Complete name                            : ./uploads/test.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/mp41/isom/avc1)
File size                                : 1.50 MiB
Duration                                 : 30 s 527 ms
Overall bit rate                         : 411 kb/s
Encoded date                             : UTC 2015-08-07 09:13:02
Tagged date                              : UTC 2015-08-07 09:13:02

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3
Format settings                          : 3 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 3 frames
Format settings, GOP                     : M=1, N=90
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 30 s 33 ms
Bit rate                                 : 300 kb/s
Width                                    : 480 pixels
Height                                   : 270 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.077
Stream size                              : 1.08 MiB (72%)
Writing library                          : x264 core 146 r11M 121396c
Encoding settings                        : cabac=0 / ref=3 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=48 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=infinite / keyint_min=30 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=300 / ratetol=1.0 / qcomp=0.60 / qpmin=5 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=330 / vbv_bufsize=360 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2015-08-07 09:13:02
Tagged date                              : UTC 2015-08-07 09:13:02
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 30 s 527 ms
Bit rate mode                            : Constant
Bit rate                                 : 112 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 417 KiB (27%)
Encoded date                             : UTC 2015-08-07 09:13:02
Tagged date                              : UTC 2015-08-07 09:13:02
```
I'll also attach the mp4 file i'm using to test

https://user-images.githubusercontent.com/8240607/121545899-4b1dc980-c9e1-11eb-9ff4-7fe460bb0743.mp4

**Comment by jonalan7** [comment]
Teistei and for me it's working normally!

**Comment by jonalan7** [comment]
try putting the file in .rar for me to test!

**Comment by jonalan7** [comment]
There are certain types of video formats that are only supported by Google Chrome.
So change the parameter
`useChrome: false
`
for 
`useChrome: true`
