### ISSUE TITLE
Error on sendImageAsStickerGif

### ISSUE THREAD

**Issue by kaiserdj** [orkestral/venom#991]
## Description

I get internal puppeteer error when trying to send some certain webp

## Environment

- **Venom version(s):** 3.0.18
- **OS:** Windows 10
- **Node version:** 15.11.0

## Log Output
```
C:\Users\gonfe\Documents\GitHub\Stickerworld\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: s
    at ExecutionContext._evaluateInternal (C:\Users\gonfe\Documents\GitHub\Stickerworld\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ExecutionContext.evaluate (C:\Users\gonfe\Documents\GitHub\Stickerworld\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command npm run start" terminated with exit code: 1.
```

## Your Code

```
await this.client
            .sendImageAsStickerGif(this.message.chatId, `${this.video.dir}${file}`)
            .then((result) => {
                if (config.debug) {
                    console.log(result);
                }
                tools.conlog_info_force(`[${this.id}] Sticker sent`);
            })
            .catch((err) => {
                tools.conlog_error(`[${this.id}] Error when sending: ${err.toString()}`);
            });
```

## Additional context / Screenshot

Example Webp files that give error: 
[images.zip](https://github.com/orkestral/venom/files/6666102/images.zip)

**Comment by johnparkerg** [comment]
I'm seeing this too.

**Comment by Viniuau** [comment]
Happens quite often to me as well. Even after trimming said GIFs, the error persists.

**Comment by kaiserdj** [comment]
And the error is not because the images weigh more than 1mb, since the ones I have shared in the zip weigh less and give an error.

**Comment by Viniuau** [comment]
![image](https://user-images.githubusercontent.com/19510529/125178190-b1e8fb00-e1b8-11eb-9aeb-de2144655c95.png)
Just happened again. Two different GIFs from Tenor.

**Comment by johnparkerg** [comment]
Why was this issue closed?
